import type { BacktestRun, ConfigParameter, ExecutionAlphaRow, MlTrainingJob, QuantFeatureRow } from "./quant-types";

export const initialBacktestRuns: BacktestRun[] = [
  {
    id: "bt-001",
    name: "momentum_btc_1h",
    strategy: "Momentum",
    status: "promoted",
    period: "2023-01-01 to 2024-01-15",
    trades: 1247,
    winRate: 58.4,
    pnl: 142500,
    sharpe: 1.85,
    maxDrawdown: 12.4,
    completedAt: "2h ago",
    promotedAt: "1h ago",
    liveAllocation: 500000,
  },
  {
    id: "bt-002",
    name: "mean_reversion_eth",
    strategy: "Mean Reversion",
    status: "completed",
    period: "2023-01-01 to 2024-01-15",
    trades: 2156,
    winRate: 62.1,
    pnl: 98400,
    sharpe: 1.52,
    maxDrawdown: 8.7,
    completedAt: "4h ago",
  },
  {
    id: "bt-003",
    name: "arb_eth_btc",
    strategy: "Statistical Arb",
    status: "running",
    period: "2023-06-01 to 2024-01-15",
    trades: 0,
    winRate: 0,
    pnl: 0,
    sharpe: 0,
    maxDrawdown: 0,
    progress: 34,
  },
  {
    id: "bt-004",
    name: "funding_arb_multi",
    strategy: "Funding Arb",
    status: "queued",
    period: "2023-01-01 to 2024-01-15",
    trades: 0,
    winRate: 0,
    pnl: 0,
    sharpe: 0,
    maxDrawdown: 0,
  },
  {
    id: "bt-005",
    name: "trend_following_sol",
    strategy: "Trend Following",
    status: "failed",
    period: "2023-01-01 to 2024-01-15",
    trades: 0,
    winRate: 0,
    pnl: 0,
    sharpe: 0,
    maxDrawdown: 0,
    error: "Insufficient data for SOL before 2023-03",
  },
];

export const mlTrainingJobs: MlTrainingJob[] = [
  {
    id: "ml-001",
    name: "price_predictor_v2",
    model: "LSTM",
    status: "completed",
    accuracy: 67.4,
    loss: 0.032,
    epochs: 100,
    duration: "4h 23m",
    completedAt: "1h ago",
  },
  {
    id: "ml-002",
    name: "signal_classifier",
    model: "XGBoost",
    status: "completed",
    accuracy: 72.1,
    loss: 0.28,
    epochs: 500,
    duration: "45m",
    completedAt: "3h ago",
  },
  {
    id: "ml-003",
    name: "volatility_forecast",
    model: "Transformer",
    status: "running",
    accuracy: 0,
    loss: 0.045,
    epochs: 50,
    duration: "2h 15m",
    progress: 62,
  },
  {
    id: "ml-004",
    name: "regime_detector",
    model: "HMM",
    status: "queued",
    accuracy: 0,
    loss: 0,
    epochs: 0,
    duration: "-",
    progress: 0,
  },
];

export const configParameters: ConfigParameter[] = [
  {
    name: "lookback_period",
    type: "int",
    min: 10,
    max: 200,
    default: 50,
    current: 50,
    description: "Number of bars to look back",
  },
  {
    name: "entry_threshold",
    type: "float",
    min: 0.5,
    max: 3.0,
    default: 1.5,
    current: 1.5,
    description: "Z-score threshold for entry",
  },
  {
    name: "exit_threshold",
    type: "float",
    min: 0.1,
    max: 1.0,
    default: 0.5,
    current: 0.5,
    description: "Z-score threshold for exit",
  },
  {
    name: "max_position_size",
    type: "float",
    min: 0.01,
    max: 1.0,
    default: 0.1,
    current: 0.1,
    description: "Max position as % of portfolio",
  },
  {
    name: "stop_loss_pct",
    type: "float",
    min: 0.5,
    max: 10.0,
    default: 2.0,
    current: 2.0,
    description: "Stop loss percentage",
  },
  {
    name: "use_trailing_stop",
    type: "bool",
    default: true,
    current: true,
    description: "Enable trailing stop loss",
  },
  {
    name: "rebalance_freq",
    type: "string",
    options: ["1m", "5m", "15m", "1h", "4h", "1d"],
    default: "1h",
    current: "1h",
    description: "Rebalancing frequency",
  },
];

export const features: QuantFeatureRow[] = [
  {
    name: "price_momentum_1h",
    category: "Momentum",
    freshness: "2s",
    coverage: "99.8%",
    status: "live",
  },
  {
    name: "volume_profile_15m",
    category: "Volume",
    freshness: "5s",
    coverage: "99.5%",
    status: "live",
  },
  {
    name: "funding_rate_btc",
    category: "Funding",
    freshness: "10s",
    coverage: "100%",
    status: "live",
  },
  {
    name: "correlation_btc_eth",
    category: "Correlation",
    freshness: "1m",
    coverage: "99.2%",
    status: "live",
  },
  {
    name: "volatility_ewma",
    category: "Volatility",
    freshness: "3s",
    coverage: "99.9%",
    status: "live",
  },
  {
    name: "order_imbalance",
    category: "Microstructure",
    freshness: "500ms",
    coverage: "98.5%",
    status: "degraded",
  },
  {
    name: "sentiment_score",
    category: "Alternative",
    freshness: "5m",
    coverage: "95.0%",
    status: "live",
  },
];

export const executionAlpha: ExecutionAlphaRow[] = [
  {
    strategy: "BTC Basis v3",
    trades: 1247,
    signal: "+$412k",
    executed: "+$398k",
    slippage: "-$14k",
    alpha: "+$3.2k",
  },
  {
    strategy: "ETH Staked",
    trades: 892,
    signal: "+$289k",
    executed: "+$281k",
    slippage: "-$8k",
    alpha: "+$1.8k",
  },
  {
    strategy: "ML Directional",
    trades: 567,
    signal: "-$18k",
    executed: "-$22k",
    slippage: "-$4k",
    alpha: "-$1.2k",
  },
  {
    strategy: "Sports Arb",
    trades: 234,
    signal: "+$44k",
    executed: "+$42k",
    slippage: "-$2k",
    alpha: "+$0.5k",
  },
];
