"""Venue error classifications for infrastructure providers (RPC, indexers, relays).

These are transport-layer providers, NOT venues. We don't trade on them — we use them
to reach venues (e.g., Alchemy errors happen when talking to Aave, not Alchemy itself).
"""

from __future__ import annotations

from ._types import ErrorAction, VenueErrorClassification, ve

INFRA_ERRORS: dict[str, list[VenueErrorClassification]] = {
    "alchemy": [
        ve(
            "alchemy",
            "-32600",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Invalid request",
        ),
        ve(
            "alchemy",
            "-32603",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Internal error",
        ),
        ve(
            "alchemy",
            "429",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Rate limit exceeded",
        ),
        ve(
            "alchemy",
            "401",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Unauthorized",
        ),
        ve(
            "alchemy",
            "400",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Bad request",
        ),
        ve(
            "alchemy",
            "500",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Internal server error",
        ),
    ],
    "thegraph": [
        ve(
            "thegraph",
            "SUBGRAPH_NOT_FOUND",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Subgraph not found or invalid ID",
        ),
        ve(
            "thegraph",
            "RATE_LIMIT",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Rate limit exceeded (HTTP 429 or GraphQL rate limit message)",
        ),
        ve(
            "thegraph",
            "AUTH_FAILURE",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="API key invalid, malformed, or not found",
        ),
        ve(
            "thegraph",
            "QUERY_ERROR",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="GraphQL query syntax or schema error",
        ),
        ve(
            "thegraph",
            "INDEXING_ERROR",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Subgraph indexing in progress or failed — data may be stale",
        ),
        ve(
            "thegraph",
            "CONNECTION_ERROR",
            retry=True,
            reconnect=True,
            action=ErrorAction.RECONNECT,
            desc="Network timeout or connection failure to The Graph gateway",
        ),
        ve(
            "thegraph",
            "429",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="HTTP rate limit exceeded",
        ),
        ve(
            "thegraph",
            "401",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Unauthorized",
        ),
        ve(
            "thegraph",
            "400",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Bad request",
        ),
        ve(
            "thegraph",
            "500",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Internal server error",
        ),
    ],
    "bloxroute": [
        ve(
            "bloxroute",
            "-32600",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Invalid request",
        ),
        ve(
            "bloxroute",
            "-32603",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Internal error",
        ),
        ve(
            "bloxroute",
            "429",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Rate limit exceeded",
        ),
        ve(
            "bloxroute",
            "401",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Unauthorized",
        ),
        ve(
            "bloxroute",
            "400",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Bad request",
        ),
        ve(
            "bloxroute",
            "500",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Internal server error",
        ),
    ],
    "onchain_revert": [
        ve(
            "onchain_revert",
            "EXECUTION_REVERTED",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="EVM transaction reverted — contract logic rejected the call",
        ),
        ve(
            "onchain_revert",
            "OUT_OF_GAS",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Transaction ran out of gas — increase gas limit",
        ),
        ve(
            "onchain_revert",
            "INSUFFICIENT_FUNDS",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Sender has insufficient ETH for gas + value",
        ),
        ve(
            "onchain_revert",
            "NONCE_TOO_LOW",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Transaction nonce already used — resync nonce",
        ),
        ve(
            "onchain_revert",
            "429",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="HTTP rate limit exceeded",
        ),
        ve(
            "onchain_revert",
            "401",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Unauthorized",
        ),
        ve(
            "onchain_revert",
            "400",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Bad request",
        ),
        ve(
            "onchain_revert",
            "500",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Internal server error",
        ),
    ],
}
