// AUTO-GENERATED from UAC archetype_capability_manifest.json.
// Do not edit by hand. Re-run:
//   bash unified-trading-pm/scripts/propagation/sync-archetype-capability-to-ui.sh --write
// SSOT: unified-api-contracts/unified_api_contracts/internal/architecture_v2/archetype_capability_manifest.json
// Codex narrative: unified-trading-pm/codex/09-strategy/architecture-v2/category-instrument-coverage.md

import type { StrategyArchetype, VenueCategoryV2 } from "./enums";

export type InstrumentTypeV2 =
  | "spot"
  | "perp"
  | "dated_future"
  | "option"
  | "lending"
  | "staking"
  | "lp"
  | "event_settled";

export const INSTRUMENT_TYPES_V2: readonly InstrumentTypeV2[] = [
  "spot",
  "perp",
  "dated_future",
  "option",
  "lending",
  "staking",
  "lp",
  "event_settled",
] as const;

export type CoverageStatus = "SUPPORTED" | "PARTIAL" | "BLOCKED" | "NOT_APPLICABLE";

export type SignalVariant =
  | "price"
  | "funding_rate"
  | "basis"
  | "iv_dispersion"
  | "vol_metric"
  | "rate_spread"
  | "liquidation_bonus"
  | "odds"
  | "event_surprise"
  | "delta_as_expression"
  | "staking_yield"
  | "zscore_reversion"
  | "momentum_ranking"
  | "spread_capture";

export type RollMode = "rolling" | "fixed" | "both" | "n/a";

export interface CoverageCell {
  archetype: StrategyArchetype;
  category: VenueCategoryV2;
  instrumentType: InstrumentTypeV2;
  status: CoverageStatus;
  representativeVenueIds: readonly string[];
  signalVariants: readonly SignalVariant[];
  rollMode: RollMode;
  notes: string;
  blockListRefs: readonly string[];
  representativeSlotLabels: readonly string[];
}

export interface ArchetypeCoverage {
  archetype: StrategyArchetype;
  usesRollingFutures: boolean;
  cells: readonly CoverageCell[];
}

const ml_directional_continuous: ArchetypeCoverage = {
  archetype: "ML_DIRECTIONAL_CONTINUOUS",
  usesRollingFutures: true,
  cells: [
    {
      archetype: "ML_DIRECTIONAL_CONTINUOUS",
      category: "CEFI",
      instrumentType: "spot",
      status: "SUPPORTED",
      representativeVenueIds: ["binance", "okx", "bybit", "hyperliquid"],
      signalVariants: ["price"],
      rollMode: "n/a",
      notes: "",
      blockListRefs: [],
      representativeSlotLabels: ["ML_DIRECTIONAL_CONTINUOUS@binance-btc-usdt-5m-usdt-prod"],
    },
    {
      archetype: "ML_DIRECTIONAL_CONTINUOUS",
      category: "CEFI",
      instrumentType: "perp",
      status: "SUPPORTED",
      representativeVenueIds: ["binance", "okx", "bybit", "hyperliquid", "deribit"],
      signalVariants: ["price"],
      rollMode: "n/a",
      notes: "",
      blockListRefs: [],
      representativeSlotLabels: ["ML_DIRECTIONAL_CONTINUOUS@binance-btc-perp-5m-usdt-prod", "ML_DIRECTIONAL_CONTINUOUS@hyperliquid-eth-perp-5m-usdt-v2-prod"],
    },
    {
      archetype: "ML_DIRECTIONAL_CONTINUOUS",
      category: "CEFI",
      instrumentType: "dated_future",
      status: "PARTIAL",
      representativeVenueIds: ["deribit"],
      signalVariants: ["price"],
      rollMode: "both",
      notes: "Settlement-aware reconciliation not batch-tested on Deribit dated.",
      blockListRefs: [],
      representativeSlotLabels: ["ML_DIRECTIONAL_CONTINUOUS@deribit-btc-dated-daily-usdt-prod"],
    },
    {
      archetype: "ML_DIRECTIONAL_CONTINUOUS",
      category: "CEFI",
      instrumentType: "option",
      status: "PARTIAL",
      representativeVenueIds: ["deribit", "okx"],
      signalVariants: ["delta_as_expression"],
      rollMode: "n/a",
      notes: "Expression axis supports atm_call / 25d_call / synthetic; multi-leg option router pending.",
      blockListRefs: [],
      representativeSlotLabels: ["ML_DIRECTIONAL_CONTINUOUS@deribit-btc-atm_call-daily-usdt-prod"],
    },
    {
      archetype: "ML_DIRECTIONAL_CONTINUOUS",
      category: "DEFI",
      instrumentType: "spot",
      status: "PARTIAL",
      representativeVenueIds: ["uniswap_v3", "balancer"],
      signalVariants: ["price"],
      rollMode: "n/a",
      notes: "Pricing-fidelity flag missing (UAC gap #8) — thin pools not tick-stream-reliable.",
      blockListRefs: [],
      representativeSlotLabels: ["ML_DIRECTIONAL_CONTINUOUS@uniswap-ethereum-weth-usdc-5m-usdc-prod"],
    },
    {
      archetype: "ML_DIRECTIONAL_CONTINUOUS",
      category: "DEFI",
      instrumentType: "perp",
      status: "SUPPORTED",
      representativeVenueIds: ["hyperliquid", "gmx_v2", "drift"],
      signalVariants: ["price"],
      rollMode: "n/a",
      notes: "",
      blockListRefs: [],
      representativeSlotLabels: ["ML_DIRECTIONAL_CONTINUOUS@gmx-arbitrum-eth-perp-5m-usdc-prod"],
    },
    {
      archetype: "ML_DIRECTIONAL_CONTINUOUS",
      category: "DEFI",
      instrumentType: "dated_future",
      status: "BLOCKED",
      representativeVenueIds: [],
      signalVariants: [],
      rollMode: "n/a",
      notes: "No DeFi dated-future venue.",
      blockListRefs: ["BL-2"],
      representativeSlotLabels: [],
    },
    {
      archetype: "ML_DIRECTIONAL_CONTINUOUS",
      category: "DEFI",
      instrumentType: "option",
      status: "BLOCKED",
      representativeVenueIds: [],
      signalVariants: [],
      rollMode: "n/a",
      notes: "No supported DeFi options venue (Lyra / Dopex archived).",
      blockListRefs: ["BL-1"],
      representativeSlotLabels: [],
    },
    {
      archetype: "ML_DIRECTIONAL_CONTINUOUS",
      category: "TRADFI",
      instrumentType: "spot",
      status: "PARTIAL",
      representativeVenueIds: ["ibkr"],
      signalVariants: ["price"],
      rollMode: "n/a",
      notes: "IBKR FIX adapter symbol universe declaration incomplete.",
      blockListRefs: [],
      representativeSlotLabels: ["ML_DIRECTIONAL_CONTINUOUS@ibkr-spy-1m-usd-prod"],
    },
    {
      archetype: "ML_DIRECTIONAL_CONTINUOUS",
      category: "TRADFI",
      instrumentType: "dated_future",
      status: "PARTIAL",
      representativeVenueIds: ["cme", "ice"],
      signalVariants: ["price"],
      rollMode: "both",
      notes: "Adapter batch-tested only for ES / NQ / CL; roll service required (BL-10).",
      blockListRefs: ["BL-10"],
      representativeSlotLabels: ["ML_DIRECTIONAL_CONTINUOUS@cme-es-dated-1m-usd-prod", "ML_DIRECTIONAL_CONTINUOUS@ice-brent-dated-daily-usd-prod"],
    },
    {
      archetype: "ML_DIRECTIONAL_CONTINUOUS",
      category: "TRADFI",
      instrumentType: "option",
      status: "PARTIAL",
      representativeVenueIds: ["cboe"],
      signalVariants: ["delta_as_expression"],
      rollMode: "n/a",
      notes: "CME options-on-futures not declared in UAC.",
      blockListRefs: [],
      representativeSlotLabels: ["ML_DIRECTIONAL_CONTINUOUS@ibkr-cboe-spy-atm_call-daily-usd-prod"],
    },
  ],
};

const ml_directional_event_settled: ArchetypeCoverage = {
  archetype: "ML_DIRECTIONAL_EVENT_SETTLED",
  usesRollingFutures: false,
  cells: [
    {
      archetype: "ML_DIRECTIONAL_EVENT_SETTLED",
      category: "SPORTS",
      instrumentType: "event_settled",
      status: "SUPPORTED",
      representativeVenueIds: ["unity", "betfair_direct", "smarkets_direct", "matchbook_direct"],
      signalVariants: ["odds"],
      rollMode: "n/a",
      notes: "",
      blockListRefs: [],
      representativeSlotLabels: ["ML_DIRECTIONAL_EVENT_SETTLED@unity-epl-1x2-usd-prod", "ML_DIRECTIONAL_EVENT_SETTLED@unity-nba-moneyline-usd-prod", "ML_DIRECTIONAL_EVENT_SETTLED@betfair-direct-epl-1x2-gbp-prod"],
    },
    {
      archetype: "ML_DIRECTIONAL_EVENT_SETTLED",
      category: "PREDICTION",
      instrumentType: "event_settled",
      status: "SUPPORTED",
      representativeVenueIds: ["polymarket"],
      signalVariants: ["odds"],
      rollMode: "n/a",
      notes: "",
      blockListRefs: [],
      representativeSlotLabels: ["ML_DIRECTIONAL_EVENT_SETTLED@polymarket-us-election-president-usdc-prod"],
    },
    {
      archetype: "ML_DIRECTIONAL_EVENT_SETTLED",
      category: "PREDICTION",
      instrumentType: "event_settled",
      status: "BLOCKED",
      representativeVenueIds: ["kalshi"],
      signalVariants: [],
      rollMode: "n/a",
      notes: "Kalshi execution adapter pending.",
      blockListRefs: ["BL-5"],
      representativeSlotLabels: [],
    },
  ],
};

const rules_directional_continuous: ArchetypeCoverage = {
  archetype: "RULES_DIRECTIONAL_CONTINUOUS",
  usesRollingFutures: true,
  cells: [
    {
      archetype: "RULES_DIRECTIONAL_CONTINUOUS",
      category: "CEFI",
      instrumentType: "spot",
      status: "SUPPORTED",
      representativeVenueIds: ["binance", "okx", "bybit", "hyperliquid"],
      signalVariants: ["price"],
      rollMode: "n/a",
      notes: "",
      blockListRefs: [],
      representativeSlotLabels: ["RULES_DIRECTIONAL_CONTINUOUS@binance-btc-usdt-15m-macd-usdt-prod"],
    },
    {
      archetype: "RULES_DIRECTIONAL_CONTINUOUS",
      category: "CEFI",
      instrumentType: "perp",
      status: "SUPPORTED",
      representativeVenueIds: ["binance", "okx", "bybit", "hyperliquid"],
      signalVariants: ["price", "funding_rate"],
      rollMode: "n/a",
      notes: "",
      blockListRefs: [],
      representativeSlotLabels: ["RULES_DIRECTIONAL_CONTINUOUS@binance-btc-perp-15m-ta-funding-usdt-prod", "RULES_DIRECTIONAL_CONTINUOUS@hyperliquid-btc-perp-5m-vwap-usdt-prod"],
    },
    {
      archetype: "RULES_DIRECTIONAL_CONTINUOUS",
      category: "CEFI",
      instrumentType: "dated_future",
      status: "PARTIAL",
      representativeVenueIds: ["deribit"],
      signalVariants: ["price"],
      rollMode: "both",
      notes: "Settlement-aware rule harness not batch-tested.",
      blockListRefs: [],
      representativeSlotLabels: [],
    },
    {
      archetype: "RULES_DIRECTIONAL_CONTINUOUS",
      category: "CEFI",
      instrumentType: "option",
      status: "BLOCKED",
      representativeVenueIds: [],
      signalVariants: [],
      rollMode: "n/a",
      notes: "Directional options via rules is non-standard; use VOL_TRADING_OPTIONS or ML with expression=atm_call.",
      blockListRefs: ["BL-4"],
      representativeSlotLabels: [],
    },
    {
      archetype: "RULES_DIRECTIONAL_CONTINUOUS",
      category: "DEFI",
      instrumentType: "spot",
      status: "PARTIAL",
      representativeVenueIds: ["uniswap_v3"],
      signalVariants: ["price"],
      rollMode: "n/a",
      notes: "Same pricing-fidelity concern as ML DeFi spot.",
      blockListRefs: [],
      representativeSlotLabels: [],
    },
    {
      archetype: "RULES_DIRECTIONAL_CONTINUOUS",
      category: "DEFI",
      instrumentType: "perp",
      status: "PARTIAL",
      representativeVenueIds: ["gmx_v2", "drift", "hyperliquid"],
      signalVariants: ["price", "funding_rate"],
      rollMode: "n/a",
      notes: "No codex instance examples yet.",
      blockListRefs: [],
      representativeSlotLabels: ["RULES_DIRECTIONAL_CONTINUOUS@gmx-arbitrum-eth-perp-1h-ta-usdc-prod"],
    },
    {
      archetype: "RULES_DIRECTIONAL_CONTINUOUS",
      category: "TRADFI",
      instrumentType: "spot",
      status: "PARTIAL",
      representativeVenueIds: ["ibkr"],
      signalVariants: ["price"],
      rollMode: "n/a",
      notes: "IBKR FIX adapter declaration gap.",
      blockListRefs: [],
      representativeSlotLabels: ["RULES_DIRECTIONAL_CONTINUOUS@ibkr-spy-daily-donchian-usd-prod"],
    },
    {
      archetype: "RULES_DIRECTIONAL_CONTINUOUS",
      category: "TRADFI",
      instrumentType: "dated_future",
      status: "PARTIAL",
      representativeVenueIds: ["cme", "ice"],
      signalVariants: ["price"],
      rollMode: "both",
      notes: "Adapter coverage partial; roll service required (BL-10).",
      blockListRefs: ["BL-10"],
      representativeSlotLabels: ["RULES_DIRECTIONAL_CONTINUOUS@cme-es-dated-1m-ta-usd-prod"],
    },
    {
      archetype: "RULES_DIRECTIONAL_CONTINUOUS",
      category: "TRADFI",
      instrumentType: "option",
      status: "BLOCKED",
      representativeVenueIds: [],
      signalVariants: [],
      rollMode: "n/a",
      notes: "Same BL-4 — directional options via rules is non-standard.",
      blockListRefs: ["BL-4"],
      representativeSlotLabels: [],
    },
  ],
};

const rules_directional_event_settled: ArchetypeCoverage = {
  archetype: "RULES_DIRECTIONAL_EVENT_SETTLED",
  usesRollingFutures: false,
  cells: [
    {
      archetype: "RULES_DIRECTIONAL_EVENT_SETTLED",
      category: "SPORTS",
      instrumentType: "event_settled",
      status: "PARTIAL",
      representativeVenueIds: ["unity", "betfair_direct", "smarkets_direct"],
      signalVariants: ["odds"],
      rollMode: "n/a",
      notes: "Engine code complete; docs + example instances minor gap.",
      blockListRefs: [],
      representativeSlotLabels: ["RULES_DIRECTIONAL_EVENT_SETTLED@unity-epl-xg-diff-usd-prod", "RULES_DIRECTIONAL_EVENT_SETTLED@unity-nba-rest-days-rule-usd-prod"],
    },
    {
      archetype: "RULES_DIRECTIONAL_EVENT_SETTLED",
      category: "PREDICTION",
      instrumentType: "event_settled",
      status: "PARTIAL",
      representativeVenueIds: ["polymarket"],
      signalVariants: ["odds"],
      rollMode: "n/a",
      notes: "Docs + example instances gap.",
      blockListRefs: [],
      representativeSlotLabels: ["RULES_DIRECTIONAL_EVENT_SETTLED@polymarket-btc-price-band-rule-usdc-prod"],
    },
  ],
};

const carry_basis_dated: ArchetypeCoverage = {
  archetype: "CARRY_BASIS_DATED",
  usesRollingFutures: true,
  cells: [
    {
      archetype: "CARRY_BASIS_DATED",
      category: "CEFI",
      instrumentType: "dated_future",
      status: "SUPPORTED",
      representativeVenueIds: ["binance", "coinbase", "deribit"],
      signalVariants: ["basis"],
      rollMode: "both",
      notes: "Spot + dated combo. Default rolls with front; expiry-targeted uses -fixed-.",
      blockListRefs: [],
      representativeSlotLabels: ["CARRY_BASIS_DATED@binance-deribit-btc-dated-usdt-prod", "CARRY_BASIS_DATED@binance-deribit-btc-fixed-dec25-usdt-prod"],
    },
    {
      archetype: "CARRY_BASIS_DATED",
      category: "CEFI",
      instrumentType: "option",
      status: "PARTIAL",
      representativeVenueIds: ["deribit"],
      signalVariants: ["basis"],
      rollMode: "n/a",
      notes: "Put-call parity synthetic expression; no worked instance yet.",
      blockListRefs: [],
      representativeSlotLabels: ["CARRY_BASIS_DATED@deribit-btc-parity-synthetic-usdt-prod"],
    },
    {
      archetype: "CARRY_BASIS_DATED",
      category: "DEFI",
      instrumentType: "dated_future",
      status: "BLOCKED",
      representativeVenueIds: [],
      signalVariants: [],
      rollMode: "n/a",
      notes: "No DeFi dated-future venue.",
      blockListRefs: ["BL-2"],
      representativeSlotLabels: [],
    },
    {
      archetype: "CARRY_BASIS_DATED",
      category: "TRADFI",
      instrumentType: "dated_future",
      status: "PARTIAL",
      representativeVenueIds: ["ibkr", "cme", "ice"],
      signalVariants: ["basis"],
      rollMode: "both",
      notes: "IBKR ↔ CME cross-venue routing policy not declared (UAC gap #10).",
      blockListRefs: ["BL-10"],
      representativeSlotLabels: ["CARRY_BASIS_DATED@ibkr-cme-spy-es-dated-usd-prod", "CARRY_BASIS_DATED@ibkr-ice-brent-fixed-feb26-usd-prod"],
    },
  ],
};

const carry_basis_perp: ArchetypeCoverage = {
  archetype: "CARRY_BASIS_PERP",
  usesRollingFutures: false,
  cells: [
    {
      archetype: "CARRY_BASIS_PERP",
      category: "CEFI",
      instrumentType: "perp",
      status: "SUPPORTED",
      representativeVenueIds: ["binance", "okx", "bybit", "hyperliquid", "deribit"],
      signalVariants: ["funding_rate"],
      rollMode: "n/a",
      notes: "Single-venue netted (most capital-efficient) or cross-venue LEADER_HEDGE.",
      blockListRefs: [],
      representativeSlotLabels: ["CARRY_BASIS_PERP@binance-btc-usdt-prod", "CARRY_BASIS_PERP@binance-bybit-btc-usdt-prod"],
    },
    {
      archetype: "CARRY_BASIS_PERP",
      category: "DEFI",
      instrumentType: "perp",
      status: "SUPPORTED",
      representativeVenueIds: ["uniswap_v3", "hyperliquid", "gmx_v2", "drift", "lido"],
      signalVariants: ["funding_rate", "staking_yield"],
      rollMode: "n/a",
      notes: "Same-chain SUPPORTED; cross-chain PARTIAL (bridge latency).",
      blockListRefs: [],
      representativeSlotLabels: ["CARRY_BASIS_PERP@uniswap-hyperliquid-eth-usdt-prod", "CARRY_BASIS_PERP@lido-hyperliquid-steth-usdt-prod"],
    },
  ],
};

const carry_staked_basis: ArchetypeCoverage = {
  archetype: "CARRY_STAKED_BASIS",
  usesRollingFutures: false,
  cells: [
    {
      archetype: "CARRY_STAKED_BASIS",
      category: "DEFI",
      instrumentType: "staking",
      status: "SUPPORTED",
      representativeVenueIds: ["lido", "rocketpool", "jito", "marinade", "aave_v3", "kamino", "hyperliquid", "gmx_v2", "drift"],
      signalVariants: ["staking_yield", "funding_rate", "rate_spread"],
      rollMode: "n/a",
      notes: "3-leg ATOMIC (stake + lending + perp). Ethereum (Lido/RocketPool + Aave + HL/GMX) and Solana (Jito/Marinade + Kamino + Drift).",
      blockListRefs: [],
      representativeSlotLabels: ["CARRY_STAKED_BASIS@lido-aave-hyperliquid-eth-prod", "CARRY_STAKED_BASIS@jito-kamino-drift-sol-usdc-prod"],
    },
  ],
};

const carry_recursive_staked: ArchetypeCoverage = {
  archetype: "CARRY_RECURSIVE_STAKED",
  usesRollingFutures: false,
  cells: [
    {
      archetype: "CARRY_RECURSIVE_STAKED",
      category: "DEFI",
      instrumentType: "staking",
      status: "SUPPORTED",
      representativeVenueIds: ["lido", "rocketpool", "jito", "marinade", "aave_v3", "kamino"],
      signalVariants: ["staking_yield", "rate_spread"],
      rollMode: "n/a",
      notes: "Recursive lending loop (up to 6 loops). Per-protocol bonus schedule gap in UAC (#4).",
      blockListRefs: [],
      representativeSlotLabels: ["CARRY_RECURSIVE_STAKED@lido-aave-steth-ltv70-ethereum-prod", "CARRY_RECURSIVE_STAKED@jito-kamino-jitosol-ltv70-solana-prod"],
    },
  ],
};

const yield_rotation_lending: ArchetypeCoverage = {
  archetype: "YIELD_ROTATION_LENDING",
  usesRollingFutures: false,
  cells: [
    {
      archetype: "YIELD_ROTATION_LENDING",
      category: "CEFI",
      instrumentType: "lending",
      status: "BLOCKED",
      representativeVenueIds: [],
      signalVariants: [],
      rollMode: "n/a",
      notes: "CeFi lending out-of-scope: withdrawal lockups + counterparty risk (BL-3).",
      blockListRefs: ["BL-3"],
      representativeSlotLabels: [],
    },
    {
      archetype: "YIELD_ROTATION_LENDING",
      category: "DEFI",
      instrumentType: "lending",
      status: "SUPPORTED",
      representativeVenueIds: ["aave_v3", "compound_v3", "euler", "morpho", "kamino"],
      signalVariants: ["rate_spread"],
      rollMode: "n/a",
      notes: "Multi-chain via Circle CCTP / LayerZero Stargate. Bridge cost + latency modeled.",
      blockListRefs: [],
      representativeSlotLabels: ["YIELD_ROTATION_LENDING@aave-multichain-usdc-prod", "YIELD_ROTATION_LENDING@aave-compound-morpho-usdc-ethereum-prod", "YIELD_ROTATION_LENDING@kamino-solana-usdc-prod"],
    },
  ],
};

const yield_staking_simple: ArchetypeCoverage = {
  archetype: "YIELD_STAKING_SIMPLE",
  usesRollingFutures: false,
  cells: [
    {
      archetype: "YIELD_STAKING_SIMPLE",
      category: "DEFI",
      instrumentType: "staking",
      status: "SUPPORTED",
      representativeVenueIds: ["lido", "rocketpool", "etherfi", "jito", "marinade"],
      signalVariants: ["staking_yield"],
      rollMode: "n/a",
      notes: "Pure staking, no hedge. Ethereum (stETH / rETH / eETH) and Solana (JitoSOL / mSOL).",
      blockListRefs: [],
      representativeSlotLabels: ["YIELD_STAKING_SIMPLE@lido-steth-ethereum-eth-prod", "YIELD_STAKING_SIMPLE@jito-jitosol-solana-sol-prod"],
    },
  ],
};

const arbitrage_price_dispersion: ArchetypeCoverage = {
  archetype: "ARBITRAGE_PRICE_DISPERSION",
  usesRollingFutures: true,
  cells: [
    {
      archetype: "ARBITRAGE_PRICE_DISPERSION",
      category: "CEFI",
      instrumentType: "spot",
      status: "SUPPORTED",
      representativeVenueIds: ["binance", "okx", "bybit", "hyperliquid"],
      signalVariants: ["price"],
      rollMode: "n/a",
      notes: "",
      blockListRefs: [],
      representativeSlotLabels: ["ARBITRAGE_PRICE_DISPERSION@binance-bybit-btc-usdt-prod"],
    },
    {
      archetype: "ARBITRAGE_PRICE_DISPERSION",
      category: "CEFI",
      instrumentType: "perp",
      status: "PARTIAL",
      representativeVenueIds: ["binance", "okx", "bybit", "hyperliquid", "deribit"],
      signalVariants: ["price", "funding_rate"],
      rollMode: "n/a",
      notes: "UAC lacks funding_arb flag distinct from price-arb (gap #2).",
      blockListRefs: [],
      representativeSlotLabels: ["ARBITRAGE_PRICE_DISPERSION@binance-bybit-btc-perp-usdt-prod", "ARBITRAGE_PRICE_DISPERSION@multi-cex-btc-funding-usdt-prod"],
    },
    {
      archetype: "ARBITRAGE_PRICE_DISPERSION",
      category: "CEFI",
      instrumentType: "option",
      status: "PARTIAL",
      representativeVenueIds: ["deribit", "okx"],
      signalVariants: ["iv_dispersion"],
      rollMode: "n/a",
      notes: "vol_arb not a separate capability; multi-leg vol-arb algo pending.",
      blockListRefs: [],
      representativeSlotLabels: ["ARBITRAGE_PRICE_DISPERSION@deribit-okx-btc-vol-usdt-prod"],
    },
    {
      archetype: "ARBITRAGE_PRICE_DISPERSION",
      category: "DEFI",
      instrumentType: "spot",
      status: "SUPPORTED",
      representativeVenueIds: ["uniswap_v3", "balancer", "curve", "sushiswap"],
      signalVariants: ["price"],
      rollMode: "n/a",
      notes: "",
      blockListRefs: [],
      representativeSlotLabels: ["ARBITRAGE_PRICE_DISPERSION@multi-dex-eth-usdc-ethereum-prod"],
    },
    {
      archetype: "ARBITRAGE_PRICE_DISPERSION",
      category: "DEFI",
      instrumentType: "perp",
      status: "SUPPORTED",
      representativeVenueIds: ["hyperliquid", "gmx_v2", "drift"],
      signalVariants: ["price", "funding_rate"],
      rollMode: "n/a",
      notes: "",
      blockListRefs: [],
      representativeSlotLabels: ["ARBITRAGE_PRICE_DISPERSION@hyperliquid-gmx-eth-perp-usdc-prod"],
    },
    {
      archetype: "ARBITRAGE_PRICE_DISPERSION",
      category: "DEFI",
      instrumentType: "lp",
      status: "PARTIAL",
      representativeVenueIds: ["uniswap_v3"],
      signalVariants: ["price"],
      rollMode: "n/a",
      notes: "Flash-loan receiver per-chain registry missing from UAC (gap #3).",
      blockListRefs: [],
      representativeSlotLabels: ["ARBITRAGE_PRICE_DISPERSION@uniswap-flashloan-eth-usdc-ethereum-prod"],
    },
    {
      archetype: "ARBITRAGE_PRICE_DISPERSION",
      category: "DEFI",
      instrumentType: "option",
      status: "BLOCKED",
      representativeVenueIds: [],
      signalVariants: [],
      rollMode: "n/a",
      notes: "No supported DeFi options venue.",
      blockListRefs: ["BL-1"],
      representativeSlotLabels: [],
    },
    {
      archetype: "ARBITRAGE_PRICE_DISPERSION",
      category: "TRADFI",
      instrumentType: "spot",
      status: "PARTIAL",
      representativeVenueIds: ["ibkr", "cme"],
      signalVariants: ["price"],
      rollMode: "n/a",
      notes: "IBKR smart-router absorbs most intra-TradFi spot arb.",
      blockListRefs: [],
      representativeSlotLabels: [],
    },
    {
      archetype: "ARBITRAGE_PRICE_DISPERSION",
      category: "TRADFI",
      instrumentType: "dated_future",
      status: "PARTIAL",
      representativeVenueIds: ["cme", "ice"],
      signalVariants: ["price"],
      rollMode: "both",
      notes: "Cross-product routing policy not declared in UAC (gap #10).",
      blockListRefs: ["BL-10"],
      representativeSlotLabels: ["ARBITRAGE_PRICE_DISPERSION@cme-es-nq-dated-ratio-usd-prod", "ARBITRAGE_PRICE_DISPERSION@cme-es-calendar-fixed-dec25-mar26-usd-prod"],
    },
    {
      archetype: "ARBITRAGE_PRICE_DISPERSION",
      category: "TRADFI",
      instrumentType: "option",
      status: "PARTIAL",
      representativeVenueIds: ["cboe"],
      signalVariants: ["iv_dispersion"],
      rollMode: "n/a",
      notes: "Same-surface no-arb (butterfly / calendar / parity) on CBOE via IBKR.",
      blockListRefs: [],
      representativeSlotLabels: ["ARBITRAGE_PRICE_DISPERSION@cboe-spy-surface-noarb-usd-prod"],
    },
    {
      archetype: "ARBITRAGE_PRICE_DISPERSION",
      category: "SPORTS",
      instrumentType: "event_settled",
      status: "SUPPORTED",
      representativeVenueIds: ["unity", "betfair_direct", "smarkets_direct"],
      signalVariants: ["odds", "price"],
      rollMode: "n/a",
      notes: "Unity single-wallet makes cross-book arb near-atomic.",
      blockListRefs: [],
      representativeSlotLabels: ["ARBITRAGE_PRICE_DISPERSION@unity-epl-1x2-usd-prod", "ARBITRAGE_PRICE_DISPERSION@betfair-smarkets-epl-1x2-gbp-prod"],
    },
    {
      archetype: "ARBITRAGE_PRICE_DISPERSION",
      category: "PREDICTION",
      instrumentType: "event_settled",
      status: "SUPPORTED",
      representativeVenueIds: ["polymarket", "unity", "betfair_direct"],
      signalVariants: ["price", "odds"],
      rollMode: "n/a",
      notes: "Cross-category arb (Polymarket ↔ Unity / Betfair for correlated markets).",
      blockListRefs: [],
      representativeSlotLabels: ["ARBITRAGE_PRICE_DISPERSION@polymarket-unity-elections-usdc-prod"],
    },
  ],
};

const liquidation_capture: ArchetypeCoverage = {
  archetype: "LIQUIDATION_CAPTURE",
  usesRollingFutures: false,
  cells: [
    {
      archetype: "LIQUIDATION_CAPTURE",
      category: "CEFI",
      instrumentType: "perp",
      status: "PARTIAL",
      representativeVenueIds: ["hyperliquid"],
      signalVariants: ["liquidation_bonus"],
      rollMode: "n/a",
      notes: "Hyperliquid liquidation feed; edge limited to bid-ladder placement near liq price.",
      blockListRefs: [],
      representativeSlotLabels: ["LIQUIDATION_CAPTURE@hyperliquid-btc-perp-bidladder-usdt-prod"],
    },
    {
      archetype: "LIQUIDATION_CAPTURE",
      category: "DEFI",
      instrumentType: "lending",
      status: "SUPPORTED",
      representativeVenueIds: ["aave_v3", "kamino"],
      signalVariants: ["liquidation_bonus"],
      rollMode: "n/a",
      notes: "Flash-loan receiver contract required per-chain. Aave V3 + Kamino primary.",
      blockListRefs: [],
      representativeSlotLabels: ["LIQUIDATION_CAPTURE@aave-ethereum-eth-usdc-prod", "LIQUIDATION_CAPTURE@aave-arbitrum-eth-usdc-prod", "LIQUIDATION_CAPTURE@kamino-solana-sol-usdc-prod"],
    },
    {
      archetype: "LIQUIDATION_CAPTURE",
      category: "DEFI",
      instrumentType: "perp",
      status: "PARTIAL",
      representativeVenueIds: ["gmx_v2"],
      signalVariants: ["liquidation_bonus"],
      rollMode: "n/a",
      notes: "GMX perp liquidations have different economics than lending liquidations.",
      blockListRefs: [],
      representativeSlotLabels: ["LIQUIDATION_CAPTURE@gmx-arbitrum-eth-perp-usdc-prod"],
    },
  ],
};

const market_making_continuous: ArchetypeCoverage = {
  archetype: "MARKET_MAKING_CONTINUOUS",
  usesRollingFutures: true,
  cells: [
    {
      archetype: "MARKET_MAKING_CONTINUOUS",
      category: "CEFI",
      instrumentType: "spot",
      status: "SUPPORTED",
      representativeVenueIds: ["binance", "okx", "bybit", "hyperliquid"],
      signalVariants: ["spread_capture"],
      rollMode: "n/a",
      notes: "",
      blockListRefs: [],
      representativeSlotLabels: ["MARKET_MAKING_CONTINUOUS@binance-btc-usdt-mm-usdt-prod"],
    },
    {
      archetype: "MARKET_MAKING_CONTINUOUS",
      category: "CEFI",
      instrumentType: "perp",
      status: "SUPPORTED",
      representativeVenueIds: ["binance", "okx", "bybit", "hyperliquid", "deribit"],
      signalVariants: ["spread_capture", "funding_rate"],
      rollMode: "n/a",
      notes: "",
      blockListRefs: [],
      representativeSlotLabels: ["MARKET_MAKING_CONTINUOUS@hyperliquid-eth-perp-mm-usdt-prod"],
    },
    {
      archetype: "MARKET_MAKING_CONTINUOUS",
      category: "CEFI",
      instrumentType: "option",
      status: "PARTIAL",
      representativeVenueIds: ["deribit", "okx"],
      signalVariants: ["spread_capture", "vol_metric"],
      rollMode: "n/a",
      notes: "Needs MultiLegOrderCapability (UAC gap #7).",
      blockListRefs: [],
      representativeSlotLabels: ["MARKET_MAKING_CONTINUOUS@deribit-btc-option-mm-usdt-prod"],
    },
    {
      archetype: "MARKET_MAKING_CONTINUOUS",
      category: "DEFI",
      instrumentType: "lp",
      status: "SUPPORTED",
      representativeVenueIds: ["uniswap_v3", "uniswap_v4", "orca", "raydium", "curve", "balancer", "uniswap_v2"],
      signalVariants: ["spread_capture"],
      rollMode: "n/a",
      notes: "Active LP (Uniswap V3/V4, Orca, Raydium) + Passive LP (Curve, Balancer, Uniswap V2).",
      blockListRefs: [],
      representativeSlotLabels: ["MARKET_MAKING_CONTINUOUS@uniswap-v3-weth-usdc-ethereum-active-usdc-prod", "MARKET_MAKING_CONTINUOUS@curve-3pool-ethereum-passive-usdc-prod"],
    },
    {
      archetype: "MARKET_MAKING_CONTINUOUS",
      category: "DEFI",
      instrumentType: "perp",
      status: "BLOCKED",
      representativeVenueIds: [],
      signalVariants: [],
      rollMode: "n/a",
      notes: "DeFi perp MM not exposed as third-party role.",
      blockListRefs: ["BL-7"],
      representativeSlotLabels: [],
    },
    {
      archetype: "MARKET_MAKING_CONTINUOUS",
      category: "DEFI",
      instrumentType: "option",
      status: "BLOCKED",
      representativeVenueIds: [],
      signalVariants: [],
      rollMode: "n/a",
      notes: "No supported DeFi options venue.",
      blockListRefs: ["BL-1"],
      representativeSlotLabels: [],
    },
    {
      archetype: "MARKET_MAKING_CONTINUOUS",
      category: "TRADFI",
      instrumentType: "spot",
      status: "PARTIAL",
      representativeVenueIds: ["ibkr"],
      signalVariants: ["spread_capture"],
      rollMode: "n/a",
      notes: "IBKR MM designation required; regulatory overhead.",
      blockListRefs: [],
      representativeSlotLabels: [],
    },
    {
      archetype: "MARKET_MAKING_CONTINUOUS",
      category: "TRADFI",
      instrumentType: "dated_future",
      status: "PARTIAL",
      representativeVenueIds: ["cme"],
      signalVariants: ["spread_capture"],
      rollMode: "rolling",
      notes: "Formal MM designation out-of-scope for initial rollout.",
      blockListRefs: [],
      representativeSlotLabels: [],
    },
    {
      archetype: "MARKET_MAKING_CONTINUOUS",
      category: "SPORTS",
      instrumentType: "event_settled",
      status: "PARTIAL",
      representativeVenueIds: ["betfair_direct", "unity"],
      signalVariants: ["odds", "spread_capture"],
      rollMode: "n/a",
      notes: "Bankroll-as-collateral lay semantics need explicit execution_policy_ref (UAC gap #9).",
      blockListRefs: [],
      representativeSlotLabels: ["MARKET_MAKING_CONTINUOUS@betfair-direct-epl-1x2-mm-gbp-prod"],
    },
  ],
};

const market_making_event_settled: ArchetypeCoverage = {
  archetype: "MARKET_MAKING_EVENT_SETTLED",
  usesRollingFutures: false,
  cells: [
    {
      archetype: "MARKET_MAKING_EVENT_SETTLED",
      category: "SPORTS",
      instrumentType: "event_settled",
      status: "SUPPORTED",
      representativeVenueIds: ["betfair_direct"],
      signalVariants: ["odds", "spread_capture"],
      rollMode: "n/a",
      notes: "Primary — lay-native.",
      blockListRefs: [],
      representativeSlotLabels: ["MARKET_MAKING_EVENT_SETTLED@betfair-direct-epl-1x2-mm-gbp-prod", "MARKET_MAKING_EVENT_SETTLED@betfair-direct-atp-match-winner-mm-gbp-prod"],
    },
    {
      archetype: "MARKET_MAKING_EVENT_SETTLED",
      category: "SPORTS",
      instrumentType: "event_settled",
      status: "PARTIAL",
      representativeVenueIds: ["smarkets_direct", "matchbook_direct", "betdaq_direct"],
      signalVariants: ["odds"],
      rollMode: "n/a",
      notes: "Lay semantics differ per venue; capability flag gap per-venue.",
      blockListRefs: [],
      representativeSlotLabels: ["MARKET_MAKING_EVENT_SETTLED@smarkets-direct-epl-1x2-mm-gbp-prod"],
    },
    {
      archetype: "MARKET_MAKING_EVENT_SETTLED",
      category: "SPORTS",
      instrumentType: "event_settled",
      status: "BLOCKED",
      representativeVenueIds: ["unity"],
      signalVariants: [],
      rollMode: "n/a",
      notes: "Unity Feed Connector is place-only, not quoting.",
      blockListRefs: ["BL-6"],
      representativeSlotLabels: [],
    },
    {
      archetype: "MARKET_MAKING_EVENT_SETTLED",
      category: "PREDICTION",
      instrumentType: "event_settled",
      status: "PARTIAL",
      representativeVenueIds: ["polymarket"],
      signalVariants: ["price"],
      rollMode: "n/a",
      notes: "Polymarket CLOB MM supported in theory but quoting UX differs (no 'lay').",
      blockListRefs: [],
      representativeSlotLabels: ["MARKET_MAKING_EVENT_SETTLED@polymarket-us-election-mm-usdc-prod"],
    },
    {
      archetype: "MARKET_MAKING_EVENT_SETTLED",
      category: "PREDICTION",
      instrumentType: "event_settled",
      status: "BLOCKED",
      representativeVenueIds: ["kalshi"],
      signalVariants: [],
      rollMode: "n/a",
      notes: "Kalshi execution adapter pending.",
      blockListRefs: ["BL-5"],
      representativeSlotLabels: [],
    },
  ],
};

const event_driven: ArchetypeCoverage = {
  archetype: "EVENT_DRIVEN",
  usesRollingFutures: true,
  cells: [
    {
      archetype: "EVENT_DRIVEN",
      category: "CEFI",
      instrumentType: "spot",
      status: "PARTIAL",
      representativeVenueIds: ["binance", "okx"],
      signalVariants: ["event_surprise"],
      rollMode: "n/a",
      notes: "External event calendar not declared in UAC (gap #5).",
      blockListRefs: [],
      representativeSlotLabels: ["EVENT_DRIVEN@binance-btc-usdt-nfp-usdt-prod"],
    },
    {
      archetype: "EVENT_DRIVEN",
      category: "CEFI",
      instrumentType: "perp",
      status: "PARTIAL",
      representativeVenueIds: ["binance", "hyperliquid", "bybit"],
      signalVariants: ["event_surprise"],
      rollMode: "n/a",
      notes: "Same calendar gap.",
      blockListRefs: [],
      representativeSlotLabels: ["EVENT_DRIVEN@binance-btc-perp-fomc-usdt-prod"],
    },
    {
      archetype: "EVENT_DRIVEN",
      category: "CEFI",
      instrumentType: "option",
      status: "PARTIAL",
      representativeVenueIds: ["deribit"],
      signalVariants: ["event_surprise", "iv_dispersion"],
      rollMode: "n/a",
      notes: "Event-straddle expression policy not declared.",
      blockListRefs: [],
      representativeSlotLabels: ["EVENT_DRIVEN@deribit-btc-option-fomc-straddle-usdt-prod"],
    },
    {
      archetype: "EVENT_DRIVEN",
      category: "DEFI",
      instrumentType: "spot",
      status: "PARTIAL",
      representativeVenueIds: ["uniswap_v3"],
      signalVariants: ["event_surprise"],
      rollMode: "n/a",
      notes: "Token unlock calendar source gap.",
      blockListRefs: [],
      representativeSlotLabels: ["EVENT_DRIVEN@uniswap-ethereum-arb-token-unlock-usdc-prod"],
    },
    {
      archetype: "EVENT_DRIVEN",
      category: "DEFI",
      instrumentType: "perp",
      status: "PARTIAL",
      representativeVenueIds: ["hyperliquid", "gmx_v2"],
      signalVariants: ["event_surprise"],
      rollMode: "n/a",
      notes: "Governance-vote reactive path; adapter ready.",
      blockListRefs: [],
      representativeSlotLabels: [],
    },
    {
      archetype: "EVENT_DRIVEN",
      category: "DEFI",
      instrumentType: "lending",
      status: "PARTIAL",
      representativeVenueIds: ["aave_v3"],
      signalVariants: ["event_surprise", "rate_spread"],
      rollMode: "n/a",
      notes: "Protocol-governance calendar gap.",
      blockListRefs: [],
      representativeSlotLabels: ["EVENT_DRIVEN@aave-ethereum-governance-rate-update-usdc-prod"],
    },
    {
      archetype: "EVENT_DRIVEN",
      category: "DEFI",
      instrumentType: "staking",
      status: "PARTIAL",
      representativeVenueIds: ["lido"],
      signalVariants: ["event_surprise"],
      rollMode: "n/a",
      notes: "Slashing feed integration incomplete.",
      blockListRefs: [],
      representativeSlotLabels: [],
    },
    {
      archetype: "EVENT_DRIVEN",
      category: "TRADFI",
      instrumentType: "spot",
      status: "PARTIAL",
      representativeVenueIds: ["ibkr"],
      signalVariants: ["event_surprise"],
      rollMode: "n/a",
      notes: "Earnings calendar source gap.",
      blockListRefs: [],
      representativeSlotLabels: ["EVENT_DRIVEN@ibkr-aapl-earnings-usd-prod"],
    },
    {
      archetype: "EVENT_DRIVEN",
      category: "TRADFI",
      instrumentType: "dated_future",
      status: "PARTIAL",
      representativeVenueIds: ["cme"],
      signalVariants: ["event_surprise"],
      rollMode: "rolling",
      notes: "Event-type → instrument mapping not declared in execution_policy.",
      blockListRefs: ["BL-10"],
      representativeSlotLabels: ["EVENT_DRIVEN@cme-es-dated-nfp-usd-prod"],
    },
    {
      archetype: "EVENT_DRIVEN",
      category: "TRADFI",
      instrumentType: "option",
      status: "PARTIAL",
      representativeVenueIds: ["cboe"],
      signalVariants: ["event_surprise", "iv_dispersion"],
      rollMode: "n/a",
      notes: "Same as CeFi option.",
      blockListRefs: [],
      representativeSlotLabels: ["EVENT_DRIVEN@cboe-vix-cpi-usd-prod"],
    },
    {
      archetype: "EVENT_DRIVEN",
      category: "SPORTS",
      instrumentType: "event_settled",
      status: "PARTIAL",
      representativeVenueIds: ["unity"],
      signalVariants: ["event_surprise"],
      rollMode: "n/a",
      notes: "News-feed + lineup timing model not declared.",
      blockListRefs: [],
      representativeSlotLabels: ["EVENT_DRIVEN@unity-epl-lineup-release-usd-prod"],
    },
    {
      archetype: "EVENT_DRIVEN",
      category: "PREDICTION",
      instrumentType: "event_settled",
      status: "PARTIAL",
      representativeVenueIds: ["polymarket"],
      signalVariants: ["event_surprise"],
      rollMode: "n/a",
      notes: "Same news-feed gap.",
      blockListRefs: [],
      representativeSlotLabels: ["EVENT_DRIVEN@polymarket-us-election-debate-usdc-prod"],
    },
  ],
};

const vol_trading_options: ArchetypeCoverage = {
  archetype: "VOL_TRADING_OPTIONS",
  usesRollingFutures: false,
  cells: [
    {
      archetype: "VOL_TRADING_OPTIONS",
      category: "CEFI",
      instrumentType: "option",
      status: "SUPPORTED",
      representativeVenueIds: ["deribit", "okx"],
      signalVariants: ["vol_metric", "iv_dispersion"],
      rollMode: "n/a",
      notes: "Full Deribit surface support; multi-leg ATOMIC supported.",
      blockListRefs: [],
      representativeSlotLabels: ["VOL_TRADING_OPTIONS@deribit-btc-vol-usdt-prod", "VOL_TRADING_OPTIONS@deribit-btc-skew-usdt-prod"],
    },
    {
      archetype: "VOL_TRADING_OPTIONS",
      category: "DEFI",
      instrumentType: "option",
      status: "BLOCKED",
      representativeVenueIds: [],
      signalVariants: [],
      rollMode: "n/a",
      notes: "No supported DeFi options venue (Lyra / Dopex archived).",
      blockListRefs: ["BL-1"],
      representativeSlotLabels: [],
    },
    {
      archetype: "VOL_TRADING_OPTIONS",
      category: "TRADFI",
      instrumentType: "option",
      status: "PARTIAL",
      representativeVenueIds: ["cboe"],
      signalVariants: ["vol_metric", "iv_dispersion"],
      rollMode: "n/a",
      notes: "CME options-on-futures not declared.",
      blockListRefs: [],
      representativeSlotLabels: ["VOL_TRADING_OPTIONS@ibkr-cboe-spy-vol-usd-prod"],
    },
  ],
};

const stat_arb_pairs_fixed: ArchetypeCoverage = {
  archetype: "STAT_ARB_PAIRS_FIXED",
  usesRollingFutures: true,
  cells: [
    {
      archetype: "STAT_ARB_PAIRS_FIXED",
      category: "CEFI",
      instrumentType: "spot",
      status: "SUPPORTED",
      representativeVenueIds: ["binance", "okx", "bybit"],
      signalVariants: ["zscore_reversion"],
      rollMode: "n/a",
      notes: "",
      blockListRefs: [],
      representativeSlotLabels: ["STAT_ARB_PAIRS_FIXED@binance-btc-eth-spot-usdt-prod"],
    },
    {
      archetype: "STAT_ARB_PAIRS_FIXED",
      category: "CEFI",
      instrumentType: "perp",
      status: "SUPPORTED",
      representativeVenueIds: ["binance", "okx", "bybit", "hyperliquid"],
      signalVariants: ["zscore_reversion"],
      rollMode: "n/a",
      notes: "",
      blockListRefs: [],
      representativeSlotLabels: ["STAT_ARB_PAIRS_FIXED@binance-btc-eth-perp-usdt-prod"],
    },
    {
      archetype: "STAT_ARB_PAIRS_FIXED",
      category: "DEFI",
      instrumentType: "spot",
      status: "PARTIAL",
      representativeVenueIds: ["uniswap_v3"],
      signalVariants: ["zscore_reversion"],
      rollMode: "n/a",
      notes: "Price-feed liquidity concerns on thinner pairs.",
      blockListRefs: [],
      representativeSlotLabels: ["STAT_ARB_PAIRS_FIXED@uniswap-ethereum-eth-wbtc-usdc-prod"],
    },
    {
      archetype: "STAT_ARB_PAIRS_FIXED",
      category: "DEFI",
      instrumentType: "perp",
      status: "PARTIAL",
      representativeVenueIds: ["hyperliquid", "gmx_v2", "drift"],
      signalVariants: ["zscore_reversion"],
      rollMode: "n/a",
      notes: "",
      blockListRefs: [],
      representativeSlotLabels: ["STAT_ARB_PAIRS_FIXED@hyperliquid-sol-eth-perp-usdc-prod"],
    },
    {
      archetype: "STAT_ARB_PAIRS_FIXED",
      category: "TRADFI",
      instrumentType: "spot",
      status: "PARTIAL",
      representativeVenueIds: ["ibkr"],
      signalVariants: ["zscore_reversion"],
      rollMode: "n/a",
      notes: "Pair pre-declaration config path fine; no batch-tested instances.",
      blockListRefs: [],
      representativeSlotLabels: ["STAT_ARB_PAIRS_FIXED@ibkr-goog-meta-daily-usd-prod", "STAT_ARB_PAIRS_FIXED@ibkr-aapl-msft-1h-usd-prod"],
    },
    {
      archetype: "STAT_ARB_PAIRS_FIXED",
      category: "TRADFI",
      instrumentType: "dated_future",
      status: "PARTIAL",
      representativeVenueIds: ["cme", "ice"],
      signalVariants: ["zscore_reversion"],
      rollMode: "rolling",
      notes: "Calendar / cross-product pairs; roll service required (BL-10).",
      blockListRefs: ["BL-10"],
      representativeSlotLabels: ["STAT_ARB_PAIRS_FIXED@cme-es-nq-dated-zscore-usd-prod", "STAT_ARB_PAIRS_FIXED@ice-brent-cme-wti-dated-usd-prod"],
    },
  ],
};

const stat_arb_cross_sectional: ArchetypeCoverage = {
  archetype: "STAT_ARB_CROSS_SECTIONAL",
  usesRollingFutures: true,
  cells: [
    {
      archetype: "STAT_ARB_CROSS_SECTIONAL",
      category: "CEFI",
      instrumentType: "spot",
      status: "PARTIAL",
      representativeVenueIds: ["binance"],
      signalVariants: ["momentum_ranking"],
      rollMode: "n/a",
      notes: "Basket execution via sequential TRADE; batch-order path not tested.",
      blockListRefs: [],
      representativeSlotLabels: ["STAT_ARB_CROSS_SECTIONAL@binance-alt-basket-momentum-usdt-prod"],
    },
    {
      archetype: "STAT_ARB_CROSS_SECTIONAL",
      category: "CEFI",
      instrumentType: "perp",
      status: "PARTIAL",
      representativeVenueIds: ["hyperliquid", "bybit"],
      signalVariants: ["momentum_ranking"],
      rollMode: "n/a",
      notes: "",
      blockListRefs: [],
      representativeSlotLabels: ["STAT_ARB_CROSS_SECTIONAL@hyperliquid-alt-perp-momentum-usdt-prod"],
    },
    {
      archetype: "STAT_ARB_CROSS_SECTIONAL",
      category: "DEFI",
      instrumentType: "spot",
      status: "BLOCKED",
      representativeVenueIds: [],
      signalVariants: [],
      rollMode: "n/a",
      notes: "Multi-token atomic basket trade on DeFi is gas-prohibitive; needs specialised router.",
      blockListRefs: ["BL-8"],
      representativeSlotLabels: [],
    },
    {
      archetype: "STAT_ARB_CROSS_SECTIONAL",
      category: "DEFI",
      instrumentType: "perp",
      status: "PARTIAL",
      representativeVenueIds: ["hyperliquid", "gmx_v2", "drift"],
      signalVariants: ["momentum_ranking"],
      rollMode: "n/a",
      notes: "",
      blockListRefs: [],
      representativeSlotLabels: ["STAT_ARB_CROSS_SECTIONAL@hyperliquid-dex-alt-perp-momentum-usdc-prod"],
    },
    {
      archetype: "STAT_ARB_CROSS_SECTIONAL",
      category: "TRADFI",
      instrumentType: "spot",
      status: "PARTIAL",
      representativeVenueIds: ["ibkr"],
      signalVariants: ["momentum_ranking"],
      rollMode: "n/a",
      notes: "Batch-order capability not declared for IBKR; basket of 50–500 legs.",
      blockListRefs: [],
      representativeSlotLabels: ["STAT_ARB_CROSS_SECTIONAL@ibkr-sp500-momentum-usd-prod", "STAT_ARB_CROSS_SECTIONAL@ibkr-sp500-sector-rotation-usd-prod"],
    },
    {
      archetype: "STAT_ARB_CROSS_SECTIONAL",
      category: "TRADFI",
      instrumentType: "dated_future",
      status: "BLOCKED",
      representativeVenueIds: [],
      signalVariants: [],
      rollMode: "n/a",
      notes: "Cross-sectional basket on CME requires multi-leg order capability not declared.",
      blockListRefs: ["BL-9"],
      representativeSlotLabels: [],
    },
  ],
};

export const ARCHETYPE_COVERAGE: Readonly<Record<StrategyArchetype, ArchetypeCoverage>> = {
  ML_DIRECTIONAL_CONTINUOUS: ml_directional_continuous,
  ML_DIRECTIONAL_EVENT_SETTLED: ml_directional_event_settled,
  RULES_DIRECTIONAL_CONTINUOUS: rules_directional_continuous,
  RULES_DIRECTIONAL_EVENT_SETTLED: rules_directional_event_settled,
  CARRY_BASIS_DATED: carry_basis_dated,
  CARRY_BASIS_PERP: carry_basis_perp,
  CARRY_STAKED_BASIS: carry_staked_basis,
  CARRY_RECURSIVE_STAKED: carry_recursive_staked,
  YIELD_ROTATION_LENDING: yield_rotation_lending,
  YIELD_STAKING_SIMPLE: yield_staking_simple,
  ARBITRAGE_PRICE_DISPERSION: arbitrage_price_dispersion,
  LIQUIDATION_CAPTURE: liquidation_capture,
  MARKET_MAKING_CONTINUOUS: market_making_continuous,
  MARKET_MAKING_EVENT_SETTLED: market_making_event_settled,
  EVENT_DRIVEN: event_driven,
  VOL_TRADING_OPTIONS: vol_trading_options,
  STAT_ARB_PAIRS_FIXED: stat_arb_pairs_fixed,
  STAT_ARB_CROSS_SECTIONAL: stat_arb_cross_sectional,
};

export function allCoverageCells(): readonly CoverageCell[] {
  const out: CoverageCell[] = [];
  for (const archetype of Object.keys(ARCHETYPE_COVERAGE) as StrategyArchetype[]) {
    out.push(...ARCHETYPE_COVERAGE[archetype].cells);
  }
  return out;
}

export function coverageForArchetype(archetype: StrategyArchetype): ArchetypeCoverage {
  return ARCHETYPE_COVERAGE[archetype];
}

export function cellsMatching(predicate: (cell: CoverageCell) => boolean): readonly CoverageCell[] {
  return allCoverageCells().filter(predicate);
}

export function cellsForInstrumentPair(
  legAType: InstrumentTypeV2,
  legBType: InstrumentTypeV2,
): readonly CoverageCell[] {
  return cellsMatching(
    (c) =>
      c.status !== "NOT_APPLICABLE" &&
      (c.instrumentType === legAType || c.instrumentType === legBType) &&
      (c.archetype === "ARBITRAGE_PRICE_DISPERSION" ||
        c.archetype === "CARRY_BASIS_PERP" ||
        c.archetype === "CARRY_BASIS_DATED" ||
        c.archetype === "STAT_ARB_PAIRS_FIXED" ||
        c.archetype === "STAT_ARB_CROSS_SECTIONAL" ||
        c.archetype === "CARRY_STAKED_BASIS"),
  );
}

export function blockedCells(): readonly CoverageCell[] {
  return cellsMatching((c) => c.status === "BLOCKED");
}

export function supportedCells(): readonly CoverageCell[] {
  return cellsMatching((c) => c.status === "SUPPORTED");
}

export function rollingFutureCells(): readonly CoverageCell[] {
  return cellsMatching((c) => c.rollMode === "rolling" || c.rollMode === "both");
}
