"""Unified internal contracts — schemas for internal service-to-service messaging.

NO cloud SDKs (google-cloud-*, boto3, redis). Pure Pydantic schemas only.
"""

from unified_api_contracts.internal.alerting import AlertEvent
from unified_api_contracts.internal.connectivity import (
    WebSocketConnectEvent,
    WebSocketDisconnectEvent,
    WebSocketErrorEvent,
    WebSocketPingEvent,
    WebSocketPongEvent,
    WebSocketReconnectEvent,
    WebSocketSubscribeAckEvent,
)
from unified_api_contracts.internal.deployment import (
    VM_INFRASTRUCTURE_EVENTS,
    ComputeType,
    DeploymentState,
    DeploymentStatus,
    ShardEvent,
    VMEventType,
)
from unified_api_contracts.internal.domain.analytics import (
    CorrelationRegime as CorrelationRegime,
)
from unified_api_contracts.internal.domain.analytics import (
    CorrelationRegimeChange as CorrelationRegimeChange,
)
from unified_api_contracts.internal.domain.analytics import (
    CrossAssetCorrelationMatrix as CrossAssetCorrelationMatrix,
)
from unified_api_contracts.internal.domain.analytics import (
    FactorAttributionModel as FactorAttributionModel,
)
from unified_api_contracts.internal.domain.analytics import (
    FactorAttributionRecord as FactorAttributionRecord,
)
from unified_api_contracts.internal.domain.analytics import (
    FactorExposure as FactorExposure,
)
from unified_api_contracts.internal.domain.analytics import (
    FactorType as FactorType,
)
from unified_api_contracts.internal.domain.cefi_accounts.schemas import (
    DepositAddress,
    DepositRecord,
    ExchangeFeeSchedule,
    InternalTransfer,
    PortfolioMarginAccount,
    SubAccount,
    WithdrawalRecord,
)
from unified_api_contracts.internal.domain.data_quality.venue_freshness_slas import (
    VenueCategory,
    VenueFreshnessSLA,
)
from unified_api_contracts.internal.domain.defi import (
    AaveBorrowParams as AaveBorrowParams,
)
from unified_api_contracts.internal.domain.defi import (
    AaveDepositParams,
    AaveFlashLoanParams,
    AaveRepayParams,
    AaveV3ReserveData,
    AaveV3UserAccountData,
    AaveV3UserReserveData,
    CompoundV3MarketInfo,
    CompoundV3UserPosition,
    CurveSwapParams,
    CurveWithdrawParams,
    Erc20TransferFromCalldata,
    EtherFiStakeResponse,
    EtherFiUnstakeResponse,
    EthSendRawTransactionResponse,
    EthSendTransactionRequest,
    EthTransactionRequest,
    EulerBorrowParams,
    EulerDepositParams,
    EulerRepayParams,
    EulerUserPosition,
    EulerVaultData,
    FluidBorrowParams,
    FluidDepositParams,
    FluidRepayParams,
    GasCostAction,
    GasCostEstimate,
    LendingRate,
    LidoRequestWithdrawalsParams,
    LidoSubmitParams,
    LidoSubmitResponse,
    LidoWstEthWrapResponse,
    LiquidityPool,
    MorphoBorrowParams,
    MorphoFlashLoanParams,
    MorphoMarketParams,
    MorphoRepayParams,
    MorphoSupplyParams,
    MorphoUserPosition,
    OraclePrice,
    StakingRate,
    UniswapV3PoolStateResponse,
    UniswapV3QuoteResponse,
    UniswapV3SwapTxReceipt,
)
from unified_api_contracts.internal.domain.defi import (
    CurveDepositParams as CurveDepositParams,
)
from unified_api_contracts.internal.domain.defi import (
    Erc20TransferCalldata as Erc20TransferCalldata,
)
from unified_api_contracts.internal.domain.defi import (
    EthSendRawTransactionRequest as EthSendRawTransactionRequest,
)
from unified_api_contracts.internal.domain.derivatives.options import (
    OptionContract,
    OptionGreeks,
    OptionsChain,
    SettlementPrice,
)
from unified_api_contracts.internal.domain.events_service.lifecycle import (
    RestartDetectedDetails,
    RestartDetectedEvent,
)
from unified_api_contracts.internal.domain.execution_service.cex_withdrawals import (
    BinanceWithdrawRequest,
    BinanceWithdrawResponse,
    BybitWithdrawRequest,
    BybitWithdrawResponse,
    CoinbaseWithdrawRequest,
    CoinbaseWithdrawResponse,
    OKXWithdrawRequest,
    OKXWithdrawResponse,
    UpbitWithdrawRequest,
    UpbitWithdrawResponse,
)
from unified_api_contracts.internal.domain.execution_service.execution_preferences import (
    ExecutionMode,
    ExecutionPreferencesConfig,
    UrgencyLevel,
)
from unified_api_contracts.internal.domain.execution_service.multi_leg import (
    LegExecutionResult,
    LegInstruction,
    LegStatus,
    MultiLegExecutionMode,
    MultiLegExecutionResult,
    MultiLegInstruction,
)
from unified_api_contracts.internal.domain.execution_service.sports import (
    SportsBetResult,
    SportsVenueScore,
    SportsVenueSelection,
)
from unified_api_contracts.internal.domain.features_commodity import (
    CommodityFeatureRequest as CommodityFeatureRequest,
)
from unified_api_contracts.internal.domain.features_commodity import (
    CommoditySignal as CommoditySignal,
)
from unified_api_contracts.internal.domain.features_commodity import (
    FactorValue as FactorValue,
)
from unified_api_contracts.internal.domain.features_commodity import (
    RegimeState as RegimeState,
)
from unified_api_contracts.internal.domain.features_delta_one import (
    FEATURES_SCHEMA,
    validate_feature_columns_not_null,
)
from unified_api_contracts.internal.domain.health.service_health import ServiceHealthResponse
from unified_api_contracts.internal.domain.market_data_api import OrderBookSnapshot
from unified_api_contracts.internal.domain.market_data_processing.adapter_models import (
    CandleOutput,
    InstrumentInfo,
    InstrumentMetadata,
)
from unified_api_contracts.internal.domain.market_data_processing.candle_schema import (
    DataType,
    MarketState,
)
from unified_api_contracts.internal.domain.market_tick_data import (
    SportsBookUpdate,
    SportsOddsTick,
)
from unified_api_contracts.internal.domain.matching_engine import (
    BookType as BookType,
)
from unified_api_contracts.internal.domain.matching_engine import (
    FeeResult as FeeResult,
)
from unified_api_contracts.internal.domain.matching_engine import (
    MatchingFeeType as MatchingFeeType,
)
from unified_api_contracts.internal.domain.matching_engine import (
    MatchResult as MatchResult,
)
from unified_api_contracts.internal.domain.matching_engine import (
    OrderRecord as OrderRecord,
)
from unified_api_contracts.internal.domain.matching_engine import (
    OrderType as OrderType,
)
from unified_api_contracts.internal.domain.matching_engine import (
    SwapResult,
)
from unified_api_contracts.internal.domain.ml_inference_service import (
    CascadeConfig,
    CascadePredictionEvent,
    PredictionSnapshot,
)
from unified_api_contracts.internal.domain.prediction_market.prediction_market_arb import (
    BucketMarket,
    CrossVenueArbLeg,
    CrossVenueArbSignal,
    CrossVenueLink,
    PredictionMarketUniverse,
    PredictionMarketUseCase,
    ProbabilityBucket,
    SportsbookLink,
)
from unified_api_contracts.internal.domain.risk_service.risk import (
    MultiAssetMarginCalculation,
    SpanMarginLeg,
)
from unified_api_contracts.internal.domain.sports.execution import (
    BetCancelledEvent,
    BetFilledEvent,
    BetPlacedEvent,
    BetSettledEvent,
    CanonicalSportsFill,
    CanonicalSportsOrder,
    SportsBetEvent,
)
from unified_api_contracts.internal.domain.strategy_service.domain_events import (
    ExposureSnapshot,
    OrderEvent,
    PnLCalculation,
    PositionSnapshot,
    RiskAssessment,
    StrategyDecision,
)
from unified_api_contracts.internal.domain.strategy_service.monitoring import (
    ExposureData,
    OrderData,
    PnLData,
    PositionData,
    RiskData,
    StrategyDecisionData,
)
from unified_api_contracts.internal.domain.strategy_service.order import Order
from unified_api_contracts.internal.domain.strategy_service.signal_vector import (
    MetaSignalRecord,
    RegimeStateRecord,
    SignalVectorRecord,
)
from unified_api_contracts.internal.domain.strategy_service.trigger_subscription import (
    TriggerEvent,
    TriggerEventType,
    TriggerSubscription,
)
from unified_api_contracts.internal.domain.websocket.lifecycle import (
    HealthPingResponse,
    UnsubscribeRequest,
    WebSocketConnectionClosed,
    WebSocketConnectionOpened,
)
from unified_api_contracts.internal.env_canon import EnvVars
from unified_api_contracts.internal.events import (
    AgentEventDetails,
    AuthFailureDetails,
    AuthFailureEvent,
    CascadeDispatchDetails,
    CategorizedErrorDetails,
    ConfigChangedDetails,
    ConfigChangedEvent,
    DataBroadcastDetails,
    DataIngestionCompletedDetails,
    DataIngestionDetails,
    DeploymentDetails,
    EventMetadata,
    EventSeverity,
    FailedDetails,
    FailedEvent,
    LifecycleEventEnvelope,
    LifecycleEventType,
    PersistenceCompletedDetails,
    PersistenceStartedDetails,
    ProcessingCompletedDetails,
    ProcessingStartedDetails,
    PubSubLifecycleEventMessage,
    QualityGateDetails,
    ResourceMetricsSnapshot,
    SecretAccessedDetails,
    SecretAccessedEvent,
    ServiceMode,
    StartedDetails,
    StartedEvent,
    StoppedDetails,
    ValidationCompletedDetails,
    ValidationStartedDetails,
    VersionBumpDetails,
)
from unified_api_contracts.internal.execution import ManualInstruction, SettlementType
from unified_api_contracts.internal.features import (
    CrossInstrumentFeatures,
    CrossTimeframeFeatures,
    DeltaOneFeatureRecord,
    FeatureSnapshotRequest,
    FuturesTermStructureRecord,
    LiquidationBandEntry,
    LiquidationBandPredictionSnapshot,
    OnchainFeatureRecord,
    OptionsIvRecord,
    PairSpreadFeatureRecord,
    VolSurfaceTermStructureRecord,
)
from unified_api_contracts.internal.market_category import MarketCategory
from unified_api_contracts.internal.market_data import (
    BookUpdateLevel,
    CanonicalBondData,
    CanonicalBookUpdate,
    CanonicalLendingRate,
    CanonicalLiquidation,
    CanonicalLiquidityPool,
    CanonicalOHLCV,
    CanonicalOptionQuote,
    CanonicalOraclePrice,
    CanonicalOrderBook,
    CanonicalStakingRate,
    CanonicalSwap,
    CanonicalTicker,
    CanonicalTrade,
    CanonicalYieldCurve,
    InternalOptionsChainSnapshot,
    OHLCVSource,
    YieldCurveTenor,
)
from unified_api_contracts.internal.messaging import MessagingScope, MessagingTopic
from unified_api_contracts.internal.ml import (
    CrossValidationResult,
    HyperparameterConfig,
    InferenceRequest,
    InferenceResult,
    MLConfigDict,
    ModelDegradationAlert,
    ModelMetadata,
    ModelType,
    ModelVariantConfig,
    TargetType,
    TrainingJobRequest,
    TrainingJobResult,
    TrainingPeriod,
)
from unified_api_contracts.internal.modes import (
    CloudProvider,
    DataMode,
    LogLevel,
    MockScenario,
    PhaseMode,
    RuntimeMode,
    TestingStage,
    TestingStageConfig,
)
from unified_api_contracts.internal.position_protocol import (
    CrossAssetPortfolioAggregator,
    PositionQuantityProtocol,
)
from unified_api_contracts.internal.position_types import (
    aggregate_notional,
    aggregate_positions,
)
from unified_api_contracts.internal.positions import (
    CeFiPosition,
    DeFiLendingPosition,
    DeFiLPPosition,
    DeFiStakingPosition,
    LendingEntry,
)
from unified_api_contracts.internal.pubsub import (
    AggregatedPositionMessage,
    CircuitBreakerEventMessage,
    DerivativeTickerMessage,
    ExecutionResultMessage,
    FeatureUpdateMessage,
    FillEventMessage,
    HealthAlertMessage,
    InternalPubSubTopic,
    LiquidationMessage,
    MarketTickMessage,
    MLPredictionMessage,
    OrderRequestMessage,
    PositionUpdateMessage,
    PubSubMessageEnvelope,
    RiskAlertMessage,
    ServiceLifecycleEventMessage,
    StrategySignalMessage,
    VenuePositionBreakdownMessage,
)
from unified_api_contracts.internal.reference import (
    ALL_FRESHNESS_CONTRACTS,
    FEATURE_FRESHNESS,
    MARKET_TICK_FRESHNESS,
    ML_FRESHNESS,
    AssetClass,
    CircuitBreakerConfigRegistry,
    ClientFeeSchedule,
    ClientPrimeBrokerLink,
    DataFreshnessContract,
    DataSourceConstraint,
    DataStalenessError,
    FeeScheduleEntry,
    FeeType,
    InstrumentDefinition,
    InstrumentKey,
    InstrumentRecord,
    InstrumentStatus,
    InstrumentType,
    MarginType,
    OnchainDataFreshnessConfig,
    OptionType,
    PrimeBrokerEntity,
    UniverseSnapshot,
    VenueCircuitBreakerConfig,
)
from unified_api_contracts.internal.reporting import ClientConfig, CredentialsRegistry, FeeStructure
from unified_api_contracts.internal.risk import (
    AccountState,
    AlertContextData,
    AlertMessage,
    AlertType,
    Balance,
    CircuitBreakerEvent,
    ClientRiskTolerance,
    CorrelationEntry,
    CustomRiskEvaluationMethod,
    CustomRiskTypeDefinition,
    DurationBucket,
    EmergencyExitPlaybook,
    EmergencyExitStep,
    EmergencyExitType,
    EODSettlementTrigger,
    ExposureSummary,
    ExtendedPnLAttribution,
    GreeksExposure,
    InternalPosition,
    KillSwitchScope,
    LimitCheckResult,
    MarginHealthSnapshot,
    MarginState,
    PnLAttributionRecord,
    PnLBreakdown,
    PositionSide,
    PreTradeCheckRequest,
    PreTradeCheckResponse,
    RealTimePnLRecord,
    RiskAggregationLevel,
    RiskMetrics,
    RiskPnLNode,
    RiskPosition,
    RiskStatus,
    ScopedKillSwitchState,
    StrategyRiskProfile,
    StressScenario,
    StressScenarioType,
    StressTestResult,
    TermStructureExposure,
    VaRMethod,
    VaRRequest,
    VaRResult,
)
from unified_api_contracts.internal.schema_definition import (
    ColumnSchema,
    SchemaDefinition,
    SchemaValidationError,
    SchemaValidationResult,
)
from unified_api_contracts.internal.schemas import (
    DeadLetterRecord,
    EnhancedError,
    ErrorCategory,
    ErrorContext,
    ErrorRecoveryStrategy,
    ErrorSeverity,
)
from unified_api_contracts.internal.schemas.audit import (
    EXECUTION_AUDIT,
    STRATEGY_AUDIT,
    AuditRequirement,
    AuditRetention,
)
from unified_api_contracts.internal.schemas.rbac import (
    Permission,
    UserProfile,
    UserRole,
)
from unified_api_contracts.internal.sports import (
    CoachRecord,
    FixtureEventsRecord,
    FixtureLineupsRecord,
    FixturePlayerStatsRecord,
    FixtureRecord,
    FixtureStatsRecord,
    InjuryRecord,
    LeagueRecord,
    PlayerRecord,
    RefereeRecord,
    RoundRecord,
    StandingsRecord,
    TeamRecord,
    VenueRecord,
)
from unified_api_contracts.internal.testing.scenario_config import (
    FaultConfig,
    ScenarioConfig,
)
from unified_api_contracts.internal.testing.seed_validator import (
    FileReport,
    ValidationReport,
)
from unified_api_contracts.internal.testing.synthetic import (
    SeedDataWriter,
    SyntheticDataGenerator,
)
from unified_api_contracts.internal.testing.tick_replay import TickReplayEngine
from unified_api_contracts.internal.timeframes import TIMEFRAME_TO_SECONDS, Timeframe

__all__ = [
    "ALL_FRESHNESS_CONTRACTS",
    "EXECUTION_AUDIT",
    "FEATURES_SCHEMA",
    "FEATURE_FRESHNESS",
    "MARKET_TICK_FRESHNESS",
    "ML_FRESHNESS",
    "STRATEGY_AUDIT",
    "TIMEFRAME_TO_SECONDS",
    "VM_INFRASTRUCTURE_EVENTS",
    "AaveBorrowParams",
    "AaveDepositParams",
    "AaveFlashLoanParams",
    "AaveRepayParams",
    "AaveV3ReserveData",
    "AaveV3UserAccountData",
    "AaveV3UserReserveData",
    "AccountState",
    "AgentEventDetails",
    "AggregatedPositionMessage",
    "AlertContextData",
    "AlertEvent",
    "AlertMessage",
    "AlertType",
    "AssetClass",
    "AuditRequirement",
    "AuditRetention",
    "AuthFailureDetails",
    "AuthFailureEvent",
    "Balance",
    "BetCancelledEvent",
    "BetFilledEvent",
    "BetPlacedEvent",
    "BetSettledEvent",
    "BinanceWithdrawRequest",
    "BinanceWithdrawResponse",
    "BookUpdateLevel",
    "BucketMarket",
    "BybitWithdrawRequest",
    "BybitWithdrawResponse",
    "CandleOutput",
    "CanonicalBondData",
    "CanonicalBookUpdate",
    "CanonicalLendingRate",
    "CanonicalLiquidation",
    "CanonicalLiquidityPool",
    "CanonicalOHLCV",
    "CanonicalOptionQuote",
    "CanonicalOraclePrice",
    "CanonicalOrderBook",
    "CanonicalSportsFill",
    "CanonicalSportsOrder",
    "CanonicalStakingRate",
    "CanonicalSwap",
    "CanonicalTicker",
    "CanonicalTrade",
    "CanonicalYieldCurve",
    "CascadeConfig",
    "CascadeDispatchDetails",
    "CascadePredictionEvent",
    "CategorizedErrorDetails",
    "CeFiPosition",
    "CircuitBreakerConfigRegistry",
    "CircuitBreakerEvent",
    "CircuitBreakerEventMessage",
    "ClientConfig",
    "ClientFeeSchedule",
    "ClientPrimeBrokerLink",
    "ClientRiskTolerance",
    "CloudProvider",
    "CoachRecord",
    "CoinbaseWithdrawRequest",
    "CoinbaseWithdrawResponse",
    "ColumnSchema",
    "CommodityFeatureRequest",
    "CommoditySignal",
    "CompoundV3MarketInfo",
    "CompoundV3UserPosition",
    "ComputeType",
    "ConfigChangedDetails",
    "ConfigChangedEvent",
    "CorrelationEntry",
    "CorrelationRegime",
    "CorrelationRegimeChange",
    "CredentialsRegistry",
    "CrossAssetCorrelationMatrix",
    "CrossAssetPortfolioAggregator",
    "CrossInstrumentFeatures",
    "CrossTimeframeFeatures",
    "CrossValidationResult",
    "CrossVenueArbLeg",
    "CrossVenueArbSignal",
    "CrossVenueLink",
    "CurveDepositParams",
    "CurveSwapParams",
    "CurveWithdrawParams",
    "CustomRiskEvaluationMethod",
    "CustomRiskTypeDefinition",
    "DataBroadcastDetails",
    "DataFreshnessContract",
    "DataIngestionCompletedDetails",
    "DataIngestionDetails",
    "DataMode",
    "DataSourceConstraint",
    "DataStalenessError",
    "DataType",
    "DeFiLPPosition",
    "DeFiLendingPosition",
    "DeFiStakingPosition",
    "DeadLetterRecord",
    "DeltaOneFeatureRecord",
    "DeploymentDetails",
    "DeploymentState",
    "DeploymentStatus",
    "DepositAddress",
    "DepositRecord",
    "DerivativeTickerMessage",
    "DurationBucket",
    "EODSettlementTrigger",
    "EmergencyExitPlaybook",
    "EmergencyExitStep",
    "EmergencyExitType",
    "EnhancedError",
    "EnvVars",
    "Erc20TransferCalldata",
    "Erc20TransferFromCalldata",
    "ErrorCategory",
    "ErrorContext",
    "ErrorRecoveryStrategy",
    "ErrorSeverity",
    "EthSendRawTransactionRequest",
    "EthSendRawTransactionResponse",
    "EthSendTransactionRequest",
    "EthTransactionRequest",
    "EtherFiStakeResponse",
    "EtherFiUnstakeResponse",
    "EulerBorrowParams",
    "EulerDepositParams",
    "EulerRepayParams",
    "EulerUserPosition",
    "EulerVaultData",
    "EventMetadata",
    "EventSeverity",
    "ExchangeFeeSchedule",
    "ExecutionMode",
    "ExecutionPreferencesConfig",
    "ExecutionResultMessage",
    "ExposureData",
    "ExposureSnapshot",
    "ExposureSummary",
    "ExtendedPnLAttribution",
    "FactorAttributionModel",
    "FactorAttributionRecord",
    "FactorExposure",
    "FactorType",
    "FactorValue",
    "FailedDetails",
    "FailedEvent",
    "FaultConfig",
    "FeatureSnapshotRequest",
    "FeatureUpdateMessage",
    "FeeScheduleEntry",
    "FeeStructure",
    "FeeType",
    "FileReport",
    "FillEventMessage",
    "FixtureEventsRecord",
    "FixtureLineupsRecord",
    "FixturePlayerStatsRecord",
    "FixtureRecord",
    "FixtureStatsRecord",
    "FluidBorrowParams",
    "FluidDepositParams",
    "FluidRepayParams",
    "FuturesTermStructureRecord",
    "GasCostAction",
    "GasCostEstimate",
    "GreeksExposure",
    "HealthAlertMessage",
    "HealthPingResponse",
    "HyperparameterConfig",
    "InferenceRequest",
    "InferenceResult",
    "InjuryRecord",
    "InstrumentDefinition",
    "InstrumentInfo",
    "InstrumentKey",
    "InstrumentMetadata",
    "InstrumentRecord",
    "InstrumentStatus",
    "InstrumentType",
    "InternalOptionsChainSnapshot",
    "InternalPosition",
    "InternalPubSubTopic",
    "InternalTransfer",
    "KillSwitchScope",
    "LeagueRecord",
    "LegExecutionResult",
    "LegInstruction",
    "LegStatus",
    "LendingEntry",
    "LendingRate",
    "LidoRequestWithdrawalsParams",
    "LidoSubmitParams",
    "LidoSubmitResponse",
    "LidoWstEthWrapResponse",
    "LifecycleEventEnvelope",
    "LifecycleEventType",
    "LimitCheckResult",
    "LiquidationBandEntry",
    "LiquidationBandPredictionSnapshot",
    "LiquidationMessage",
    "LiquidityPool",
    "LogLevel",
    "MLConfigDict",
    "MLPredictionMessage",
    "ManualInstruction",
    "MarginHealthSnapshot",
    "MarginState",
    "MarginType",
    "MarketCategory",
    "MarketState",
    "MarketTickMessage",
    "MessagingScope",
    "MessagingTopic",
    "MetaSignalRecord",
    "MockScenario",
    "ModelDegradationAlert",
    "ModelMetadata",
    "ModelType",
    "ModelVariantConfig",
    "MorphoBorrowParams",
    "MorphoFlashLoanParams",
    "MorphoMarketParams",
    "MorphoRepayParams",
    "MorphoSupplyParams",
    "MorphoUserPosition",
    "MultiAssetMarginCalculation",
    "MultiLegExecutionMode",
    "MultiLegExecutionResult",
    "MultiLegInstruction",
    "OHLCVSource",
    "OKXWithdrawRequest",
    "OKXWithdrawResponse",
    "OnchainDataFreshnessConfig",
    "OnchainFeatureRecord",
    "OptionContract",
    "OptionGreeks",
    "OptionType",
    "OptionsChain",
    "OptionsIvRecord",
    "OraclePrice",
    "Order",
    "OrderBookSnapshot",
    "OrderData",
    "OrderEvent",
    "OrderRequestMessage",
    "PairSpreadFeatureRecord",
    "Permission",
    "PersistenceCompletedDetails",
    "PersistenceStartedDetails",
    "PhaseMode",
    "PlayerRecord",
    "PnLAttributionRecord",
    "PnLBreakdown",
    "PnLCalculation",
    "PnLData",
    "PortfolioMarginAccount",
    "PositionData",
    "PositionQuantityProtocol",
    "PositionSide",
    "PositionSnapshot",
    "PositionUpdateMessage",
    "PreTradeCheckRequest",
    "PreTradeCheckResponse",
    "PredictionMarketUniverse",
    "PredictionMarketUseCase",
    "PredictionSnapshot",
    "PrimeBrokerEntity",
    "ProbabilityBucket",
    "ProcessingCompletedDetails",
    "ProcessingStartedDetails",
    "PubSubLifecycleEventMessage",
    "PubSubMessageEnvelope",
    "QualityGateDetails",
    "RealTimePnLRecord",
    "RefereeRecord",
    "RegimeState",
    "RegimeStateRecord",
    "ResourceMetricsSnapshot",
    "RestartDetectedDetails",
    "RestartDetectedEvent",
    "RiskAggregationLevel",
    "RiskAlertMessage",
    "RiskAssessment",
    "RiskData",
    "RiskMetrics",
    "RiskPnLNode",
    "RiskPosition",
    "RiskStatus",
    "RoundRecord",
    "RuntimeMode",
    "ScenarioConfig",
    "SchemaDefinition",
    "SchemaValidationError",
    "SchemaValidationResult",
    "ScopedKillSwitchState",
    "SecretAccessedDetails",
    "SecretAccessedEvent",
    "SeedDataWriter",
    "ServiceHealthResponse",
    "ServiceLifecycleEventMessage",
    "ServiceMode",
    "SettlementPrice",
    "SettlementType",
    "ShardEvent",
    "SignalVectorRecord",
    "SpanMarginLeg",
    "SportsBetEvent",
    "SportsBetResult",
    "SportsBookUpdate",
    "SportsOddsTick",
    "SportsVenueScore",
    "SportsVenueSelection",
    "SportsbookLink",
    "StakingRate",
    "StandingsRecord",
    "StartedDetails",
    "StartedEvent",
    "StoppedDetails",
    "StrategyDecision",
    "StrategyDecisionData",
    "StrategyRiskProfile",
    "StrategySignalMessage",
    "StressScenario",
    "StressScenarioType",
    "StressTestResult",
    "SubAccount",
    "SwapResult",
    "SyntheticDataGenerator",
    "TargetType",
    "TeamRecord",
    "TermStructureExposure",
    "TestingStage",
    "TestingStageConfig",
    "TickReplayEngine",
    "Timeframe",
    "TrainingJobRequest",
    "TrainingJobResult",
    "TrainingPeriod",
    "TriggerEvent",
    "TriggerEventType",
    "TriggerSubscription",
    "UniswapV3PoolStateResponse",
    "UniswapV3QuoteResponse",
    "UniswapV3SwapTxReceipt",
    "UniverseSnapshot",
    "UnsubscribeRequest",
    "UpbitWithdrawRequest",
    "UpbitWithdrawResponse",
    "UrgencyLevel",
    "UserProfile",
    "UserRole",
    "VMEventType",
    "VaRMethod",
    "VaRRequest",
    "VaRResult",
    "ValidationCompletedDetails",
    "ValidationReport",
    "ValidationStartedDetails",
    "VenueCategory",
    "VenueCircuitBreakerConfig",
    "VenueFreshnessSLA",
    "VenuePositionBreakdownMessage",
    "VenueRecord",
    "VersionBumpDetails",
    "VolSurfaceTermStructureRecord",
    "WebSocketConnectEvent",
    "WebSocketConnectionClosed",
    "WebSocketConnectionOpened",
    "WebSocketDisconnectEvent",
    "WebSocketErrorEvent",
    "WebSocketPingEvent",
    "WebSocketPongEvent",
    "WebSocketReconnectEvent",
    "WebSocketSubscribeAckEvent",
    "WithdrawalRecord",
    "YieldCurveTenor",
    "aggregate_notional",
    "aggregate_positions",
    "validate_feature_columns_not_null",
]
