/**
 * Mock fixtures for the counterparty observability dashboard.
 *
 * These are deterministic placeholders used until strategy-service ships a
 * read-API for emission history. The shapes mirror the UAC Python types in
 * `./types.ts`. Swap-point: replace `MOCK_*` consumers with `useQuery` hooks
 * against the strategy-service API once it lands.
 *
 * Plan reference:
 *   unified-trading-pm/plans/active/signal_leasing_broadcast_architecture_2026_04_20.plan.md
 *   § Phase 5 — counterparty observability UI
 */

import type {
  BacktestVsLiveRow,
  Counterparty,
  DeliveryHealth,
  PnlAttributionRow,
  SignalEmission,
} from "./types";

export const MOCK_COUNTERPARTY: Counterparty = {
  id: "cp-qrt-alpha",
  name: "QRT-Alpha (staging fixture)",
  endpoint: "https://webhook.example-cp.com/odum/signals",
  schema_depth: "STANDARD",
  active: true,
  allowed_slots: [
    "btc_trend_rules_live_cefi-spot-1.0",
    "eth_meanrev_stat_arb_pairs_fixed_cefi-perp-1.0",
    "sp500_mlrules_dated_future-cme-2.0",
  ],
  rate_limit_per_strategy_per_sec: 10,
  pnl_reporting_enabled: false,
};

const SLOTS = MOCK_COUNTERPARTY.allowed_slots;

function iso(daysAgo: number, hoursAgo = 0, minutesAgo = 0): string {
  // Deterministic anchor — 2026-04-20T12:00:00Z
  const anchor = new Date("2026-04-20T12:00:00Z").getTime();
  const ms =
    anchor -
    daysAgo * 86_400_000 -
    hoursAgo * 3_600_000 -
    minutesAgo * 60_000;
  return new Date(ms).toISOString();
}

export const MOCK_SIGNAL_EMISSIONS: readonly SignalEmission[] = [
  {
    emission_id: "em-0001",
    strategy_id: "strategy-btc-trend-001",
    slot_label: SLOTS[0],
    counterparty_id: MOCK_COUNTERPARTY.id,
    emission_timestamp: iso(0, 0, 3),
    schema_depth: "STANDARD",
    signal_payload_summary: "direction=long weight=0.8 horizon=4h",
    delivery_status: "delivered",
    delivery_attempt: 1,
    idempotency_key: "idem-0001",
  },
  {
    emission_id: "em-0002",
    strategy_id: "strategy-btc-trend-001",
    slot_label: SLOTS[0],
    counterparty_id: MOCK_COUNTERPARTY.id,
    emission_timestamp: iso(0, 0, 27),
    schema_depth: "STANDARD",
    signal_payload_summary: "direction=long weight=0.6 horizon=4h",
    delivery_status: "delivered",
    delivery_attempt: 1,
    idempotency_key: "idem-0002",
  },
  {
    emission_id: "em-0003",
    strategy_id: "strategy-eth-meanrev-002",
    slot_label: SLOTS[1],
    counterparty_id: MOCK_COUNTERPARTY.id,
    emission_timestamp: iso(0, 1, 12),
    schema_depth: "STANDARD",
    signal_payload_summary: "direction=short weight=0.4 pair=ETH/BTC",
    delivery_status: "retrying",
    delivery_attempt: 2,
    idempotency_key: "idem-0003",
  },
  {
    emission_id: "em-0004",
    strategy_id: "strategy-sp500-ml-003",
    slot_label: SLOTS[2],
    counterparty_id: MOCK_COUNTERPARTY.id,
    emission_timestamp: iso(0, 2, 5),
    schema_depth: "STANDARD",
    signal_payload_summary: "direction=flat weight=0 horizon=1d",
    delivery_status: "delivered",
    delivery_attempt: 1,
    idempotency_key: "idem-0004",
  },
  {
    emission_id: "em-0005",
    strategy_id: "strategy-btc-trend-001",
    slot_label: SLOTS[0],
    counterparty_id: MOCK_COUNTERPARTY.id,
    emission_timestamp: iso(0, 3, 40),
    schema_depth: "STANDARD",
    signal_payload_summary: "direction=long weight=1.0 horizon=4h",
    delivery_status: "delivered",
    delivery_attempt: 1,
    idempotency_key: "idem-0005",
  },
  {
    emission_id: "em-0006",
    strategy_id: "strategy-eth-meanrev-002",
    slot_label: SLOTS[1],
    counterparty_id: MOCK_COUNTERPARTY.id,
    emission_timestamp: iso(0, 4, 22),
    schema_depth: "STANDARD",
    signal_payload_summary: "direction=short weight=0.7 pair=ETH/BTC",
    delivery_status: "delivered",
    delivery_attempt: 1,
    idempotency_key: "idem-0006",
  },
  {
    emission_id: "em-0007",
    strategy_id: "strategy-sp500-ml-003",
    slot_label: SLOTS[2],
    counterparty_id: MOCK_COUNTERPARTY.id,
    emission_timestamp: iso(0, 6, 15),
    schema_depth: "STANDARD",
    signal_payload_summary: "direction=long weight=0.3 horizon=1d",
    delivery_status: "failed",
    delivery_attempt: 3,
    idempotency_key: "idem-0007",
  },
  {
    emission_id: "em-0008",
    strategy_id: "strategy-btc-trend-001",
    slot_label: SLOTS[0],
    counterparty_id: MOCK_COUNTERPARTY.id,
    emission_timestamp: iso(0, 8, 0),
    schema_depth: "STANDARD",
    signal_payload_summary: "direction=long weight=0.9 horizon=4h",
    delivery_status: "delivered",
    delivery_attempt: 1,
    idempotency_key: "idem-0008",
  },
  {
    emission_id: "em-0009",
    strategy_id: "strategy-eth-meanrev-002",
    slot_label: SLOTS[1],
    counterparty_id: MOCK_COUNTERPARTY.id,
    emission_timestamp: iso(0, 10, 30),
    schema_depth: "STANDARD",
    signal_payload_summary: "direction=flat weight=0 pair=ETH/BTC",
    delivery_status: "delivered",
    delivery_attempt: 1,
    idempotency_key: "idem-0009",
  },
  {
    emission_id: "em-0010",
    strategy_id: "strategy-btc-trend-001",
    slot_label: SLOTS[0],
    counterparty_id: MOCK_COUNTERPARTY.id,
    emission_timestamp: iso(1, 0, 0),
    schema_depth: "STANDARD",
    signal_payload_summary: "direction=short weight=0.5 horizon=4h",
    delivery_status: "delivered",
    delivery_attempt: 1,
    idempotency_key: "idem-0010",
  },
  {
    emission_id: "em-0011",
    strategy_id: "strategy-sp500-ml-003",
    slot_label: SLOTS[2],
    counterparty_id: MOCK_COUNTERPARTY.id,
    emission_timestamp: iso(1, 2, 14),
    schema_depth: "STANDARD",
    signal_payload_summary: "direction=long weight=0.6 horizon=1d",
    delivery_status: "delivered",
    delivery_attempt: 1,
    idempotency_key: "idem-0011",
  },
  {
    emission_id: "em-0012",
    strategy_id: "strategy-eth-meanrev-002",
    slot_label: SLOTS[1],
    counterparty_id: MOCK_COUNTERPARTY.id,
    emission_timestamp: iso(1, 4, 50),
    schema_depth: "STANDARD",
    signal_payload_summary: "direction=short weight=0.3 pair=ETH/BTC",
    delivery_status: "retrying",
    delivery_attempt: 2,
    idempotency_key: "idem-0012",
  },
  {
    emission_id: "em-0013",
    strategy_id: "strategy-btc-trend-001",
    slot_label: SLOTS[0],
    counterparty_id: MOCK_COUNTERPARTY.id,
    emission_timestamp: iso(1, 8, 5),
    schema_depth: "STANDARD",
    signal_payload_summary: "direction=long weight=0.7 horizon=4h",
    delivery_status: "delivered",
    delivery_attempt: 1,
    idempotency_key: "idem-0013",
  },
  {
    emission_id: "em-0014",
    strategy_id: "strategy-sp500-ml-003",
    slot_label: SLOTS[2],
    counterparty_id: MOCK_COUNTERPARTY.id,
    emission_timestamp: iso(2, 1, 0),
    schema_depth: "STANDARD",
    signal_payload_summary: "direction=flat weight=0 horizon=1d",
    delivery_status: "delivered",
    delivery_attempt: 1,
    idempotency_key: "idem-0014",
  },
  {
    emission_id: "em-0015",
    strategy_id: "strategy-eth-meanrev-002",
    slot_label: SLOTS[1],
    counterparty_id: MOCK_COUNTERPARTY.id,
    emission_timestamp: iso(2, 3, 30),
    schema_depth: "STANDARD",
    signal_payload_summary: "direction=short weight=0.8 pair=ETH/BTC",
    delivery_status: "delivered",
    delivery_attempt: 1,
    idempotency_key: "idem-0015",
  },
  {
    emission_id: "em-0016",
    strategy_id: "strategy-btc-trend-001",
    slot_label: SLOTS[0],
    counterparty_id: MOCK_COUNTERPARTY.id,
    emission_timestamp: iso(2, 6, 20),
    schema_depth: "STANDARD",
    signal_payload_summary: "direction=long weight=0.9 horizon=4h",
    delivery_status: "delivered",
    delivery_attempt: 1,
    idempotency_key: "idem-0016",
  },
  {
    emission_id: "em-0017",
    strategy_id: "strategy-sp500-ml-003",
    slot_label: SLOTS[2],
    counterparty_id: MOCK_COUNTERPARTY.id,
    emission_timestamp: iso(3, 0, 0),
    schema_depth: "STANDARD",
    signal_payload_summary: "direction=long weight=0.4 horizon=1d",
    delivery_status: "delivered",
    delivery_attempt: 1,
    idempotency_key: "idem-0017",
  },
  {
    emission_id: "em-0018",
    strategy_id: "strategy-eth-meanrev-002",
    slot_label: SLOTS[1],
    counterparty_id: MOCK_COUNTERPARTY.id,
    emission_timestamp: iso(3, 2, 10),
    schema_depth: "STANDARD",
    signal_payload_summary: "direction=short weight=0.5 pair=ETH/BTC",
    delivery_status: "delivered",
    delivery_attempt: 1,
    idempotency_key: "idem-0018",
  },
  {
    emission_id: "em-0019",
    strategy_id: "strategy-btc-trend-001",
    slot_label: SLOTS[0],
    counterparty_id: MOCK_COUNTERPARTY.id,
    emission_timestamp: iso(3, 5, 45),
    schema_depth: "STANDARD",
    signal_payload_summary: "direction=long weight=0.8 horizon=4h",
    delivery_status: "delivered",
    delivery_attempt: 1,
    idempotency_key: "idem-0019",
  },
  {
    emission_id: "em-0020",
    strategy_id: "strategy-sp500-ml-003",
    slot_label: SLOTS[2],
    counterparty_id: MOCK_COUNTERPARTY.id,
    emission_timestamp: iso(4, 0, 0),
    schema_depth: "STANDARD",
    signal_payload_summary: "direction=flat weight=0 horizon=1d",
    delivery_status: "delivered",
    delivery_attempt: 1,
    idempotency_key: "idem-0020",
  },
  {
    emission_id: "em-0021",
    strategy_id: "strategy-btc-trend-001",
    slot_label: SLOTS[0],
    counterparty_id: MOCK_COUNTERPARTY.id,
    emission_timestamp: iso(4, 6, 20),
    schema_depth: "STANDARD",
    signal_payload_summary: "direction=short weight=0.6 horizon=4h",
    delivery_status: "delivered",
    delivery_attempt: 1,
    idempotency_key: "idem-0021",
  },
  {
    emission_id: "em-0022",
    strategy_id: "strategy-eth-meanrev-002",
    slot_label: SLOTS[1],
    counterparty_id: MOCK_COUNTERPARTY.id,
    emission_timestamp: iso(5, 1, 0),
    schema_depth: "STANDARD",
    signal_payload_summary: "direction=short weight=0.7 pair=ETH/BTC",
    delivery_status: "failed",
    delivery_attempt: 4,
    idempotency_key: "idem-0022",
  },
  {
    emission_id: "em-0023",
    strategy_id: "strategy-sp500-ml-003",
    slot_label: SLOTS[2],
    counterparty_id: MOCK_COUNTERPARTY.id,
    emission_timestamp: iso(5, 4, 45),
    schema_depth: "STANDARD",
    signal_payload_summary: "direction=long weight=0.5 horizon=1d",
    delivery_status: "delivered",
    delivery_attempt: 1,
    idempotency_key: "idem-0023",
  },
  {
    emission_id: "em-0024",
    strategy_id: "strategy-btc-trend-001",
    slot_label: SLOTS[0],
    counterparty_id: MOCK_COUNTERPARTY.id,
    emission_timestamp: iso(6, 0, 0),
    schema_depth: "STANDARD",
    signal_payload_summary: "direction=long weight=0.9 horizon=4h",
    delivery_status: "delivered",
    delivery_attempt: 1,
    idempotency_key: "idem-0024",
  },
  {
    emission_id: "em-0025",
    strategy_id: "strategy-eth-meanrev-002",
    slot_label: SLOTS[1],
    counterparty_id: MOCK_COUNTERPARTY.id,
    emission_timestamp: iso(6, 5, 30),
    schema_depth: "STANDARD",
    signal_payload_summary: "direction=flat weight=0 pair=ETH/BTC",
    delivery_status: "delivered",
    delivery_attempt: 1,
    idempotency_key: "idem-0025",
  },
];

export const MOCK_BACKTEST_COMPARISON: readonly BacktestVsLiveRow[] = [
  {
    slot_label: SLOTS[0],
    backtest_sharpe: 1.82,
    backtest_return_pct: 14.3,
    live_signal_count: 112,
    live_signal_hit_rate: 0.58,
  },
  {
    slot_label: SLOTS[1],
    backtest_sharpe: 1.41,
    backtest_return_pct: 9.6,
    live_signal_count: 84,
    live_signal_hit_rate: 0.54,
  },
  {
    slot_label: SLOTS[2],
    backtest_sharpe: 2.07,
    backtest_return_pct: 18.2,
    live_signal_count: 63,
    live_signal_hit_rate: 0.62,
  },
];

export const MOCK_DELIVERY_HEALTH: DeliveryHealth = {
  success_rate: 0.987,
  retries_24h: 12,
  avg_latency_ms: 145,
  last_delivery_at: iso(0, 0, 3),
  total_deliveries_24h: 247,
};

export const MOCK_PNL_ATTRIBUTION: readonly PnlAttributionRow[] = [
  {
    slot_label: SLOTS[0],
    reported_pnl_usd: 18_420.55,
    reported_signal_count: 108,
    reporting_window_start: iso(30),
    reporting_window_end: iso(0),
  },
  {
    slot_label: SLOTS[1],
    reported_pnl_usd: 6_780.14,
    reported_signal_count: 79,
    reporting_window_start: iso(30),
    reporting_window_end: iso(0),
  },
  {
    slot_label: SLOTS[2],
    reported_pnl_usd: 24_900.01,
    reported_signal_count: 61,
    reporting_window_start: iso(30),
    reporting_window_end: iso(0),
  },
];
