"use client";

import { createContext, useContext, type Dispatch, type RefObject, type SetStateAction } from "react";
import type * as api from "@/hooks/deployment/_api-stub";
import type { DataStatusResponse, CategoryStatus, CreateDeploymentResponse } from "@/lib/types/deployment";
import type { VenueCheckResponse, DataTypeCheckResponse, TurboDataStatusResponse } from "@/hooks/deployment/_api-stub";
import type { DataStatusTabProps } from "./types";
import type { HeatmapDay } from "./build-heatmap-data";

export interface DataStatusTabContextValue {
  serviceName: string;
  deploymentResult?: CreateDeploymentResponse | null;
  isDeploying?: boolean;
  onDeployMissing?: DataStatusTabProps["onDeployMissing"];
  startDate: string;
  setStartDate: Dispatch<SetStateAction<string>>;
  endDate: string;
  setEndDate: Dispatch<SetStateAction<string>>;
  dataStatusMode: "batch" | "live";
  setDataStatusMode: Dispatch<SetStateAction<"batch" | "live">>;
  selectedCategories: string[];
  setSelectedCategories: Dispatch<SetStateAction<string[]>>;
  selectedVenues: string[];
  setSelectedVenues: Dispatch<SetStateAction<string[]>>;
  selectedFolders: string[];
  setSelectedFolders: Dispatch<SetStateAction<string[]>>;
  selectedDataTypes: string[];
  setSelectedDataTypes: Dispatch<SetStateAction<string[]>>;
  availableVenues: string[];
  setAvailableVenues: Dispatch<SetStateAction<string[]>>;
  venuesLoading: boolean;
  setVenuesLoading: Dispatch<SetStateAction<boolean>>;
  availableCategories: string[];
  setAvailableCategories: Dispatch<SetStateAction<string[]>>;
  categoriesLoading: boolean;
  setCategoriesLoading: Dispatch<SetStateAction<boolean>>;
  venueAvailableFolders: string[];
  setVenueAvailableFolders: Dispatch<SetStateAction<string[]>>;
  venueAvailableDataTypes: string[];
  setVenueAvailableDataTypes: Dispatch<SetStateAction<string[]>>;
  venueFiltersLoading: boolean;
  setVenueFiltersLoading: Dispatch<SetStateAction<boolean>>;
  fileListingData: api.ListFilesResponse | null;
  setFileListingData: Dispatch<SetStateAction<api.ListFilesResponse | null>>;
  fileListingLoading: boolean;
  setFileListingLoading: Dispatch<SetStateAction<boolean>>;
  fileListingError: string | null;
  setFileListingError: Dispatch<SetStateAction<string | null>>;
  showFileListing: boolean;
  setShowFileListing: Dispatch<SetStateAction<boolean>>;
  selectedTimeframe: string;
  setSelectedTimeframe: Dispatch<SetStateAction<string>>;
  availableTimeframes: string[];
  data: DataStatusResponse | null;
  setData: Dispatch<SetStateAction<DataStatusResponse | null>>;
  turboData: TurboDataStatusResponse | null;
  setTurboData: Dispatch<SetStateAction<TurboDataStatusResponse | null>>;
  venueCheckData: VenueCheckResponse | null;
  setVenueCheckData: Dispatch<SetStateAction<VenueCheckResponse | null>>;
  dataTypeCheckData: DataTypeCheckResponse | null;
  setDataTypeCheckData: Dispatch<SetStateAction<DataTypeCheckResponse | null>>;
  checkVenues: boolean;
  checkDataTypes: boolean;
  useTurboMode: boolean;
  turboSubDimension: string | undefined;
  loading: boolean;
  setLoading: Dispatch<SetStateAction<boolean>>;
  clearingCache: boolean;
  setClearingCache: Dispatch<SetStateAction<boolean>>;
  error: string | null;
  setError: Dispatch<SetStateAction<string | null>>;
  expandedCategories: Set<string>;
  setExpandedCategories: Dispatch<SetStateAction<Set<string>>>;
  expandedDates: Set<string>;
  setExpandedDates: Dispatch<SetStateAction<Set<string>>>;
  expandedVenues: Set<string>;
  setExpandedVenues: Dispatch<SetStateAction<Set<string>>>;
  viewMode: "table" | "calendar";
  setViewMode: Dispatch<SetStateAction<"table" | "calendar">>;
  selectedCalendarDate: string | null;
  setSelectedCalendarDate: Dispatch<SetStateAction<string | null>>;
  deployMissingModalOpen: boolean;
  setDeployMissingModalOpen: Dispatch<SetStateAction<boolean>>;
  deployMissingForce: boolean;
  setDeployMissingForce: Dispatch<SetStateAction<boolean>>;
  deployMissingDryRun: boolean;
  setDeployMissingDryRun: Dispatch<SetStateAction<boolean>>;
  deployMissingDateGranularity: "daily" | "weekly" | "monthly" | "none";
  setDeployMissingDateGranularity: Dispatch<SetStateAction<"daily" | "weekly" | "monthly" | "none">>;
  deployMissingRegion: string;
  setDeployMissingRegion: Dispatch<SetStateAction<string>>;
  backendRegion: string;
  setBackendRegion: Dispatch<SetStateAction<string>>;
  showDeployMissingRegionWarning: boolean;
  setShowDeployMissingRegionWarning: Dispatch<SetStateAction<boolean>>;
  firstDayOfMonthOnly: boolean;
  setFirstDayOfMonthOnly: Dispatch<SetStateAction<boolean>>;
  requireFreshness: boolean;
  setRequireFreshness: Dispatch<SetStateAction<boolean>>;
  freshnessDate: string;
  setFreshnessDate: Dispatch<SetStateAction<string>>;
  instrumentSearchMode: boolean;
  setInstrumentSearchMode: Dispatch<SetStateAction<boolean>>;
  instrumentSearchQuery: string;
  setInstrumentSearchQuery: Dispatch<SetStateAction<string>>;
  instrumentSearchResults: api.InstrumentSearchResult[];
  setInstrumentSearchResults: Dispatch<SetStateAction<api.InstrumentSearchResult[]>>;
  instrumentSearchLoading: boolean;
  setInstrumentSearchLoading: Dispatch<SetStateAction<boolean>>;
  selectedInstrument: api.InstrumentSearchResult | null;
  setSelectedInstrument: Dispatch<SetStateAction<api.InstrumentSearchResult | null>>;
  instrumentAvailability: api.InstrumentAvailabilityResponse | null;
  setInstrumentAvailability: Dispatch<SetStateAction<api.InstrumentAvailabilityResponse | null>>;
  instrumentAvailabilityLoading: boolean;
  setInstrumentAvailabilityLoading: Dispatch<SetStateAction<boolean>>;
  instrumentAvailabilityError: string | null;
  setInstrumentAvailabilityError: Dispatch<SetStateAction<string | null>>;
  showInstrumentDropdown: boolean;
  setShowInstrumentDropdown: Dispatch<SetStateAction<boolean>>;
  supportsVenueCheck: boolean;
  supportsDataTypeCheck: boolean;
  requestIdRef: RefObject<number>;
  abortControllerRef: RefObject<AbortController | null>;
  searchInstrumentsDebounceRef: RefObject<ReturnType<typeof setTimeout> | null>;
  cancelQuery: () => void;
  fetchData: (fetchStart: string, fetchEnd: string) => Promise<void>;
  handleClearDataStatusCache: () => Promise<void>;
  fetchFileListing: () => Promise<void>;
  fetchInstruments: (query: string) => Promise<void>;
  fetchInstrumentAvailability: () => Promise<void>;
  toggleVenue: (venueKey: string) => void;
  toggleDate: (dateKey: string) => void;
  toggleCategory: (cat: string) => void;
  totalMissing: number;
  categoriesWithMissing: string[];
  handleOpenDeployMissingModal: () => void;
  effectiveDeployCategories: string[];
  handleConfirmDeployMissing: (previewRefreshOnly?: boolean) => void;
  handleInstrumentDeployMissing: () => void;
  heatmapData: HeatmapDay[];
  getCategoryCompletion: (catData: CategoryStatus) => number;
  getMissingCount: (catData: CategoryStatus) => number;
}

export const DataStatusTabCtx = createContext<DataStatusTabContextValue | null>(null);

export function useDataStatusTabCtx(): DataStatusTabContextValue {
  const v = useContext(DataStatusTabCtx);
  if (!v) {
    throw new Error("useDataStatusTabCtx must be used within DataStatusProvider");
  }
  return v;
}
