import type { RouteMapping } from "./lifecycle-types";

// Route to lifecycle mapping — all platform routes use /services/{service}/... prefix
export const routeMappings: RouteMapping[] = [
  // ACQUIRE stage — Data Service
  {
    path: "/services/data/overview",
    label: "Data",
    primaryStage: "acquire",
    lanes: ["data"],
    description: "Pipeline status, venue coverage, freshness",
    requiresAuth: true,
  },

  // BUILD stage — Research Service
  {
    path: "/services/research/overview",
    label: "Research",
    primaryStage: "build",
    lanes: ["ml", "strategy", "execution"],
    description: "ML models, strategy research, execution research",
    requiresAuth: true,
  },
  {
    path: "/services/research/ml",
    label: "ML Models & Training",
    primaryStage: "build",
    lanes: ["ml"],
    requiresAuth: true,
  },
  {
    path: "/services/research/ml/training",
    label: "Training",
    primaryStage: "build",
    lanes: ["ml"],
    requiresAuth: true,
  },
  {
    path: "/services/research/ml/analysis",
    label: "Analysis",
    primaryStage: "build",
    lanes: ["ml"],
    requiresAuth: true,
  },
  {
    path: "/services/research/ml/registry",
    label: "Model Registry",
    primaryStage: "build",
    secondaryStage: "promote",
    lanes: ["ml"],
    requiresAuth: true,
  },
  {
    path: "/services/research/ml/monitoring",
    label: "Model Observe",
    primaryStage: "observe",
    lanes: ["ml"],
    requiresAuth: true,
  },
  {
    path: "/services/research/ml/governance",
    label: "ML Governance",
    primaryStage: "manage",
    lanes: ["ml", "compliance"],
    requiresAuth: true,
  },
  {
    path: "/services/research/strategy/backtests",
    label: "Backtests",
    primaryStage: "build",
    lanes: ["strategy"],
    requiresAuth: true,
  },
  {
    path: "/services/research/strategy/compare",
    label: "Compare",
    primaryStage: "build",
    lanes: ["strategy"],
    requiresAuth: true,
  },
  {
    path: "/services/research/strategy/results",
    label: "Results",
    primaryStage: "build",
    lanes: ["strategy"],
    requiresAuth: true,
  },
  {
    path: "/services/research/strategy/heatmap",
    label: "Heatmap",
    primaryStage: "build",
    lanes: ["strategy"],
    requiresAuth: true,
  },
  {
    path: "/services/research/strategy/candidates",
    label: "Strategy Candidates",
    primaryStage: "promote",
    lanes: ["strategy"],
    requiresAuth: true,
  },
  {
    path: "/services/research/strategy/handoff",
    label: "Strategy Handoff",
    primaryStage: "promote",
    lanes: ["strategy"],
    requiresAuth: true,
  },
  {
    path: "/services/execution/algos",
    label: "Algo Comparison",
    primaryStage: "build",
    lanes: ["execution"],
    requiresAuth: true,
  },
  {
    path: "/services/execution/venues",
    label: "Venues",
    primaryStage: "build",
    secondaryStage: "acquire",
    lanes: ["execution", "data"],
    requiresAuth: true,
  },
  {
    path: "/services/execution/tca",
    label: "TCA",
    primaryStage: "observe",
    lanes: ["execution"],
    requiresAuth: true,
  },
  {
    path: "/services/execution/benchmarks",
    label: "Benchmarks",
    primaryStage: "build",
    lanes: ["execution"],
    requiresAuth: true,
  },

  // G2.10 — Portfolio allocator surfaces (two commercial audiences on one
  // ``portfolio_allocator`` core). Rule 03 same-system-principle.
  {
    path: "/services/investment-management/allocator",
    label: "Allocator (IM)",
    primaryStage: "promote",
    secondaryStage: "manage",
    lanes: ["strategy", "capital"],
    description: "IM-side portfolio allocator — proposal-then-apply flow.",
    requiresAuth: true,
  },
  {
    path: "/services/trading-platform/allocator",
    label: "Allocator (platform)",
    primaryStage: "promote",
    secondaryStage: "run",
    lanes: ["strategy", "execution"],
    description: "Trading-platform allocator — auto-apply on client-infra.",
    requiresAuth: true,
  },

  // PROMOTE stage
  {
    path: "/services/promote/pipeline",
    label: "Strategy Promotion",
    primaryStage: "promote",
    lanes: ["strategy", "ml"],
    description: "Review, assess, and approve strategies for live deployment",
    requiresAuth: true,
  },
  {
    path: "/config",
    label: "Config",
    primaryStage: "promote",
    secondaryStage: "manage",
    lanes: ["strategy", "execution"],
    requiresAuth: true,
  },

  // RUN stage — Trading Service
  // /dashboard is the platform hub — not mapped here so lifecycle nav has no active stage on that route.
  {
    path: "/services/trading/overview",
    label: "Trading Overview",
    primaryStage: "run",
    lanes: ["execution"],
    description: "Command center — P&L, strategies, alerts",
    requiresAuth: true,
  },
  {
    path: "/services/trading/terminal",
    label: "Terminal",
    primaryStage: "run",
    lanes: ["execution"],
    description: "Live trading — charts, order book, order entry",
    requiresAuth: true,
  },
  {
    path: "/services/trading/positions",
    label: "Positions",
    primaryStage: "run",
    secondaryStage: "observe",
    lanes: ["execution", "capital"],
    requiresAuth: true,
  },
  {
    path: "/services/trading/orders",
    label: "Orders",
    primaryStage: "run",
    lanes: ["execution"],
    requiresAuth: true,
  },
  {
    path: "/services/trading/book",
    label: "Book Trade",
    primaryStage: "run",
    lanes: ["execution"],
    requiresAuth: true,
  },
  {
    path: "/services/trading/accounts",
    label: "Accounts",
    primaryStage: "run",
    lanes: ["execution", "capital"],
    requiresAuth: true,
  },
  {
    path: "/services/trading/pnl",
    label: "P&L Breakdown",
    primaryStage: "run",
    secondaryStage: "report",
    lanes: ["execution", "capital"],
    requiresAuth: true,
  },
  {
    path: "/services/trading/strategies",
    label: "Strategies",
    primaryStage: "run",
    lanes: ["strategy"],
    requiresAuth: true,
  },
  {
    path: "/services/observe/risk",
    label: "Risk",
    primaryStage: "observe",
    lanes: ["strategy", "execution", "capital"],
    requiresAuth: true,
  },
  {
    path: "/services/observe/alerts",
    label: "Alerts",
    primaryStage: "observe",
    lanes: ["strategy", "execution", "ml"],
    requiresAuth: true,
  },
  {
    path: "/services/observe/news",
    label: "News",
    primaryStage: "observe",
    lanes: ["strategy", "execution", "data"],
    requiresAuth: true,
  },
  {
    path: "/services/observe/strategy-health",
    label: "Strategy Health",
    primaryStage: "observe",
    lanes: ["strategy", "ml"],
    requiresAuth: true,
  },

  // Execution Service (Execute stage)
  {
    path: "/services/execution/overview",
    label: "Execution",
    primaryStage: "execute",
    lanes: ["execution"],
    description: "Live execution research and analytics",
    requiresAuth: true,
  },
  {
    path: "/services/execution/algos",
    label: "Algo Comparison",
    primaryStage: "execute",
    lanes: ["execution"],
    requiresAuth: true,
  },
  {
    path: "/services/execution/venues",
    label: "Venues",
    primaryStage: "execute",
    lanes: ["execution", "data"],
    requiresAuth: true,
  },
  {
    path: "/services/execution/tca",
    label: "TCA",
    primaryStage: "execute",
    lanes: ["execution"],
    requiresAuth: true,
  },
  {
    path: "/services/execution/benchmarks",
    label: "Benchmarks",
    primaryStage: "execute",
    lanes: ["execution"],
    requiresAuth: true,
  },
  {
    path: "/services/execution/candidates",
    label: "Candidates",
    primaryStage: "execute",
    lanes: ["execution"],
    requiresAuth: true,
  },
  {
    path: "/services/execution/handoff",
    label: "Handoff",
    primaryStage: "execute",
    lanes: ["execution"],
    requiresAuth: true,
  },

  // OBSERVE stage
  {
    path: "/services/observe/health",
    label: "Health",
    primaryStage: "observe",
    lanes: ["data", "execution"],
    requiresAuth: true,
  },
  {
    path: "/ops",
    label: "Operations",
    primaryStage: "observe",
    secondaryStage: "manage",
    lanes: ["execution", "data"],
    requiresAuth: true,
  },

  // MANAGE stage
  {
    path: "/services/manage/clients",
    label: "Clients",
    primaryStage: "manage",
    lanes: ["capital"],
    requiresAuth: true,
  },
  {
    path: "/services/manage/mandates",
    label: "Mandates",
    primaryStage: "manage",
    lanes: ["capital", "compliance"],
    requiresAuth: true,
  },
  {
    path: "/services/manage/fees",
    label: "Fees",
    primaryStage: "manage",
    lanes: ["capital"],
    requiresAuth: true,
  },
  {
    path: "/services/manage/users",
    label: "Users",
    primaryStage: "manage",
    lanes: ["compliance"],
    requiresAuth: true,
  },
  {
    path: "/approvals",
    label: "Approvals",
    primaryStage: "manage",
    lanes: ["compliance"],
    requiresAuth: true,
  },
  {
    path: "/admin",
    label: "Admin",
    primaryStage: "manage",
    lanes: ["compliance"],
    requiresAuth: true,
  },
  {
    path: "/services/manage/compliance",
    label: "Compliance",
    primaryStage: "manage",
    lanes: ["compliance"],
    requiresAuth: true,
  },

  // REPORT stage — Reports Service
  {
    path: "/services/reports/overview",
    label: "Reports",
    primaryStage: "report",
    lanes: ["capital", "compliance"],
    requiresAuth: true,
  },
  {
    path: "/services/reports/executive",
    label: "Executive",
    primaryStage: "report",
    secondaryStage: "observe",
    lanes: ["capital", "strategy"],
    requiresAuth: true,
  },

  // INVESTOR RELATIONS — presentations, disaster recovery, security
  {
    path: "/investor-relations",
    label: "Investor Relations",
    primaryStage: "report",
    lanes: ["capital", "compliance"],
    requiresAuth: true,
  },
  {
    path: "/investor-relations/board-presentation",
    label: "Board Presentation",
    primaryStage: "report",
    lanes: ["capital"],
    requiresAuth: true,
  },
  {
    path: "/investor-relations/disaster-recovery",
    label: "Disaster Recovery",
    primaryStage: "report",
    lanes: ["compliance"],
    requiresAuth: true,
  },

  // Public/commercial routes (no auth required)
  {
    path: "/",
    label: "Home",
    primaryStage: "acquire",
    lanes: ["data"],
    requiresAuth: false,
  },
  {
    path: "/services/data",
    label: "Data Service",
    primaryStage: "acquire",
    lanes: ["data"],
    requiresAuth: false,
  },
  {
    path: "/services/backtesting",
    label: "Backtesting Service",
    primaryStage: "build",
    lanes: ["strategy"],
    requiresAuth: false,
  },
  {
    path: "/services/execution",
    label: "Execution Service",
    primaryStage: "run",
    lanes: ["execution"],
    requiresAuth: false,
  },
  {
    path: "/services/platform",
    label: "Platform Service",
    primaryStage: "build",
    lanes: ["strategy", "execution", "ml"],
    requiresAuth: false,
  },
  {
    path: "/services/investment",
    label: "Manage",
    primaryStage: "manage",
    lanes: ["capital"],
    requiresAuth: false,
  },
  {
    path: "/services/regulatory",
    label: "Regulatory Service",
    primaryStage: "manage",
    lanes: ["compliance"],
    requiresAuth: false,
  },
];
