#!/usr/bin/env bash
#
# setup-workspace.sh — deployment-service
#
# Auto-generated by unified-trading-pm/scripts/rollout-manifest-driven-setup.sh
# Do NOT edit directly. To regenerate:
#   bash unified-trading-pm/scripts/rollout-manifest-driven-setup.sh --repo deployment-service
#
# Clones manifest dependencies as siblings, runs pre-flight checks, installs Python deps.
# Logic lives in unified-trading-pm/scripts/setup-workspace-from-manifest.sh (SSOT).
#
set -euo pipefail

SERVICE_NAME="deployment-service"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SERVICE_DIR="$(dirname "$SCRIPT_DIR")"
WORKSPACE_ROOT="${WORKSPACE_ROOT:-$(dirname "$SERVICE_DIR")}"
GH_ORG="${GH_ORG:-IggyIkenna}"
GH_TOKEN="${GH_TOKEN:-${GITHUB_TOKEN:-}}"

# ── CLONE PM FIRST (contains manifest + shared bootstrap script) ───────────────
PM_DEST="$WORKSPACE_ROOT/unified-trading-pm"
if [ ! -d "$PM_DEST" ]; then
    echo "Cloning unified-trading-pm (manifest source)..."
    if [ -n "$GH_TOKEN" ]; then
        git clone --depth=1 "https://x-access-token:${GH_TOKEN}@github.com/${GH_ORG}/unified-trading-pm.git" "$PM_DEST"
    else
        git clone --depth=1 "https://github.com/${GH_ORG}/unified-trading-pm.git" "$PM_DEST"
    fi
fi

# ── DELEGATE TO MANIFEST-DRIVEN SCRIPT (SSOT in PM) ───────────────────────────
exec bash "$PM_DEST/scripts/setup-workspace-from-manifest.sh" "$SERVICE_NAME" "$@"
