/**
 * Typed accessors for the instrument snapshot.
 *
 * The snapshot is generated by unified-trading-pm/scripts/openapi/generate_instrument_snapshot.py
 * from real GCS instrument data. It contains ALL instruments across all categories and venues
 * (typically 20,000+). This is permanent reference data, not cached.
 *
 * The UI must handle grouping, filtering, and virtualization at this scale.
 */

import snapshotData from "./instruments-snapshot.json";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface Instrument {
  instrument_key: string;
  venue: string;
  instrument_type: string;
  raw_symbol?: string;
  base_asset?: string;
  quote_asset?: string;
  status?: string;
  available_from_datetime?: string;
  available_to_datetime?: string;
  asset_group?: string;
  settle_asset?: string;
  tick_size?: number;
  min_size?: number;
  contract_size?: number;
  expiry?: string;
  strike?: number;
  option_type?: string;
  underlying?: string;
  margin_type?: string;
  legs?: string;
  is_trading_day?: boolean;
  regular_open_utc?: string;
  regular_close_utc?: string;
  early_close_utc?: string;
  category: string;
  /** Whether market data is assumed available for this instrument. */
  hasMarketData: boolean;
  // Sports-specific
  league?: string;
  home_team?: string;
  away_team?: string;
  bookmakers?: string[];
}

export interface SnapshotMeta {
  date: string;
  generated_by: string;
  total_instruments: number;
  categories: Record<string, number>;
  venues: Record<string, Record<string, number>>;
  sports_reference?: {
    team_count: number;
  };
}

// ---------------------------------------------------------------------------
// Data access
// ---------------------------------------------------------------------------

const snapshot = snapshotData as {
  _meta: SnapshotMeta;
  instruments: Instrument[];
};

/** Snapshot metadata (date, counts, venue summary). */
export const SNAPSHOT_META: SnapshotMeta = snapshot._meta;

/** All instruments in the snapshot. */
export const ALL_INSTRUMENTS: Instrument[] = snapshot.instruments;

// ---------------------------------------------------------------------------
// Pre-built indexes (computed once on import)
// ---------------------------------------------------------------------------

const _byVenue = new Map<string, Instrument[]>();
/** Grouped by snapshot `category` (CeFi/DeFi/TradFi/sports axis). */
const _byAssetGroup = new Map<string, Instrument[]>();
const _byType = new Map<string, Instrument[]>();

for (const inst of ALL_INSTRUMENTS) {
  // By venue
  const venueList = _byVenue.get(inst.venue);
  if (venueList) {
    venueList.push(inst);
  } else {
    _byVenue.set(inst.venue, [inst]);
  }

  // By asset group (snapshot field `category`)
  const agList = _byAssetGroup.get(inst.category);
  if (agList) {
    agList.push(inst);
  } else {
    _byAssetGroup.set(inst.category, [inst]);
  }

  // By instrument type
  const typeList = _byType.get(inst.instrument_type);
  if (typeList) {
    typeList.push(inst);
  } else {
    _byType.set(inst.instrument_type, [inst]);
  }
}

// ---------------------------------------------------------------------------
// Query helpers
// ---------------------------------------------------------------------------

/** Get all instruments for a specific venue (e.g., "BINANCE-SPOT", "AAVEV3-ETHEREUM"). */
export function getInstrumentsByVenue(venue: string): Instrument[] {
  return _byVenue.get(venue) ?? [];
}

/** Get all instruments for an asset group (e.g., "cefi", "defi", "tradfi", "sports"). */
export function getInstrumentsByAssetGroup(assetGroup: string): Instrument[] {
  return _byAssetGroup.get(assetGroup) ?? [];
}

/** Get all instruments of a given type (e.g., "spot_pair", "perp", "lending_market", "option"). */
export function getInstrumentsByType(instrumentType: string): Instrument[] {
  return _byType.get(instrumentType) ?? [];
}

/** Get all venue names that have at least one instrument. */
export function getVenuesWithInstruments(): string[] {
  return Array.from(_byVenue.keys()).sort();
}

/** Get all asset groups (snapshot `category` values) that have instruments. */
export function getAssetGroupsWithInstruments(): string[] {
  return Array.from(_byAssetGroup.keys()).sort();
}

/** Get all instrument types present in the snapshot. */
export function getInstrumentTypes(): string[] {
  return Array.from(_byType.keys()).sort();
}

/** Get sports fixtures (instruments with asset group "sports" on the snapshot). */
export function getSportsFixtures(): Instrument[] {
  return _byAssetGroup.get("sports") ?? [];
}

/** Get venues grouped by asset group (snapshot `category` field). */
export function getVenuesGroupedByAssetGroup(): Record<string, string[]> {
  const result: Record<string, string[]> = {};
  for (const inst of ALL_INSTRUMENTS) {
    if (!result[inst.category]) {
      result[inst.category] = [];
    }
    if (!result[inst.category].includes(inst.venue)) {
      result[inst.category].push(inst.venue);
    }
  }
  for (const ag of Object.keys(result)) {
    result[ag].sort();
  }
  return result;
}

/** Get instrument count per venue, optionally filtered by asset group. */
export function getVenueInstrumentCounts(assetGroup?: string): Record<string, number> {
  const source = assetGroup ? getInstrumentsByAssetGroup(assetGroup) : ALL_INSTRUMENTS;
  const counts: Record<string, number> = {};
  for (const inst of source) {
    counts[inst.venue] = (counts[inst.venue] ?? 0) + 1;
  }
  return counts;
}

/**
 * Search instruments by keyword (matches instrument_key, raw_symbol, base_asset, venue).
 * Returns at most `limit` results (default 100) for performance.
 */
export function searchInstruments(query: string, limit = 100): Instrument[] {
  const q = query.toUpperCase();
  const results: Instrument[] = [];

  for (const inst of ALL_INSTRUMENTS) {
    if (results.length >= limit) break;

    if (
      inst.instrument_key.toUpperCase().includes(q) ||
      (inst.raw_symbol?.toUpperCase().includes(q) ?? false) ||
      (inst.base_asset?.toUpperCase().includes(q) ?? false) ||
      inst.venue.toUpperCase().includes(q)
    ) {
      results.push(inst);
    }
  }

  return results;
}
