"""Venue execution registry — regional licensed venues (UK, FR, DE, IT, SE, AU additional)."""

from __future__ import annotations

from decimal import Decimal

from .venue_execution import (
    AntiDetectionLevel,
    CredentialType,
    ExecutionMethod,
    VenueCategory,
    VenueExecutionProfile,
)

REGIONAL_REGISTRY: dict[str, VenueExecutionProfile] = {
    # ── UK Additional ────────────────────────────────────────────────────
    "betfair_sb_uk": VenueExecutionProfile(
        venue_key="betfair_sb_uk",
        odds_api_key="betfair_sb_uk",
        display_name="Betfair Sportsbook (UK)",
        parent_company="Flutter Entertainment",
        venue_category=VenueCategory.SCRAPER,
        primary_execution_method=ExecutionMethod.BROWSER_AUTOMATION,
        credential_type=CredentialType.USERNAME_PASSWORD,
        login_url="https://www.betfair.com/sport/",
        config_secret_field="betfair_sb_uk_credentials",
        username_secret_key="username",
        password_secret_key="password",
        headquarters_country="GB",
        license_jurisdictions=["GB-UKGC", "MT-MGA"],
        available_countries=["GB", "IE"],
        supported_currencies=["GBP", "EUR"],
        min_bet=Decimal("0.10"),
        min_bet_currency="GBP",
        anti_detection_level=AntiDetectionLevel.MODERATE,
        commission_model="built_into_odds",
        withdrawal_fee=Decimal("0"),
        limits_winning_accounts=True,
        account_limiting_severity="moderate",
        notes="Betfair's fixed-odds sportsbook (NOT the exchange). Limits sharps.",
    ),
    "grosvenor": VenueExecutionProfile(
        venue_key="grosvenor",
        odds_api_key="grosvenor",
        display_name="Grosvenor Sport",
        parent_company="Rank Group",
        venue_category=VenueCategory.SCRAPER,
        primary_execution_method=ExecutionMethod.BROWSER_AUTOMATION,
        credential_type=CredentialType.USERNAME_PASSWORD,
        login_url="https://www.grosvenorsport.com/",
        config_secret_field="grosvenor_credentials",
        username_secret_key="username",
        password_secret_key="password",
        headquarters_country="GB",
        license_jurisdictions=["GB-UKGC"],
        supported_currencies=["GBP"],
        min_bet=Decimal("0.10"),
        min_bet_currency="GBP",
        anti_detection_level=AntiDetectionLevel.BASIC,
        commission_model="built_into_odds",
        withdrawal_fee=Decimal("0"),
        limits_winning_accounts=True,
        notes="Rank Group UK sportsbook. Casino-first brand.",
    ),
    "casumo": VenueExecutionProfile(
        venue_key="casumo",
        odds_api_key="casumo",
        display_name="Casumo",
        parent_company="Casumo Services Ltd",
        venue_category=VenueCategory.SCRAPER,
        primary_execution_method=ExecutionMethod.BROWSER_AUTOMATION,
        credential_type=CredentialType.USERNAME_PASSWORD,
        login_url="https://www.casumo.com/en-gb/sports/",
        config_secret_field="casumo_credentials",
        username_secret_key="username",
        password_secret_key="password",
        headquarters_country="MT",
        license_jurisdictions=["GB-UKGC", "MT-MGA", "SE-SGA"],
        available_countries=["GB", "SE", "NO", "FI", "DE"],
        supported_currencies=["GBP", "EUR", "SEK"],
        min_bet=Decimal("0.10"),
        min_bet_currency="GBP",
        anti_detection_level=AntiDetectionLevel.BASIC,
        commission_model="built_into_odds",
        withdrawal_fee=Decimal("0"),
        limits_winning_accounts=True,
        notes="Malta-based casino/sportsbook. Multi-market EU.",
    ),
    "leovegas": VenueExecutionProfile(
        venue_key="leovegas",
        odds_api_key="leovegas",
        display_name="LeoVegas",
        parent_company="MGM Resorts (acquired 2022)",
        venue_category=VenueCategory.SCRAPER,
        primary_execution_method=ExecutionMethod.BROWSER_AUTOMATION,
        credential_type=CredentialType.USERNAME_PASSWORD,
        login_url="https://www.leovegas.com/en-gb/betting/",
        config_secret_field="leovegas_credentials",
        username_secret_key="username",
        password_secret_key="password",
        headquarters_country="SE",
        license_jurisdictions=["GB-UKGC", "MT-MGA", "SE-SGA"],
        available_countries=["GB", "SE", "DE", "DK", "IT"],
        supported_currencies=["GBP", "EUR", "SEK"],
        min_bet=Decimal("0.10"),
        min_bet_currency="GBP",
        anti_detection_level=AntiDetectionLevel.BASIC,
        commission_model="built_into_odds",
        withdrawal_fee=Decimal("0"),
        limits_winning_accounts=True,
        notes="MGM-owned EU sportsbook. Originally Swedish mobile casino.",
    ),
    # ── France ───────────────────────────────────────────────────────────
    "winamax_fr": VenueExecutionProfile(
        venue_key="winamax_fr",
        odds_api_key="winamax_fr",
        display_name="Winamax (France)",
        parent_company="Winamax SAS",
        venue_category=VenueCategory.SCRAPER,
        primary_execution_method=ExecutionMethod.BROWSER_AUTOMATION,
        credential_type=CredentialType.USERNAME_PASSWORD,
        login_url="https://www.winamax.fr/paris-sportifs",
        config_secret_field="winamax_fr_credentials",
        username_secret_key="username",
        password_secret_key="password",
        headquarters_country="FR",
        license_jurisdictions=["FR-ANJ"],
        available_countries=["FR"],
        requires_residency=True,
        residency_countries=["FR"],
        supported_currencies=["EUR"],
        min_bet=Decimal("0.50"),
        min_bet_currency="EUR",
        anti_detection_level=AntiDetectionLevel.MODERATE,
        commission_model="built_into_odds",
        withdrawal_fee=Decimal("0"),
        limits_winning_accounts=True,
        notes="French-licensed. Competitive odds. FR residents only.",
    ),
    "winamax_de": VenueExecutionProfile(
        venue_key="winamax_de",
        odds_api_key="winamax_de",
        display_name="Winamax (Germany)",
        parent_company="Winamax SAS",
        venue_category=VenueCategory.SCRAPER,
        primary_execution_method=ExecutionMethod.BROWSER_AUTOMATION,
        credential_type=CredentialType.USERNAME_PASSWORD,
        login_url="https://www.winamax.de/sportwetten",
        config_secret_field="winamax_de_credentials",
        username_secret_key="username",
        password_secret_key="password",
        headquarters_country="FR",
        license_jurisdictions=["DE-GGL"],
        available_countries=["DE"],
        requires_residency=True,
        residency_countries=["DE"],
        supported_currencies=["EUR"],
        min_bet=Decimal("0.50"),
        min_bet_currency="EUR",
        anti_detection_level=AntiDetectionLevel.MODERATE,
        commission_model="built_into_odds",
        withdrawal_fee=Decimal("0"),
        notes="Winamax German market. GGL-licensed. 5.3% turnover tax on bets.",
    ),
    "parionssport_fr": VenueExecutionProfile(
        venue_key="parionssport_fr",
        odds_api_key="parionssport_fr",
        display_name="ParionsSport (FDJ)",
        parent_company="Francaise des Jeux (FDJ)",
        venue_category=VenueCategory.SCRAPER,
        primary_execution_method=ExecutionMethod.BROWSER_AUTOMATION,
        credential_type=CredentialType.USERNAME_PASSWORD,
        login_url="https://www.enligne.parionssport.fdj.fr/",
        config_secret_field="parionssport_fr_credentials",
        username_secret_key="username",
        password_secret_key="password",
        headquarters_country="FR",
        license_jurisdictions=["FR-ANJ"],
        available_countries=["FR"],
        requires_residency=True,
        residency_countries=["FR"],
        supported_currencies=["EUR"],
        min_bet=Decimal("1"),
        min_bet_currency="EUR",
        anti_detection_level=AntiDetectionLevel.MODERATE,
        commission_model="built_into_odds",
        withdrawal_fee=Decimal("0"),
        notes="French state lottery sportsbook. Wide retail network.",
    ),
    "pmu_fr": VenueExecutionProfile(
        venue_key="pmu_fr",
        odds_api_key="pmu_fr",
        display_name="PMU (France)",
        parent_company="Pari Mutuel Urbain",
        venue_category=VenueCategory.SCRAPER,
        primary_execution_method=ExecutionMethod.BROWSER_AUTOMATION,
        credential_type=CredentialType.USERNAME_PASSWORD,
        login_url="https://paris-sportifs.pmu.fr/",
        config_secret_field="pmu_fr_credentials",
        username_secret_key="username",
        password_secret_key="password",
        headquarters_country="FR",
        license_jurisdictions=["FR-ANJ"],
        available_countries=["FR"],
        requires_residency=True,
        residency_countries=["FR"],
        supported_currencies=["EUR"],
        min_bet=Decimal("1"),
        min_bet_currency="EUR",
        anti_detection_level=AntiDetectionLevel.BASIC,
        commission_model="built_into_odds",
        withdrawal_fee=Decimal("0"),
        notes="French horse racing monopoly. Also offers sports betting.",
    ),
    "netbet_fr": VenueExecutionProfile(
        venue_key="netbet_fr",
        odds_api_key="netbet_fr",
        display_name="NetBet (France)",
        parent_company="NetBet Enterprises Ltd",
        venue_category=VenueCategory.SCRAPER,
        primary_execution_method=ExecutionMethod.BROWSER_AUTOMATION,
        credential_type=CredentialType.USERNAME_PASSWORD,
        login_url="https://www.netbet.fr/sport",
        config_secret_field="netbet_fr_credentials",
        username_secret_key="username",
        password_secret_key="password",
        headquarters_country="MT",
        license_jurisdictions=["FR-ANJ", "MT-MGA"],
        available_countries=["FR"],
        requires_residency=True,
        residency_countries=["FR"],
        supported_currencies=["EUR"],
        min_bet=Decimal("0.50"),
        min_bet_currency="EUR",
        anti_detection_level=AntiDetectionLevel.BASIC,
        commission_model="built_into_odds",
        withdrawal_fee=Decimal("0"),
        notes="Malta-based, French-licensed sportsbook.",
    ),
    # ── Germany ──────────────────────────────────────────────────────────
    "tipico_de": VenueExecutionProfile(
        venue_key="tipico_de",
        odds_api_key="tipico_de",
        display_name="Tipico (Germany)",
        parent_company="Tipico Group",
        venue_category=VenueCategory.SCRAPER,
        primary_execution_method=ExecutionMethod.BROWSER_AUTOMATION,
        credential_type=CredentialType.USERNAME_PASSWORD,
        login_url="https://www.tipico.de/sportwetten",
        config_secret_field="tipico_de_credentials",
        username_secret_key="username",
        password_secret_key="password",
        headquarters_country="MT",
        license_jurisdictions=["DE-GGL", "MT-MGA"],
        available_countries=["DE", "AT"],
        requires_residency=True,
        residency_countries=["DE"],
        supported_currencies=["EUR"],
        min_bet=Decimal("1"),
        min_bet_currency="EUR",
        anti_detection_level=AntiDetectionLevel.MODERATE,
        commission_model="built_into_odds",
        withdrawal_fee=Decimal("0"),
        limits_winning_accounts=True,
        notes="Germany's largest sportsbook. 5.3% turnover tax. Limits sharps.",
    ),
    "codere_it": VenueExecutionProfile(
        venue_key="codere_it",
        odds_api_key="codere_it",
        display_name="Codere (Italy)",
        parent_company="Codere Group",
        venue_category=VenueCategory.SCRAPER,
        primary_execution_method=ExecutionMethod.BROWSER_AUTOMATION,
        credential_type=CredentialType.USERNAME_PASSWORD,
        login_url="https://www.codere.it/scommesse",
        config_secret_field="codere_it_credentials",
        username_secret_key="username",
        password_secret_key="password",
        headquarters_country="ES",
        license_jurisdictions=["IT-ADM"],
        available_countries=["IT"],
        requires_residency=True,
        residency_countries=["IT"],
        supported_currencies=["EUR"],
        min_bet=Decimal("1"),
        min_bet_currency="EUR",
        anti_detection_level=AntiDetectionLevel.BASIC,
        commission_model="built_into_odds",
        withdrawal_fee=Decimal("0"),
        notes="Spanish-owned, Italian-licensed. Retail + online.",
    ),
    # ── Sweden ───────────────────────────────────────────────────────────
    "svenskaspel_se": VenueExecutionProfile(
        venue_key="svenskaspel_se",
        odds_api_key="svenskaspel_se",
        display_name="Svenska Spel",
        parent_company="Svenska Spel AB (Swedish state)",
        venue_category=VenueCategory.SCRAPER,
        primary_execution_method=ExecutionMethod.BROWSER_AUTOMATION,
        credential_type=CredentialType.USERNAME_PASSWORD,
        login_url="https://www.svenskaspel.se/odds",
        config_secret_field="svenskaspel_se_credentials",
        username_secret_key="username",
        password_secret_key="password",
        headquarters_country="SE",
        license_jurisdictions=["SE-SGA"],
        available_countries=["SE"],
        requires_residency=True,
        residency_countries=["SE"],
        supported_currencies=["SEK"],
        min_bet=Decimal("1"),
        min_bet_currency="SEK",
        anti_detection_level=AntiDetectionLevel.BASIC,
        commission_model="built_into_odds",
        withdrawal_fee=Decimal("0"),
        notes="Swedish state gambling monopoly. BankID login required.",
    ),
    "atg_se": VenueExecutionProfile(
        venue_key="atg_se",
        odds_api_key="atg_se",
        display_name="ATG (Sweden)",
        parent_company="AB Trav och Galopp",
        venue_category=VenueCategory.SCRAPER,
        primary_execution_method=ExecutionMethod.BROWSER_AUTOMATION,
        credential_type=CredentialType.USERNAME_PASSWORD,
        login_url="https://www.atg.se/sport",
        config_secret_field="atg_se_credentials",
        username_secret_key="username",
        password_secret_key="password",
        headquarters_country="SE",
        license_jurisdictions=["SE-SGA"],
        available_countries=["SE"],
        requires_residency=True,
        residency_countries=["SE"],
        supported_currencies=["SEK"],
        min_bet=Decimal("1"),
        min_bet_currency="SEK",
        anti_detection_level=AntiDetectionLevel.BASIC,
        commission_model="built_into_odds",
        withdrawal_fee=Decimal("0"),
        notes="Swedish horse racing monopoly. Also offers sports betting.",
    ),
    "sport888_se": VenueExecutionProfile(
        venue_key="sport888_se",
        odds_api_key="sport888_se",
        display_name="888sport (Sweden)",
        parent_company="888 Holdings",
        venue_category=VenueCategory.SCRAPER,
        primary_execution_method=ExecutionMethod.BROWSER_AUTOMATION,
        credential_type=CredentialType.USERNAME_PASSWORD,
        login_url="https://www.888sport.se/",
        config_secret_field="sport888_se_credentials",
        username_secret_key="username",
        password_secret_key="password",
        headquarters_country="GI",
        license_jurisdictions=["SE-SGA"],
        available_countries=["SE"],
        supported_currencies=["SEK"],
        min_bet=Decimal("10"),
        min_bet_currency="SEK",
        anti_detection_level=AntiDetectionLevel.BASIC,
        commission_model="built_into_odds",
        withdrawal_fee=Decimal("0"),
        limits_winning_accounts=True,
        notes="888 Holdings Swedish market. SGA-licensed.",
    ),
    "mrgreen_se": VenueExecutionProfile(
        venue_key="mrgreen_se",
        odds_api_key="mrgreen_se",
        display_name="Mr Green (Sweden)",
        parent_company="William Hill (888 Holdings)",
        venue_category=VenueCategory.SCRAPER,
        primary_execution_method=ExecutionMethod.BROWSER_AUTOMATION,
        credential_type=CredentialType.USERNAME_PASSWORD,
        login_url="https://www.mrgreen.se/sport",
        config_secret_field="mrgreen_se_credentials",
        username_secret_key="username",
        password_secret_key="password",
        headquarters_country="MT",
        license_jurisdictions=["SE-SGA", "MT-MGA"],
        available_countries=["SE"],
        supported_currencies=["SEK"],
        min_bet=Decimal("10"),
        min_bet_currency="SEK",
        anti_detection_level=AntiDetectionLevel.BASIC,
        commission_model="built_into_odds",
        withdrawal_fee=Decimal("0"),
        notes="888/WH subsidiary. Swedish sportsbook.",
    ),
    # ── Australia Additional ─────────────────────────────────────────────
    "bet365_au": VenueExecutionProfile(
        venue_key="bet365_au",
        odds_api_key="bet365_au",
        display_name="bet365 (Australia)",
        parent_company="bet365 Group",
        venue_category=VenueCategory.SCRAPER,
        primary_execution_method=ExecutionMethod.BROWSER_AUTOMATION,
        credential_type=CredentialType.USERNAME_PASSWORD,
        login_url="https://www.bet365.com.au/",
        config_secret_field="bet365_au_credentials",
        username_secret_key="username",
        password_secret_key="password",
        headquarters_country="GB",
        license_jurisdictions=["AU-NT"],
        available_countries=["AU"],
        requires_residency=True,
        residency_countries=["AU"],
        supported_currencies=["AUD"],
        min_bet=Decimal("1"),
        min_bet_currency="AUD",
        withdrawal_delay_hours_min=24,
        withdrawal_delay_hours_max=72,
        anti_detection_level=AntiDetectionLevel.AGGRESSIVE,
        known_waf="cloudflare",
        requires_captcha=True,
        captcha_type="hcaptcha",
        commission_model="built_into_odds",
        withdrawal_fee=Decimal("0"),
        limits_winning_accounts=True,
        account_limiting_severity="aggressive",
        notes="bet365 AU. Aggressive anti-bot + account limiting. Hardest to automate.",
    ),
    "dabble_au": VenueExecutionProfile(
        venue_key="dabble_au",
        odds_api_key="dabble_au",
        display_name="Dabble (Australia)",
        parent_company="Dabble Pty Ltd",
        venue_category=VenueCategory.SCRAPER,
        primary_execution_method=ExecutionMethod.BROWSER_AUTOMATION,
        credential_type=CredentialType.USERNAME_PASSWORD,
        login_url="https://www.dabble.com.au/",
        config_secret_field="dabble_au_credentials",
        username_secret_key="username",
        password_secret_key="password",
        headquarters_country="AU",
        license_jurisdictions=["AU-NT"],
        available_countries=["AU"],
        requires_residency=True,
        residency_countries=["AU"],
        supported_currencies=["AUD"],
        min_bet=Decimal("1"),
        min_bet_currency="AUD",
        anti_detection_level=AntiDetectionLevel.BASIC,
        commission_model="built_into_odds",
        withdrawal_fee=Decimal("0"),
        notes="Australian social betting app. Newer entrant.",
    ),
}
