/**
 * DeFi widget domain types — aligned with backend (UAC + execution-service).
 *
 * SSOT for enums/venues/instruments: lib/registry/ui-reference-data.json
 * (generated by unified-trading-pm/scripts/openapi/generate-unified-openapi.sh)
 *
 * The constants below are convenience copies for TypeScript type safety.
 * They MUST stay in sync with ui-reference-data.json. Run the OpenAPI sync
 * script after backend changes to regenerate.
 *
 * Mock-backed until API wiring. All IDs, enums, and field names match the
 * real backend so switching from mock → API is a data-source swap, not a rewrite.
 */

// ---------------------------------------------------------------------------
// Share Class (base currency denomination — matches UAC ShareClass enum)
// ---------------------------------------------------------------------------

/** Base currency in which strategy P&L and risk is denominated. */
export const SHARE_CLASSES = ["USDT", "ETH", "BTC"] as const;
export type ShareClass = (typeof SHARE_CLASSES)[number];

/** Human-readable labels for share class display. */
export const SHARE_CLASS_LABELS: Record<ShareClass, string> = {
  USDT: "USDT (Stablecoin)",
  ETH: "ETH (Ethereum)",
  BTC: "BTC (Bitcoin)",
};

// ---------------------------------------------------------------------------
// Strategy IDs (match strategy-service factory keys)
// ---------------------------------------------------------------------------

export const DEFI_STRATEGY_IDS = [
  "AAVE_LENDING",
  "BASIS_TRADE",
  "STAKED_BASIS",
  "RECURSIVE_STAKED_BASIS",
  "UNHEDGED_RECURSIVE",
  "USDT_HEDGED_RECURSIVE",
  "ETH_LENDING",
  "BTC_BASIS",
  "SOL_BASIS",
  "L2_BASIS",
  "MULTICHAIN_LENDING",
  "CROSS_CHAIN_YIELD_ARB",
  "CROSS_CHAIN_SOR",
  "ACTIVE_LP",
  "PASSIVE_LP",
  "LIQUIDATION_CAPTURE",
] as const;

/**
 * Benchmark references — NOT deployable strategies. Used as comparison anchors
 * in yield / P&L widgets. Codex (`ethena-benchmark.md`) classifies Ethena sUSDe
 * as a benchmark reference, not a runtime strategy instance.
 */
export const BENCHMARK_IDS = ["ETHENA_BENCHMARK"] as const;
export type Benchmark = (typeof BENCHMARK_IDS)[number];

export const BENCHMARK_DISPLAY_NAMES: Record<Benchmark, string> = {
  ETHENA_BENCHMARK: "Ethena sUSDe Benchmark",
};

export type DeFiStrategyId = (typeof DEFI_STRATEGY_IDS)[number];

export function asDeFiStrategyId(id: string | undefined): DeFiStrategyId | undefined {
  return id && (DEFI_STRATEGY_IDS as readonly string[]).includes(id) ? (id as DeFiStrategyId) : undefined;
}

// ---------------------------------------------------------------------------
// Strategy slot-label — canonical strategy_id shape
// ---------------------------------------------------------------------------

/**
 * Launch-stage enum for strategy instances.
 * SSOT: unified-trading-pm/codex/09-strategy/architecture-v2/category-instrument-coverage.md
 * (§ Slot label grammar — order is shadow → uat → paper → prod).
 */
export const STRATEGY_ENVS = ["shadow", "uat", "paper", "prod"] as const;
export type StrategyEnv = (typeof STRATEGY_ENVS)[number];

/**
 * Parsed form of a strategy slot-label.
 * Grammar: `{ARCHETYPE}@{slot}-{env}` (e.g. `YIELD_STAKING_SIMPLE@lido-steth-ethereum-eth-prod`).
 */
export interface ParsedSlotLabel {
  readonly archetype: string;
  readonly slot: string;
  readonly env: StrategyEnv;
  readonly raw: string;
}

/**
 * Parse a slot-label. Returns undefined if the input does not match the
 * `{ARCHETYPE}@{slot}-{env}` grammar (e.g. legacy venue-id literals).
 */
export function parseSlotLabel(input: string | undefined): ParsedSlotLabel | undefined {
  if (!input) return undefined;
  const atIdx = input.indexOf("@");
  if (atIdx <= 0 || atIdx === input.length - 1) return undefined;
  const archetype = input.slice(0, atIdx);
  const rest = input.slice(atIdx + 1);
  const lastDash = rest.lastIndexOf("-");
  if (lastDash <= 0) return undefined;
  const envCandidate = rest.slice(lastDash + 1);
  if (!(STRATEGY_ENVS as readonly string[]).includes(envCandidate)) return undefined;
  const slot = rest.slice(0, lastDash);
  if (!slot) return undefined;
  return { archetype, slot, env: envCandidate as StrategyEnv, raw: input };
}

/** Round-trip inverse of `parseSlotLabel`. */
export function formatSlotLabel(parts: { archetype: string; slot: string; env: StrategyEnv }): string {
  return `${parts.archetype}@${parts.slot}-${parts.env}`;
}

/** Type guard — whether the input matches the slot-label grammar. */
export function isSlotLabel(input: string | undefined): boolean {
  return parseSlotLabel(input) !== undefined;
}

/**
 * Reference to a strategy instance carried by widget order emissions.
 *
 * Accepts both the canonical slot-label (`{ARCHETYPE}@{slot}-{env}`) and the
 * legacy venue-id literals in `DeFiStrategyId` during the transition — the
 * backend strategy-service factory resolves either form.
 */
export type StrategyInstanceRef = string;

/** Human-readable display names for strategies. */
export const STRATEGY_DISPLAY_NAMES: Record<DeFiStrategyId, string> = {
  AAVE_LENDING: "AAVE Lending",
  BASIS_TRADE: "Multi-Venue Basis Trade",
  STAKED_BASIS: "Staked Basis (weETH)",
  RECURSIVE_STAKED_BASIS: "Recursive Staked Basis (Hedged)",
  UNHEDGED_RECURSIVE: "Recursive Staked Basis (Unhedged)",
  USDT_HEDGED_RECURSIVE: "USDT Hedged Recursive",
  ETH_LENDING: "ETH Lending",
  BTC_BASIS: "BTC Basis Trade",
  SOL_BASIS: "SOL Basis Trade",
  L2_BASIS: "L2 Basis Trade",
  MULTICHAIN_LENDING: "Multi-Chain Lending",
  CROSS_CHAIN_YIELD_ARB: "Cross-Chain Yield Arb",
  CROSS_CHAIN_SOR: "Cross-Chain SOR",
  ACTIVE_LP: "Active LP (Uniswap V3)",
  PASSIVE_LP: "Passive LP (Curve / Balancer / Uniswap V2)",
  LIQUIDATION_CAPTURE: "Liquidation Capture",
};

// ---------------------------------------------------------------------------
// Instruction Types (match backend OperationType enum)
// ---------------------------------------------------------------------------

/**
 * Operation types — from UAC OperationType enum (ui-reference-data.json → uac_enums.OperationType).
 * These are the DeFi-relevant subset. Full list includes BUY/SELL for CeFi.
 */
export const OPERATION_TYPES = [
  // From UAC OperationType enum
  "SWAP",
  "LEND",
  "BORROW",
  "REPAY",
  "WITHDRAW",
  "DEPOSIT",
  "REBALANCE",
  "ADD_LIQUIDITY",
  "REMOVE_LIQUIDITY",
  "COLLECT_FEES",
  // DeFi-specific extensions (in strategy-service, not yet in UAC enum)
  "TRANSFER",
  "TRADE", // CeFi perp trade (maps to InstructionType.TRADE)
  "STAKE",
  "UNSTAKE",
  "FLASH_BORROW",
  "FLASH_REPAY",
] as const;

export type OperationType = (typeof OPERATION_TYPES)[number];

// Backward compat alias
export const INSTRUCTION_TYPES = OPERATION_TYPES;
export type InstructionType = OperationType;

// ---------------------------------------------------------------------------
// Algo per Instruction Type (execution-service algo_library)
// ---------------------------------------------------------------------------

export const ALGO_TYPES = [
  "SOR_DEX",
  "SOR_TWAP",
  "SOR_CROSS_CHAIN",
  "BENCHMARK_FILL",
  "DIRECT_MARKET",
  "DIRECT",
  "FLASH_LOAN_MORPHO",
  "FLASH_LOAN_AAVE",
  "AMM_CONCENTRATED",
] as const;

export type AlgoType = (typeof ALGO_TYPES)[number];

/** Which algos are available for each instruction type. */
export const INSTRUCTION_ALGO_MAP: Record<InstructionType, AlgoType[]> = {
  TRANSFER: ["DIRECT"],
  SWAP: ["SOR_DEX", "SOR_TWAP", "SOR_CROSS_CHAIN"],
  LEND: ["BENCHMARK_FILL", "DIRECT_MARKET"],
  BORROW: ["BENCHMARK_FILL", "DIRECT_MARKET"],
  WITHDRAW: ["BENCHMARK_FILL", "DIRECT_MARKET"],
  REPAY: ["BENCHMARK_FILL", "DIRECT_MARKET"],
  TRADE: ["DIRECT_MARKET", "SOR_DEX"],
  STAKE: ["BENCHMARK_FILL", "DIRECT_MARKET"],
  UNSTAKE: ["BENCHMARK_FILL", "DIRECT_MARKET"],
  FLASH_BORROW: ["FLASH_LOAN_MORPHO", "FLASH_LOAN_AAVE"],
  FLASH_REPAY: ["FLASH_LOAN_MORPHO", "FLASH_LOAN_AAVE"],
  DEPOSIT: ["BENCHMARK_FILL", "DIRECT_MARKET"],
  REBALANCE: ["AMM_CONCENTRATED"],
  ADD_LIQUIDITY: ["AMM_CONCENTRATED", "DIRECT_MARKET"],
  REMOVE_LIQUIDITY: ["AMM_CONCENTRATED", "DIRECT_MARKET"],
  COLLECT_FEES: ["DIRECT"],
};

// ---------------------------------------------------------------------------
// Canonical Venues (match UAC VenueMapping + CANONICAL_VENUE_TO_ADAPTER)
// ---------------------------------------------------------------------------

export const DEFI_VENUES = [
  // EVM DeFi
  "AAVEV3-ETHEREUM",
  "AAVEV3-ARBITRUM",
  "AAVEV3-BASE",
  "AAVEV3-OPTIMISM",
  "AAVEV3-POLYGON",
  "UNISWAPV3-ETHEREUM",
  "UNISWAPV3-ARBITRUM",
  "UNISWAPV3-BASE",
  "UNISWAPV4-ETHEREUM",
  "CURVE-ETHEREUM",
  "BALANCER-ETHEREUM",
  "BALANCER-ARBITRUM",
  "MORPHO-ETHEREUM",
  "ETHENA-ETHEREUM",
  "ETHERFI-ETHEREUM",
  "LIDO-ETHEREUM",
  // CeFi perp venues
  "HYPERLIQUID",
  "BINANCE-FUTURES",
  "OKX",
  "BYBIT",
  "ASTER",
  // Solana DeFi
  "ORCA-SOLANA",
  "RAYDIUM-SOLANA",
  "KAMINO-SOLANA",
  "DRIFT-SOLANA",
  "MARINADE-SOLANA",
] as const;

export type DeFiVenue = (typeof DEFI_VENUES)[number];

// ---------------------------------------------------------------------------
// Strategy Instruction (matches backend StrategyInstruction)
// ---------------------------------------------------------------------------

export interface StrategyInstruction {
  instruction_id: string;
  strategy_id: StrategyInstanceRef;
  timestamp: string;
  operation: InstructionType;
  algo_type: AlgoType;
  instrument_id: string; // canonical: "AAVEV3-ETHEREUM:A_TOKEN:AUSDC@ETHEREUM"
  from_venue: string;
  to_venue: string;
  token_in: string;
  token_out?: string;
  amount: number;
  direction?: "LONG" | "SHORT";
  benchmark_price: number;
  max_slippage_bps: number;
  expected_output: number; // what strategy expects to receive
  is_atomic?: boolean;
  metadata?: Record<string, string>;
}

// ---------------------------------------------------------------------------
// Instant P&L (alpha decomposition per instruction)
// ---------------------------------------------------------------------------

export interface InstantPnL {
  /** Gross P&L before costs: actual_output - expected_output */
  gross_pnl: number;
  /** Price slippage vs benchmark */
  price_slippage_usd: number;
  /** Gas cost in USD */
  gas_cost_usd: number;
  /** Swap/trading fee */
  trading_fee_usd: number;
  /** Bridge fee (cross-chain only) */
  bridge_fee_usd: number;
  /** Net P&L after all costs */
  net_pnl: number;
  /** Was max_slippage_bps exceeded? */
  slippage_exceeded: boolean;
}

// ---------------------------------------------------------------------------
// Trade History (running totals)
// ---------------------------------------------------------------------------

export interface ExecutionStep {
  label: string;
  detail?: string;
  duration_ms?: number;
}

export interface TradeHistoryRow {
  seq: number;
  timestamp: string;
  instruction_type: InstructionType;
  algo_type: AlgoType;
  instrument_id: string;
  venue: string;
  amount: number;
  price: number;
  expected_output: number;
  actual_output: number;
  instant_pnl: InstantPnL;
  running_pnl: number;
  status: "pending" | "confirmed" | "filled" | "failed" | "reverted";
  tx_hash?: string;
  reference_price?: number;
  alpha_pnl_usd?: number;
  venue_fills?: VenueFill[];
  is_child_fill?: boolean;
  parent_seq?: number;
  strategy_id?: string;
  execution_chain?: ExecutionStep[];
}

// ---------------------------------------------------------------------------
// Risk Dimensions
// ---------------------------------------------------------------------------

export type RiskLevel = "low" | "medium" | "high" | "critical";

export interface StrategyRiskProfile {
  strategy_id: DeFiStrategyId;
  /** Mock/demo: synthetic Aave-style health factor for weighted portfolio HF */
  health_factor?: number;
  /** Smart contract / oracle / governance risk */
  protocol_risk: RiskLevel;
  /** Individual token price collapse exposure */
  coin_isolated_risk: RiskLevel;
  /** Spot vs perp price divergence (basis strategies) */
  basis_risk: RiskLevel;
  /** Funding rate going negative across venues */
  funding_rate_risk: RiskLevel;
  /** % drawdown to close ALL positions at once */
  liquidity_risk_pct: number;
  /** Qualitative description */
  risk_notes: string;
}

// ---------------------------------------------------------------------------
// Delta Neutrality
// ---------------------------------------------------------------------------

export interface DeltaExposure {
  strategy_id: DeFiStrategyId;
  /** What this strategy is supposed to be neutral to */
  neutral_to: string; // "USD" | "ETH" | "SOL" | "BTC"
  /** Current net delta per underlying */
  net_delta_usd: number;
  net_delta_eth: number;
  net_delta_sol: number;
  net_delta_btc: number;
  /** Deviation from target neutrality (0 = perfectly neutral) */
  delta_deviation_pct: number;
  /** Max acceptable deviation before rebalance */
  max_deviation_pct: number;
}

export interface PortfolioDeltaComposite {
  /** Aggregate across all strategies */
  total_delta_usd: number;
  total_delta_eth: number;
  total_delta_sol: number;
  total_delta_btc: number;
  /** Per-strategy breakdown */
  per_strategy: DeltaExposure[];
  /** Total liquidation cost as % of portfolio */
  total_liquidation_cost_pct: number;
}

// ---------------------------------------------------------------------------
// DeFi Reconciliation (on-chain vs system)
// ---------------------------------------------------------------------------

export interface DeFiReconciliationRecord {
  id: string;
  date: string;
  venue: DeFiVenue | string;
  instrument_id: string;
  break_type: "position" | "pnl" | "fee" | "gas" | "balance";
  /** What the chain/exchange reports */
  on_chain_value: number;
  /** What our system (position-balance-monitor) reports */
  system_value: number;
  /** Difference */
  delta: number;
  delta_pct: number;
  status: "pending" | "investigating" | "resolved" | "accepted";
  resolution?: "system_correct" | "chain_correct" | "adjusted";
}

// ---------------------------------------------------------------------------
// Rebalance
// ---------------------------------------------------------------------------

export interface RebalancePreview {
  treasury_current_pct: number;
  treasury_target_pct: number;
  treasury_balance_usd: number;
  total_aum_usd: number;
  action: "deploy" | "reduce"; // deploy = treasury high, reduce = treasury low
  /** Per-strategy proposed capital movement */
  allocations: RebalanceAllocation[];
  /** Total instructions that will be generated */
  total_instructions: number;
  estimated_gas_usd: number;
}

export interface RebalanceAllocation {
  strategy_id: DeFiStrategyId;
  current_balance_usd: number;
  proposed_change_usd: number; // positive = deploy more, negative = reduce
  instructions: StrategyInstruction[];
}

// ---------------------------------------------------------------------------
// Treasury
// ---------------------------------------------------------------------------

export interface ShareClassBreakdown {
  share_class: ShareClass;
  nav_usd: number;
  /** NAV denominated in the share class asset (e.g. ETH units for ETH share class) */
  nav_denominated: number;
  pct_of_total: number;
  strategies: string[];
  /** Target delta in share class terms (1.0 for fully crypto-denominated, 0 for stablecoin) */
  target_delta: number;
  actual_delta: number;
  unrealised_pnl_usd: number;
  unrealised_pnl_denominated: number;
}

export interface TreasurySnapshot {
  timestamp: string;
  chain: string;
  custodian: string;
  treasury_balance_usd: number;
  total_trading_balance_usd: number;
  total_aum_usd: number;
  treasury_pct: number;
  status: "normal" | "low" | "high";
  per_strategy_balance: Record<DeFiStrategyId, number>;
  per_token_balance: Record<string, number>;
  share_class_breakdown?: ShareClassBreakdown[];
}

// ---------------------------------------------------------------------------
// Existing types (aligned, kept for backward compat)
// ---------------------------------------------------------------------------

export interface LendingProtocol {
  name: string;
  venue_id: DeFiVenue | string;
  chain: string;
  assets: string[];
  supplyApy: Record<string, number>;
  borrowApy: Record<string, number>;
}

export interface VenueFill {
  venue: string;
  venue_display: string;
  allocation_pct: number;
  input_amount: number;
  fill_price: number;
  fill_qty: number;
  price_impact_bps: number;
  gas_usd: number;
  fee_bps: number;
}

export interface SwapRoute {
  path: string[];
  pools: string[];
  priceImpactPct: number;
  expectedOutput: number;
  gasEstimateEth: number;
  gasEstimateUsd: number;
  algo_type: AlgoType;
  /** Per-venue fill breakdown for SOR orders */
  venue_fills?: VenueFill[];
  /** Reference (mid) price at time of routing — used for alpha P&L */
  reference_price?: number;
}

export interface LiquidityPool {
  name: string;
  venue_id: DeFiVenue | string;
  token0: string;
  token1: string;
  feeTier: number;
  tvl: number;
  apr24h: number;
  tick_lower?: number;
  tick_upper?: number;
}

export interface StakingProtocol {
  name: string;
  venue_id: DeFiVenue | string;
  asset: string;
  apy: number;
  tvl: number;
  minStake: number;
  unbondingDays: number;
}

export interface FlashLoanStep {
  id: string;
  operationType: InstructionType;
  algo_type: AlgoType;
  asset: string;
  amount: string;
  venue: DeFiVenue | string;
  max_slippage_bps: number;
}

export interface DeFiFlashPnl {
  grossProfit: number;
  flashFee: number;
  gasEstimate: number;
  netPnl: number;
}

/** Params passed to execution (maps to backend StrategyInstruction). */
export interface DeFiOrderParams {
  client_id: string;
  strategy_id: StrategyInstanceRef;
  instruction_type: InstructionType;
  algo_type: AlgoType;
  instrument_id: string;
  venue: DeFiVenue | string;
  side: "buy" | "sell";
  order_type: "market" | "limit";
  quantity: number;
  price: number;
  max_slippage_bps: number;
  expected_output: number;
  benchmark_price: number;
  asset_class: "DeFi";
  lane: "defi";
  is_atomic?: boolean;
}

/** Bridge route quote from a single protocol. */
export interface BridgeRouteQuote {
  protocol: string;
  feePct: number;
  feeUsd: number;
  estimatedTimeMin: number;
  outputAmount: number;
  isBestReturn: boolean;
  isFastest: boolean;
}

/** Per-chain portfolio breakdown for wallet summary. */
export interface ChainPortfolio {
  chain: string;
  totalUsd: number;
  tokenBreakdown: Record<string, number>;
  gasTokenBalance: number;
  gasTokenSymbol: string;
}

export interface DeFiRatesRow {
  id: string;
  protocol: string;
  venue_id: DeFiVenue | string;
  category: "Lending supply" | "Lending borrow" | "Staking" | "LP";
  detail: string;
  apyPct: number;
  tvlUsd: number;
}

// ---------------------------------------------------------------------------
// Staking Rewards (reward lifecycle tracking)
// ---------------------------------------------------------------------------

export interface StakingReward {
  token: string;
  accrued_amount: number;
  accrued_value_usd: number;
  claimed_amount: number;
  sold_amount: number;
  sold_value_usd: number;
  next_payout: string;
  frequency: "WEEKLY" | "MONTHLY" | "QUARTERLY";
}

// ---------------------------------------------------------------------------
// Funding Rate Matrix (per-coin-per-venue)
// ---------------------------------------------------------------------------

export type FundingRateMatrix = Record<string, Record<string, number | null>>;

// ---------------------------------------------------------------------------
// Two-Waterfall Allocation Weights
// ---------------------------------------------------------------------------

export interface WaterfallWeights {
  coin_weights: Record<string, number>;
  venue_weights: Record<string, Record<string, number>>;
  restricted_venues: string[];
}

// ---------------------------------------------------------------------------
// Health Factor Dashboard
// ---------------------------------------------------------------------------

export interface HealthFactorDashboard {
  current_hf: number;
  liquidation_at: number;
  warning_at: number;
  buffer_pct: number;
  /**
   * LST ticker or asset symbol rendered alongside the oracle/market rows.
   * Examples: "weETH", "wstETH", "JitoSOL", "WBTC". Widgets render labels
   * as `${collateral_token} oracle rate` etc. — do not hardcode per-asset.
   */
  collateral_token: string;
  collateral_oracle_rate: number;
  collateral_market_rate: number;
  oracle_market_gap_pct: number;
  borrow_rate_pct: number;
  staking_rate_pct: number;
  net_spread_pct: number;
  leverage: number;
  leveraged_spread_pct: number;
  monitoring_interval: string;
  /**
   * Prose for the Emergency Exit dialog description. Archetype-specific so
   * the widget can render across recursive-staked / lending / staked-basis
   * without fork. Example: "unwind the recursive staking position".
   */
  emergency_exit_description: string;
}

// ---------------------------------------------------------------------------
// Emergency Exit
// ---------------------------------------------------------------------------

export interface EmergencyExitEstimate {
  estimated_gas_usd: number;
  estimated_slippage_usd: number;
  estimated_exchange_fees_usd: number;
  total_cost_usd: number;
  total_as_pct_of_nav: number;
  estimated_time_minutes: number;
  steps: string[];
}

// ---------------------------------------------------------------------------
// Reward P&L Breakdown
// ---------------------------------------------------------------------------

/**
 * One row of a strategy-instance P&L decomposition.
 *
 * `key` is the canonical factor identifier (e.g. `staking_yield`, `funding`,
 * `basis_spread`) and drives the colour palette lookup in the widget. `label`
 * is the human-readable string rendered verbatim. `amount` is USD.
 *
 * Factor sets are archetype-specific and supplied as instance metadata —
 * widgets do not hardcode factor keys. Staking archetypes decompose into
 * `staking_yield / restaking_reward / seasonal_reward / reward_unrealised`;
 * basis archetypes into `funding / basis_spread / trading / fees / exec_alpha`;
 * lending into `supply_apy / incentive_rewards / fee_earnings`; etc.
 */
export interface RewardPnLFactor {
  key: string;
  label: string;
  amount: number;
}

/**
 * Ordered list of reward / P&L factors for a single strategy instance.
 * The ordering is meaningful — widgets render waterfall bars in list order.
 */
export type RewardPnLBreakdown = RewardPnLFactor[];

// ---------------------------------------------------------------------------
// Basis Trade
// ---------------------------------------------------------------------------

export interface BasisTradeMarketData {
  spotPrice: number;
  perpPrice: number;
  fundingRate: number;
  fundingRateAnnualized: number;
  basis24h: number;
  basisBps: number;
  volume24h: number;
  slippage: number;
}

export interface BasisTradeHistoryEntry {
  seq: number;
  timestamp: string;
  operation: "SWAP" | "TRADE" | "BOTH";
  asset: string;
  amount: number;
  expectedOutput: number;
  actualOutput: number;
  slippage: number;
  marginUsage: number;
  fundingRate: number;
  fundingPnL: number;
  basisBps: number;
  status: "pending" | "filled" | "failed";
  runningPnL: number;
}
