"""Venue execution registry — international (non-US) scraper bookmakers."""

from __future__ import annotations

from .venue_execution import (
    AntiDetectionLevel,
    CredentialType,
    ExecutionMethod,
    VenueCategory,
    VenueExecutionProfile,
)

INTL_SCRAPER_REGISTRY: dict[str, VenueExecutionProfile] = {
    # ── EU / Offshore Scrapers ───────────────────────────────────────────
    "onexbet": VenueExecutionProfile(
        venue_key="onexbet",
        odds_api_key="onexbet",
        display_name="1xBet",
        venue_category=VenueCategory.SCRAPER,
        primary_execution_method=ExecutionMethod.BROWSER_AUTOMATION,
        credential_type=CredentialType.USERNAME_PASSWORD,
        login_url="https://1xbet.com",
        config_secret_field="onexbet_credentials",
        username_secret_key="username",
        password_secret_key="password",
        commission_model="built_into_odds",
        min_bet="0.20",
        min_bet_currency="EUR",
        withdrawal_fee="0",
    ),
    "unibet_uk": VenueExecutionProfile(
        venue_key="unibet_uk",
        odds_api_key="unibet_uk",
        display_name="Unibet UK",
        venue_category=VenueCategory.SCRAPER,
        primary_execution_method=ExecutionMethod.BROWSER_AUTOMATION,
        credential_type=CredentialType.USERNAME_PASSWORD,
        login_url="https://www.unibet.com",
        config_secret_field="unibet_uk_credentials",
        username_secret_key="username",
        password_secret_key="password",
        commission_model="built_into_odds",
        min_bet="0.10",
        min_bet_currency="GBP",
        withdrawal_fee="0",
    ),
    "unibet_fr": VenueExecutionProfile(
        venue_key="unibet_fr",
        odds_api_key="unibet_fr",
        display_name="Unibet FR",
        venue_category=VenueCategory.SCRAPER,
        primary_execution_method=ExecutionMethod.BROWSER_AUTOMATION,
        credential_type=CredentialType.USERNAME_PASSWORD,
        login_url="https://www.unibet.com",
        config_secret_field="unibet_fr_credentials",
        username_secret_key="username",
        password_secret_key="password",
        commission_model="built_into_odds",
        min_bet="0.10",
        min_bet_currency="EUR",
        withdrawal_fee="0",
    ),
    "unibet_it": VenueExecutionProfile(
        venue_key="unibet_it",
        odds_api_key="unibet_it",
        display_name="Unibet IT",
        venue_category=VenueCategory.SCRAPER,
        primary_execution_method=ExecutionMethod.BROWSER_AUTOMATION,
        credential_type=CredentialType.USERNAME_PASSWORD,
        login_url="https://www.unibet.com",
        config_secret_field="unibet_it_credentials",
        username_secret_key="username",
        password_secret_key="password",
        commission_model="built_into_odds",
        min_bet="0.10",
        min_bet_currency="EUR",
        withdrawal_fee="0",
    ),
    "unibet_nl": VenueExecutionProfile(
        venue_key="unibet_nl",
        odds_api_key="unibet_nl",
        display_name="Unibet NL",
        venue_category=VenueCategory.SCRAPER,
        primary_execution_method=ExecutionMethod.BROWSER_AUTOMATION,
        credential_type=CredentialType.USERNAME_PASSWORD,
        login_url="https://www.unibet.com",
        config_secret_field="unibet_nl_credentials",
        username_secret_key="username",
        password_secret_key="password",
        commission_model="built_into_odds",
        min_bet="0.10",
        min_bet_currency="EUR",
        withdrawal_fee="0",
    ),
    "unibet_se": VenueExecutionProfile(
        venue_key="unibet_se",
        odds_api_key="unibet_se",
        display_name="Unibet SE",
        venue_category=VenueCategory.SCRAPER,
        primary_execution_method=ExecutionMethod.BROWSER_AUTOMATION,
        credential_type=CredentialType.USERNAME_PASSWORD,
        login_url="https://www.unibet.com",
        config_secret_field="unibet_se_credentials",
        username_secret_key="username",
        password_secret_key="password",
        commission_model="built_into_odds",
        min_bet="0.10",
        min_bet_currency="EUR",
        withdrawal_fee="0",
    ),
    "betsson": VenueExecutionProfile(
        venue_key="betsson",
        odds_api_key="betsson",
        display_name="Betsson",
        venue_category=VenueCategory.SCRAPER,
        primary_execution_method=ExecutionMethod.BROWSER_AUTOMATION,
        credential_type=CredentialType.USERNAME_PASSWORD,
        login_url="https://www.betsson.com",
        config_secret_field="betsson_credentials",
        username_secret_key="username",
        password_secret_key="password",
        commission_model="built_into_odds",
        min_bet="0.10",
        min_bet_currency="EUR",
        withdrawal_fee="0",
    ),
    "marathonbet": VenueExecutionProfile(
        venue_key="marathonbet",
        odds_api_key="marathonbet",
        display_name="Marathonbet",
        venue_category=VenueCategory.SCRAPER,
        primary_execution_method=ExecutionMethod.BROWSER_AUTOMATION,
        credential_type=CredentialType.USERNAME_PASSWORD,
        login_url="https://www.marathonbet.com",
        config_secret_field="marathonbet_credentials",
        username_secret_key="username",
        password_secret_key="password",
        commission_model="built_into_odds",
        min_bet="0.10",
        min_bet_currency="EUR",
        withdrawal_fee="0",
    ),
    "coolbet": VenueExecutionProfile(
        venue_key="coolbet",
        odds_api_key="coolbet",
        display_name="Coolbet",
        venue_category=VenueCategory.SCRAPER,
        primary_execution_method=ExecutionMethod.BROWSER_AUTOMATION,
        credential_type=CredentialType.USERNAME_PASSWORD,
        login_url="https://www.coolbet.com",
        config_secret_field="coolbet_credentials",
        username_secret_key="username",
        password_secret_key="password",
        commission_model="built_into_odds",
        min_bet="0.10",
        min_bet_currency="EUR",
        withdrawal_fee="0",
    ),
    "nordicbet": VenueExecutionProfile(
        venue_key="nordicbet",
        odds_api_key="nordicbet",
        display_name="NordicBet",
        venue_category=VenueCategory.SCRAPER,
        primary_execution_method=ExecutionMethod.BROWSER_AUTOMATION,
        credential_type=CredentialType.USERNAME_PASSWORD,
        login_url="https://www.nordicbet.com",
        config_secret_field="nordicbet_credentials",
        username_secret_key="username",
        password_secret_key="password",
        commission_model="built_into_odds",
        min_bet="0.10",
        min_bet_currency="EUR",
        withdrawal_fee="0",
    ),
    # ── Offshore / Crypto-friendly ───────────────────────────────────────
    "bovada": VenueExecutionProfile(
        venue_key="bovada",
        odds_api_key="bovada",
        display_name="Bovada",
        venue_category=VenueCategory.SCRAPER,
        primary_execution_method=ExecutionMethod.BROWSER_AUTOMATION,
        credential_type=CredentialType.USERNAME_PASSWORD,
        login_url="https://www.bovada.lv",
        config_secret_field="bovada_credentials",
        username_secret_key="username",
        password_secret_key="password",
        supports_crypto_withdrawal=True,
        commission_model="built_into_odds",
        min_bet="1",
        min_bet_currency="USD",
        withdrawal_fee="0",
    ),
    "betonlineag": VenueExecutionProfile(
        venue_key="betonlineag",
        odds_api_key="betonlineag",
        display_name="BetOnline",
        venue_category=VenueCategory.SCRAPER,
        primary_execution_method=ExecutionMethod.BROWSER_AUTOMATION,
        credential_type=CredentialType.USERNAME_PASSWORD,
        login_url="https://www.betonline.ag",
        config_secret_field="betonlineag_credentials",
        username_secret_key="username",
        password_secret_key="password",
        supports_crypto_withdrawal=True,
        commission_model="built_into_odds",
        min_bet="1",
        min_bet_currency="USD",
        withdrawal_fee="0",
    ),
    "mybookieag": VenueExecutionProfile(
        venue_key="mybookieag",
        odds_api_key="mybookieag",
        display_name="MyBookie",
        venue_category=VenueCategory.SCRAPER,
        primary_execution_method=ExecutionMethod.BROWSER_AUTOMATION,
        credential_type=CredentialType.USERNAME_PASSWORD,
        login_url="https://www.mybookie.ag",
        config_secret_field="mybookieag_credentials",
        username_secret_key="username",
        password_secret_key="password",
        supports_crypto_withdrawal=True,
        commission_model="built_into_odds",
        min_bet="5",
        min_bet_currency="USD",
        withdrawal_fee="0",
    ),
    "betus": VenueExecutionProfile(
        venue_key="betus",
        odds_api_key="betus",
        display_name="BetUS",
        venue_category=VenueCategory.SCRAPER,
        primary_execution_method=ExecutionMethod.BROWSER_AUTOMATION,
        credential_type=CredentialType.USERNAME_PASSWORD,
        login_url="https://www.betus.com.pa",
        config_secret_field="betus_credentials",
        username_secret_key="username",
        password_secret_key="password",
        supports_crypto_withdrawal=True,
        commission_model="built_into_odds",
        min_bet="1",
        min_bet_currency="USD",
        withdrawal_fee="0",
    ),
    # ── Australia Scrapers ───────────────────────────────────────────────
    "sportsbet": VenueExecutionProfile(
        venue_key="sportsbet",
        odds_api_key="sportsbet",
        display_name="Sportsbet",
        venue_category=VenueCategory.SCRAPER,
        primary_execution_method=ExecutionMethod.BROWSER_AUTOMATION,
        credential_type=CredentialType.USERNAME_PASSWORD,
        login_url="https://www.sportsbet.com.au",
        config_secret_field="sportsbet_credentials",
        username_secret_key="username",
        password_secret_key="password",
        available_countries=["AU"],
        commission_model="built_into_odds",
        min_bet="1",
        min_bet_currency="AUD",
        withdrawal_fee="0",
    ),
    "tab": VenueExecutionProfile(
        venue_key="tab",
        odds_api_key="tab",
        display_name="TAB",
        venue_category=VenueCategory.SCRAPER,
        primary_execution_method=ExecutionMethod.BROWSER_AUTOMATION,
        credential_type=CredentialType.USERNAME_PASSWORD,
        login_url="https://www.tab.com.au",
        config_secret_field="tab_credentials",
        username_secret_key="username",
        password_secret_key="password",
        available_countries=["AU"],
        commission_model="built_into_odds",
        min_bet="1",
        min_bet_currency="AUD",
        withdrawal_fee="0",
    ),
    "neds": VenueExecutionProfile(
        venue_key="neds",
        odds_api_key="neds",
        display_name="Neds",
        venue_category=VenueCategory.SCRAPER,
        primary_execution_method=ExecutionMethod.BROWSER_AUTOMATION,
        credential_type=CredentialType.USERNAME_PASSWORD,
        login_url="https://www.neds.com.au",
        config_secret_field="neds_credentials",
        username_secret_key="username",
        password_secret_key="password",
        available_countries=["AU"],
        commission_model="built_into_odds",
        min_bet="1",
        min_bet_currency="AUD",
        withdrawal_fee="0",
    ),
    "pointsbetau": VenueExecutionProfile(
        venue_key="pointsbetau",
        odds_api_key="pointsbetau",
        display_name="PointsBet AU",
        venue_category=VenueCategory.SCRAPER,
        primary_execution_method=ExecutionMethod.BROWSER_AUTOMATION,
        credential_type=CredentialType.USERNAME_PASSWORD,
        login_url="https://www.pointsbet.com.au",
        config_secret_field="pointsbetau_credentials",
        username_secret_key="username",
        password_secret_key="password",
        available_countries=["AU"],
        commission_model="built_into_odds",
        min_bet="1",
        min_bet_currency="AUD",
        withdrawal_fee="0",
    ),
    "ladbrokes_au": VenueExecutionProfile(
        venue_key="ladbrokes_au",
        odds_api_key="ladbrokes_au",
        display_name="Ladbrokes AU",
        venue_category=VenueCategory.SCRAPER,
        primary_execution_method=ExecutionMethod.BROWSER_AUTOMATION,
        credential_type=CredentialType.USERNAME_PASSWORD,
        login_url="https://www.ladbrokes.com.au",
        config_secret_field="ladbrokes_au_credentials",
        username_secret_key="username",
        password_secret_key="password",
        available_countries=["AU"],
        commission_model="built_into_odds",
        min_bet="1",
        min_bet_currency="AUD",
        withdrawal_fee="0",
    ),
    "betr_au": VenueExecutionProfile(
        venue_key="betr_au",
        odds_api_key="betr_au",
        display_name="Betr AU",
        venue_category=VenueCategory.SCRAPER,
        primary_execution_method=ExecutionMethod.BROWSER_AUTOMATION,
        credential_type=CredentialType.USERNAME_PASSWORD,
        login_url="https://www.betr.com.au",
        config_secret_field="betr_au_credentials",
        username_secret_key="username",
        password_secret_key="password",
        available_countries=["AU"],
        commission_model="built_into_odds",
        min_bet="1",
        min_bet_currency="AUD",
        withdrawal_fee="0",
    ),
    "betright": VenueExecutionProfile(
        venue_key="betright",
        odds_api_key="betright",
        display_name="BetRight",
        venue_category=VenueCategory.SCRAPER,
        primary_execution_method=ExecutionMethod.BROWSER_AUTOMATION,
        credential_type=CredentialType.USERNAME_PASSWORD,
        login_url="https://www.betright.com.au",
        config_secret_field="betright_credentials",
        username_secret_key="username",
        password_secret_key="password",
        available_countries=["AU"],
        commission_model="built_into_odds",
        min_bet="1",
        min_bet_currency="AUD",
        withdrawal_fee="0",
    ),
    "playup": VenueExecutionProfile(
        venue_key="playup",
        odds_api_key="playup",
        display_name="PlayUp",
        venue_category=VenueCategory.SCRAPER,
        primary_execution_method=ExecutionMethod.BROWSER_AUTOMATION,
        credential_type=CredentialType.USERNAME_PASSWORD,
        login_url="https://www.playup.com.au",
        config_secret_field="playup_credentials",
        username_secret_key="username",
        password_secret_key="password",
        available_countries=["AU"],
        commission_model="built_into_odds",
        min_bet="1",
        min_bet_currency="AUD",
        withdrawal_fee="0",
    ),
    "tabtouch": VenueExecutionProfile(
        venue_key="tabtouch",
        odds_api_key="tabtouch",
        display_name="TAB Touch",
        venue_category=VenueCategory.SCRAPER,
        primary_execution_method=ExecutionMethod.BROWSER_AUTOMATION,
        credential_type=CredentialType.USERNAME_PASSWORD,
        login_url="https://www.tabtouch.com.au",
        config_secret_field="tabtouch_credentials",
        username_secret_key="username",
        password_secret_key="password",
        available_countries=["AU"],
        commission_model="built_into_odds",
        min_bet="1",
        min_bet_currency="AUD",
        withdrawal_fee="0",
    ),
    # ── UK Scrapers ──────────────────────────────────────────────────────
    "williamhill": VenueExecutionProfile(
        venue_key="williamhill",
        odds_api_key="williamhill",
        display_name="William Hill",
        venue_category=VenueCategory.SCRAPER,
        primary_execution_method=ExecutionMethod.BROWSER_AUTOMATION,
        credential_type=CredentialType.USERNAME_PASSWORD,
        login_url="https://www.williamhill.com/",
        config_secret_field="williamhill_credentials",
        username_secret_key="username",
        password_secret_key="password",
        anti_detection_level=AntiDetectionLevel.MODERATE,
        available_countries=["GB"],
        commission_model="built_into_odds",
        min_bet="0.10",
        min_bet_currency="GBP",
        withdrawal_fee="0",
    ),
    "ladbrokes_uk": VenueExecutionProfile(
        venue_key="ladbrokes_uk",
        odds_api_key="ladbrokes_uk",
        display_name="Ladbrokes UK",
        venue_category=VenueCategory.SCRAPER,
        primary_execution_method=ExecutionMethod.BROWSER_AUTOMATION,
        credential_type=CredentialType.USERNAME_PASSWORD,
        login_url="https://www.ladbrokes.com/",
        config_secret_field="ladbrokes_uk_credentials",
        username_secret_key="username",
        password_secret_key="password",
        anti_detection_level=AntiDetectionLevel.MODERATE,
        available_countries=["GB"],
        commission_model="built_into_odds",
        min_bet="0.10",
        min_bet_currency="GBP",
        withdrawal_fee="0",
    ),
    "coral": VenueExecutionProfile(
        venue_key="coral",
        odds_api_key="coral",
        display_name="Coral",
        venue_category=VenueCategory.SCRAPER,
        primary_execution_method=ExecutionMethod.BROWSER_AUTOMATION,
        credential_type=CredentialType.USERNAME_PASSWORD,
        login_url="https://www.coral.co.uk/",
        config_secret_field="coral_credentials",
        username_secret_key="username",
        password_secret_key="password",
        anti_detection_level=AntiDetectionLevel.MODERATE,
        available_countries=["GB"],
        commission_model="built_into_odds",
        min_bet="0.10",
        min_bet_currency="GBP",
        withdrawal_fee="0",
    ),
    "paddypower": VenueExecutionProfile(
        venue_key="paddypower",
        odds_api_key="paddypower",
        display_name="Paddy Power",
        venue_category=VenueCategory.SCRAPER,
        primary_execution_method=ExecutionMethod.BROWSER_AUTOMATION,
        credential_type=CredentialType.USERNAME_PASSWORD,
        login_url="https://www.paddypower.com/",
        config_secret_field="paddypower_credentials",
        username_secret_key="username",
        password_secret_key="password",
        anti_detection_level=AntiDetectionLevel.MODERATE,
        available_countries=["GB"],
        commission_model="built_into_odds",
        min_bet="0.10",
        min_bet_currency="GBP",
        withdrawal_fee="0",
    ),
    "skybet": VenueExecutionProfile(
        venue_key="skybet",
        odds_api_key="skybet",
        display_name="Sky Bet",
        venue_category=VenueCategory.SCRAPER,
        primary_execution_method=ExecutionMethod.BROWSER_AUTOMATION,
        credential_type=CredentialType.USERNAME_PASSWORD,
        login_url="https://www.skybet.com/",
        config_secret_field="skybet_credentials",
        username_secret_key="username",
        password_secret_key="password",
        anti_detection_level=AntiDetectionLevel.AGGRESSIVE,
        available_countries=["GB"],
        commission_model="built_into_odds",
        min_bet="0.10",
        min_bet_currency="GBP",
        withdrawal_fee="0",
    ),
    "betway": VenueExecutionProfile(
        venue_key="betway",
        odds_api_key="betway",
        display_name="Betway",
        venue_category=VenueCategory.SCRAPER,
        primary_execution_method=ExecutionMethod.BROWSER_AUTOMATION,
        credential_type=CredentialType.USERNAME_PASSWORD,
        login_url="https://www.betway.com/",
        config_secret_field="betway_credentials",
        username_secret_key="username",
        password_secret_key="password",
        anti_detection_level=AntiDetectionLevel.MODERATE,
        available_countries=["GB"],
        commission_model="built_into_odds",
        min_bet="0.10",
        min_bet_currency="GBP",
        withdrawal_fee="0",
    ),
    "sport888": VenueExecutionProfile(
        venue_key="sport888",
        odds_api_key="sport888",
        display_name="888sport",
        venue_category=VenueCategory.SCRAPER,
        primary_execution_method=ExecutionMethod.BROWSER_AUTOMATION,
        credential_type=CredentialType.USERNAME_PASSWORD,
        login_url="https://www.888sport.com/",
        config_secret_field="sport888_credentials",
        username_secret_key="username",
        password_secret_key="password",
        anti_detection_level=AntiDetectionLevel.MODERATE,
        available_countries=["GB"],
        commission_model="built_into_odds",
        min_bet="0.10",
        min_bet_currency="GBP",
        withdrawal_fee="0",
    ),
    "betvictor": VenueExecutionProfile(
        venue_key="betvictor",
        odds_api_key="betvictor",
        display_name="BetVictor",
        venue_category=VenueCategory.SCRAPER,
        primary_execution_method=ExecutionMethod.BROWSER_AUTOMATION,
        credential_type=CredentialType.USERNAME_PASSWORD,
        login_url="https://www.betvictor.com/",
        config_secret_field="betvictor_credentials",
        username_secret_key="username",
        password_secret_key="password",
        anti_detection_level=AntiDetectionLevel.MODERATE,
        available_countries=["GB"],
        commission_model="built_into_odds",
        min_bet="0.10",
        min_bet_currency="GBP",
        withdrawal_fee="0",
    ),
    "boylesports": VenueExecutionProfile(
        venue_key="boylesports",
        odds_api_key="boylesports",
        display_name="BoyleSports",
        venue_category=VenueCategory.SCRAPER,
        primary_execution_method=ExecutionMethod.BROWSER_AUTOMATION,
        credential_type=CredentialType.USERNAME_PASSWORD,
        login_url="https://www.boylesports.com/",
        config_secret_field="boylesports_credentials",
        username_secret_key="username",
        password_secret_key="password",
        anti_detection_level=AntiDetectionLevel.MODERATE,
        available_countries=["GB"],
        commission_model="built_into_odds",
        min_bet="0.10",
        min_bet_currency="GBP",
        withdrawal_fee="0",
    ),
    "virginbet": VenueExecutionProfile(
        venue_key="virginbet",
        odds_api_key="virginbet",
        display_name="Virgin Bet",
        venue_category=VenueCategory.SCRAPER,
        primary_execution_method=ExecutionMethod.BROWSER_AUTOMATION,
        credential_type=CredentialType.USERNAME_PASSWORD,
        login_url="https://www.virginbet.com/",
        config_secret_field="virginbet_credentials",
        username_secret_key="username",
        password_secret_key="password",
        anti_detection_level=AntiDetectionLevel.MODERATE,
        available_countries=["GB"],
        commission_model="built_into_odds",
        min_bet="0.10",
        min_bet_currency="GBP",
        withdrawal_fee="0",
    ),
    "livescorebet": VenueExecutionProfile(
        venue_key="livescorebet",
        odds_api_key="livescorebet",
        display_name="LiveScore Bet",
        venue_category=VenueCategory.SCRAPER,
        primary_execution_method=ExecutionMethod.BROWSER_AUTOMATION,
        credential_type=CredentialType.USERNAME_PASSWORD,
        login_url="https://www.livescorebet.com/",
        config_secret_field="livescorebet_credentials",
        username_secret_key="username",
        password_secret_key="password",
        anti_detection_level=AntiDetectionLevel.MODERATE,
        available_countries=["GB"],
        commission_model="built_into_odds",
        min_bet="0.10",
        min_bet_currency="GBP",
        withdrawal_fee="0",
    ),
}
