/** Reference data for the atomic bundle builder (venues overlap conceptually with trading book; list kept for builder UX). */

export const ALL_OPERATION_TYPES = [
  "LEND",
  "BORROW",
  "WITHDRAW",
  "REPAY",
  "STAKE",
  "UNSTAKE",
  "SWAP",
  "TRADE",
  "TRANSFER",
  "FLASH_BORROW",
  "FLASH_REPAY",
  "ADD_LIQUIDITY",
  "REMOVE_LIQUIDITY",
  "COLLECT_FEES",
  "BET",
  "CANCEL_BET",
  "SPORTS_EXCHANGE",
  "OPTIONS_COMBO",
  "FUTURES_ROLL",
  "PREDICTION_BET",
  "SPORTS_BET",
  "SPORTS_EXCHANGE_ORDER",
] as const;

export type BundleOperationType = (typeof ALL_OPERATION_TYPES)[number];

export const BUNDLE_VENUES = [
  "Binance",
  "Deribit",
  "Hyperliquid",
  "Coinbase",
  "OKX",
  "Bybit",
  "Uniswap",
  "Curve",
  "Aave",
  "Sushiswap",
  "Balancer",
  "Lido",
  "EtherFi",
  "RocketPool",
  "Betfair",
  "Pinnacle",
  "Bet365",
  "Smarkets",
  "Polymarket",
  "Kalshi",
] as const;

export const BUNDLE_INSTRUMENTS = [
  "BTC/USDT",
  "ETH/USDT",
  "SOL/USDT",
  "BTC/USD-PERP",
  "ETH/USD-PERP",
  "ETH",
  "USDC",
  "USDT",
  "DAI",
  "WBTC",
  "LINK",
  "BTC-28MAR26-70000-C",
  "BTC-28MAR26-65000-P",
  "Arsenal vs Chelsea",
  "Man City vs Liverpool",
  "YES-Arsenal-EPL",
  "NO-Arsenal-EPL",
] as const;
