import type { TerminalEvent } from "@/components/widgets/terminal/terminal-data-context";

export const MOCK_TERMINAL_EVENTS: TerminalEvent[] = [
  {
    id: "evt-1",
    timestamp: "14:32:08",
    domain: "EXECUTION",
    severity: "INFO",
    title: "Order Filled",
    detail: "BTC/USDT LONG 0.5 @ 68,420 on Binance",
  },
  {
    id: "evt-2",
    timestamp: "14:31:45",
    domain: "RISK",
    severity: "WARNING",
    title: "Margin Utilisation High",
    detail: "Account SL2 at 78.4% margin — threshold 80%",
  },
  {
    id: "evt-3",
    timestamp: "14:30:12",
    domain: "STRATEGY",
    severity: "INFO",
    title: "Signal Generated",
    detail: "HUF-MOMENTUM-BTC entered LONG bias (score 0.82)",
  },
  {
    id: "evt-4",
    timestamp: "14:29:58",
    domain: "DATA",
    severity: "INFO",
    title: "Market Data Refresh",
    detail: "MTDS tick batch 2026-04-15T14:29 — 425 venues OK",
  },
  {
    id: "evt-5",
    timestamp: "14:28:30",
    domain: "SYSTEM",
    severity: "CRITICAL",
    title: "Health Check Failed",
    detail: "features-onchain-service /healthz returned 503 — 2 retries",
  },
  {
    id: "evt-6",
    timestamp: "14:27:15",
    domain: "EXECUTION",
    severity: "INFO",
    title: "Flash Loan Executed",
    detail: "Aave V3 ETH 50.0 — arb profit $342 (0.18%)",
  },
  {
    id: "evt-7",
    timestamp: "14:26:40",
    domain: "RISK",
    severity: "WARNING",
    title: "Liquidation Proximity",
    detail: "AAVE ETH-USDC HF 1.12 — monitor threshold 1.15",
  },
  {
    id: "evt-8",
    timestamp: "14:25:02",
    domain: "STRATEGY",
    severity: "INFO",
    title: "Regime Shift",
    detail: "Commodity regime: Mean-Reverting -> Trending (WTI driver)",
  },
  {
    id: "evt-9",
    timestamp: "14:24:18",
    domain: "DATA",
    severity: "INFO",
    title: "Instruments Refreshed",
    detail: "instruments-service batch — 12,482 active instruments",
  },
  {
    id: "evt-10",
    timestamp: "14:23:05",
    domain: "EXECUTION",
    severity: "INFO",
    title: "LP Rebalance",
    detail: "Uniswap V3 ETH/USDC range adjusted: 3,600-4,100",
  },
];
