"""Venue error classifications for prediction markets and sports betting platforms."""

from __future__ import annotations

from ._types import ErrorAction, VenueErrorClassification, ve

VENUE_ERRORS_SPORTS: dict[str, list[VenueErrorClassification]] = {
    "polymarket": [
        ve(
            "polymarket",
            "429",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Rate limit exceeded",
        ),
        ve(
            "polymarket",
            "401",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Unauthorized — invalid API key or signature",
        ),
        ve(
            "polymarket",
            "400",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Bad request — invalid order parameters",
        ),
        ve(
            "polymarket",
            "500",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Internal server error",
        ),
    ],
    "betfair": [
        ve(
            "betfair",
            "INVALID_SESSION_INFORMATION",
            retry=False,
            reconnect=True,
            action=ErrorAction.RECONNECT,
            desc="Session token invalid or expired — reauthenticate",
        ),
        ve(
            "betfair",
            "NO_SESSION",
            retry=False,
            reconnect=True,
            action=ErrorAction.RECONNECT,
            desc="No active session — reauthenticate",
        ),
        ve(
            "betfair",
            "TOO_MUCH_DATA",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Response too large — reduce request scope",
        ),
        ve(
            "betfair",
            "SERVICE_BUSY",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Betfair API service busy — retry with backoff",
        ),
        ve(
            "betfair",
            "TIMEOUT_ERROR",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Request timed out on Betfair side",
        ),
        ve(
            "betfair",
            "REQUEST_SIZE_EXCEEDS_LIMIT",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Request payload exceeds size limit",
        ),
        ve(
            "betfair",
            "429",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="HTTP rate limit exceeded",
        ),
        ve(
            "betfair",
            "401",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Unauthorized",
        ),
        ve(
            "betfair",
            "400",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Bad request",
        ),
        ve(
            "betfair",
            "500",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Internal server error",
        ),
    ],
    "kalshi": [
        ve(
            "kalshi",
            "429",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Rate limit exceeded",
        ),
        ve(
            "kalshi",
            "401",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Unauthorized — invalid or expired token",
        ),
        ve(
            "kalshi",
            "403",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Forbidden — insufficient permissions",
        ),
        ve(
            "kalshi",
            "400",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Bad request — invalid order parameters",
        ),
        ve(
            "kalshi",
            "500",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Internal server error",
        ),
        ve(
            "kalshi",
            "MARKET_NOT_OPEN",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Market is not open for trading",
        ),
        ve(
            "kalshi",
            "INSUFFICIENT_FUNDS",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Account balance insufficient for order",
        ),
    ],
    "smarkets": [
        ve(
            "smarkets",
            "429",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Rate limit exceeded",
        ),
        ve(
            "smarkets",
            "401",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Unauthorized — invalid credentials",
        ),
        ve(
            "smarkets",
            "400",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Bad request",
        ),
        ve(
            "smarkets",
            "500",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Internal server error",
        ),
        ve(
            "smarkets",
            "MARKET_SUSPENDED",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Market suspended — no new orders accepted",
        ),
        ve(
            "smarkets",
            "SELECTION_REMOVED",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Selection removed from market",
        ),
    ],
    "betdaq": [
        ve(
            "betdaq",
            "429",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Rate limit exceeded",
        ),
        ve(
            "betdaq",
            "401",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Unauthorized — invalid credentials",
        ),
        ve(
            "betdaq",
            "400",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Bad request",
        ),
        ve(
            "betdaq",
            "500",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Internal server error",
        ),
        ve(
            "betdaq",
            "MARKET_SUSPENDED",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Market suspended — no new orders accepted",
        ),
        ve(
            "betdaq",
            "SELECTION_REMOVED",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Selection removed from market",
        ),
    ],
}
