"""Venue execution registry — US sportsbooks, DFS, and social betting."""

from __future__ import annotations

from decimal import Decimal

from .venue_execution import (
    AntiDetectionLevel,
    CredentialType,
    ExecutionMethod,
    VenueCategory,
    VenueExecutionProfile,
)

US_VENUE_REGISTRY: dict[str, VenueExecutionProfile] = {
    # ── US Major Sportsbooks (Browser Automation) ────────────────────────
    "draftkings": VenueExecutionProfile(
        venue_key="draftkings",
        odds_api_key="draftkings",
        display_name="DraftKings",
        venue_category=VenueCategory.SCRAPER,
        primary_execution_method=ExecutionMethod.BROWSER_AUTOMATION,
        credential_type=CredentialType.USERNAME_PASSWORD,
        login_url="https://sportsbook.draftkings.com/",
        config_secret_field="draftkings_credentials",
        username_secret_key="username",
        password_secret_key="password",
        anti_detection_level=AntiDetectionLevel.AGGRESSIVE,
        requires_geolocation_check=True,
        geolocation_provider="geocomply",
        commission_model="built_into_odds",
        min_bet="0.50",
        min_bet_currency="USD",
        withdrawal_fee="0",
    ),
    "fanduel": VenueExecutionProfile(
        venue_key="fanduel",
        odds_api_key="fanduel",
        display_name="FanDuel",
        venue_category=VenueCategory.SCRAPER,
        primary_execution_method=ExecutionMethod.BROWSER_AUTOMATION,
        credential_type=CredentialType.USERNAME_PASSWORD,
        login_url="https://sportsbook.fanduel.com/",
        config_secret_field="fanduel_credentials",
        username_secret_key="username",
        password_secret_key="password",
        anti_detection_level=AntiDetectionLevel.AGGRESSIVE,
        requires_geolocation_check=True,
        geolocation_provider="geocomply",
        commission_model="built_into_odds",
        min_bet="1",
        min_bet_currency="USD",
        withdrawal_fee="0",
    ),
    "betmgm": VenueExecutionProfile(
        venue_key="betmgm",
        odds_api_key="betmgm",
        display_name="BetMGM",
        venue_category=VenueCategory.SCRAPER,
        primary_execution_method=ExecutionMethod.BROWSER_AUTOMATION,
        credential_type=CredentialType.USERNAME_PASSWORD,
        login_url="https://sports.betmgm.com/",
        config_secret_field="betmgm_credentials",
        username_secret_key="username",
        password_secret_key="password",
        anti_detection_level=AntiDetectionLevel.AGGRESSIVE,
        requires_geolocation_check=True,
        geolocation_provider="geocomply",
        commission_model="built_into_odds",
        min_bet="1",
        min_bet_currency="USD",
        withdrawal_fee="0",
    ),
    "williamhill_us": VenueExecutionProfile(
        venue_key="williamhill_us",
        odds_api_key="williamhill_us",
        display_name="William Hill US",
        venue_category=VenueCategory.SCRAPER,
        primary_execution_method=ExecutionMethod.BROWSER_AUTOMATION,
        credential_type=CredentialType.USERNAME_PASSWORD,
        login_url="https://www.williamhill.com/us/",
        config_secret_field="williamhill_us_credentials",
        username_secret_key="username",
        password_secret_key="password",
        anti_detection_level=AntiDetectionLevel.MODERATE,
        requires_geolocation_check=True,
        geolocation_provider="geocomply",
        commission_model="built_into_odds",
        min_bet="1",
        min_bet_currency="USD",
        withdrawal_fee="0",
    ),
    "betrivers": VenueExecutionProfile(
        venue_key="betrivers",
        odds_api_key="betrivers",
        display_name="BetRivers",
        venue_category=VenueCategory.SCRAPER,
        primary_execution_method=ExecutionMethod.BROWSER_AUTOMATION,
        credential_type=CredentialType.USERNAME_PASSWORD,
        login_url="https://www.betrivers.com/",
        config_secret_field="betrivers_credentials",
        username_secret_key="username",
        password_secret_key="password",
        anti_detection_level=AntiDetectionLevel.MODERATE,
        requires_geolocation_check=True,
        geolocation_provider="geocomply",
        commission_model="built_into_odds",
        min_bet="0.50",
        min_bet_currency="USD",
        withdrawal_fee="0",
    ),
    "espnbet": VenueExecutionProfile(
        venue_key="espnbet",
        odds_api_key="espnbet",
        display_name="ESPN Bet",
        venue_category=VenueCategory.SCRAPER,
        primary_execution_method=ExecutionMethod.BROWSER_AUTOMATION,
        credential_type=CredentialType.USERNAME_PASSWORD,
        login_url="https://www.espnbet.com/",
        config_secret_field="espnbet_credentials",
        username_secret_key="username",
        password_secret_key="password",
        anti_detection_level=AntiDetectionLevel.MODERATE,
        requires_geolocation_check=True,
        geolocation_provider="geocomply",
        commission_model="built_into_odds",
        min_bet="1",
        min_bet_currency="USD",
        withdrawal_fee="0",
    ),
    "hardrockbet": VenueExecutionProfile(
        venue_key="hardrockbet",
        odds_api_key="hardrockbet",
        display_name="Hard Rock Bet",
        venue_category=VenueCategory.SCRAPER,
        primary_execution_method=ExecutionMethod.BROWSER_AUTOMATION,
        credential_type=CredentialType.USERNAME_PASSWORD,
        login_url="https://www.hardrockbet.com/",
        config_secret_field="hardrockbet_credentials",
        username_secret_key="username",
        password_secret_key="password",
        anti_detection_level=AntiDetectionLevel.MODERATE,
        requires_geolocation_check=True,
        geolocation_provider="geocomply",
        commission_model="built_into_odds",
        min_bet="1",
        min_bet_currency="USD",
        withdrawal_fee="0",
    ),
    "fanatics": VenueExecutionProfile(
        venue_key="fanatics",
        odds_api_key="fanatics",
        display_name="Fanatics",
        venue_category=VenueCategory.SCRAPER,
        primary_execution_method=ExecutionMethod.BROWSER_AUTOMATION,
        credential_type=CredentialType.USERNAME_PASSWORD,
        login_url="https://sportsbook.fanatics.com/",
        config_secret_field="fanatics_credentials",
        username_secret_key="username",
        password_secret_key="password",
        anti_detection_level=AntiDetectionLevel.MODERATE,
        requires_geolocation_check=True,
        geolocation_provider="geocomply",
        commission_model="built_into_odds",
        min_bet="1",
        min_bet_currency="USD",
        withdrawal_fee="0",
    ),
    # ── US DFS / Social Betting ──────────────────────────────────────────
    "betr_us_dfs": VenueExecutionProfile(
        venue_key="betr_us_dfs",
        odds_api_key="betr_us_dfs",
        display_name="Betr (US DFS)",
        parent_company="Betr Holdings",
        venue_category=VenueCategory.SCRAPER,
        primary_execution_method=ExecutionMethod.BROWSER_AUTOMATION,
        credential_type=CredentialType.USERNAME_PASSWORD,
        login_url="https://www.betr.app/",
        config_secret_field="betr_us_dfs_credentials",
        username_secret_key="username",
        password_secret_key="password",
        headquarters_country="US",
        requires_geolocation_check=True,
        supported_currencies=["USD"],
        min_bet=Decimal("1"),
        min_bet_currency="USD",
        anti_detection_level=AntiDetectionLevel.MODERATE,
        commission_model="built_into_odds",
        withdrawal_fee=Decimal("0"),
        notes="US DFS/micro-betting platform. Props and picks format.",
    ),
    "pick6": VenueExecutionProfile(
        venue_key="pick6",
        odds_api_key="pick6",
        display_name="Pick6 by DraftKings",
        parent_company="DraftKings",
        venue_category=VenueCategory.SCRAPER,
        primary_execution_method=ExecutionMethod.BROWSER_AUTOMATION,
        credential_type=CredentialType.USERNAME_PASSWORD,
        login_url="https://pick6.draftkings.com/",
        config_secret_field="pick6_credentials",
        username_secret_key="username",
        password_secret_key="password",
        headquarters_country="US",
        requires_geolocation_check=True,
        supported_currencies=["USD"],
        min_bet=Decimal("1"),
        min_bet_currency="USD",
        anti_detection_level=AntiDetectionLevel.MODERATE,
        commission_model="built_into_odds",
        withdrawal_fee=Decimal("0"),
        notes="DraftKings DFS pick'em product.",
    ),
    "prizepicks": VenueExecutionProfile(
        venue_key="prizepicks",
        odds_api_key="prizepicks",
        display_name="PrizePicks",
        parent_company="PrizePicks LLC",
        venue_category=VenueCategory.SCRAPER,
        primary_execution_method=ExecutionMethod.BROWSER_AUTOMATION,
        credential_type=CredentialType.USERNAME_PASSWORD,
        login_url="https://app.prizepicks.com/",
        config_secret_field="prizepicks_credentials",
        username_secret_key="username",
        password_secret_key="password",
        headquarters_country="US",
        requires_geolocation_check=True,
        supported_currencies=["USD"],
        min_bet=Decimal("5"),
        min_bet_currency="USD",
        max_payout=Decimal("100000"),
        max_payout_currency="USD",
        anti_detection_level=AntiDetectionLevel.MODERATE,
        commission_model="built_into_odds",
        withdrawal_fee=Decimal("0"),
        notes="US DFS props platform. Over/under player props. $5 min entry.",
    ),
    "underdog": VenueExecutionProfile(
        venue_key="underdog",
        odds_api_key="underdog",
        display_name="Underdog Fantasy",
        parent_company="Underdog Sports",
        venue_category=VenueCategory.SCRAPER,
        primary_execution_method=ExecutionMethod.BROWSER_AUTOMATION,
        credential_type=CredentialType.USERNAME_PASSWORD,
        login_url="https://underdogfantasy.com/",
        config_secret_field="underdog_credentials",
        username_secret_key="username",
        password_secret_key="password",
        headquarters_country="US",
        requires_geolocation_check=True,
        supported_currencies=["USD"],
        min_bet=Decimal("1"),
        min_bet_currency="USD",
        max_payout=Decimal("50000"),
        max_payout_currency="USD",
        anti_detection_level=AntiDetectionLevel.MODERATE,
        commission_model="built_into_odds",
        withdrawal_fee=Decimal("0"),
        notes="US DFS pick'em platform. Higher/lower player props.",
    ),
    "fliff": VenueExecutionProfile(
        venue_key="fliff",
        odds_api_key="fliff",
        display_name="Fliff",
        parent_company="Fliff Inc",
        venue_category=VenueCategory.SCRAPER,
        primary_execution_method=ExecutionMethod.BROWSER_AUTOMATION,
        credential_type=CredentialType.USERNAME_PASSWORD,
        login_url="https://www.getfliff.com/",
        config_secret_field="fliff_credentials",
        username_secret_key="username",
        password_secret_key="password",
        headquarters_country="US",
        requires_geolocation_check=True,
        supported_currencies=["USD"],
        min_bet=Decimal("0.50"),
        min_bet_currency="USD",
        anti_detection_level=AntiDetectionLevel.BASIC,
        commission_model="built_into_odds",
        withdrawal_fee=Decimal("0"),
        notes="US social sportsbook using sweepstakes model.",
    ),
    # ── US Additional ────────────────────────────────────────────────────
    "ballybet": VenueExecutionProfile(
        venue_key="ballybet",
        odds_api_key="ballybet",
        display_name="Bally Bet",
        parent_company="Bally's Corporation",
        venue_category=VenueCategory.SCRAPER,
        primary_execution_method=ExecutionMethod.BROWSER_AUTOMATION,
        credential_type=CredentialType.USERNAME_PASSWORD,
        login_url="https://www.ballybet.com/",
        config_secret_field="ballybet_credentials",
        username_secret_key="username",
        password_secret_key="password",
        headquarters_country="US",
        available_us_states=["AZ", "CO", "IA", "IN", "NY", "OH", "VA"],
        requires_geolocation_check=True,
        geolocation_provider="geocomply",
        supported_currencies=["USD"],
        min_bet=Decimal("0.50"),
        min_bet_currency="USD",
        anti_detection_level=AntiDetectionLevel.MODERATE,
        commission_model="built_into_odds",
        withdrawal_fee=Decimal("0"),
        notes="Bally's Corp US sportsbook. Multi-state licensed.",
    ),
    "betparx": VenueExecutionProfile(
        venue_key="betparx",
        odds_api_key="betparx",
        display_name="BetParx",
        parent_company="Parx Casino",
        venue_category=VenueCategory.SCRAPER,
        primary_execution_method=ExecutionMethod.BROWSER_AUTOMATION,
        credential_type=CredentialType.USERNAME_PASSWORD,
        login_url="https://www.betparx.com/",
        config_secret_field="betparx_credentials",
        username_secret_key="username",
        password_secret_key="password",
        headquarters_country="US",
        available_us_states=["PA", "NJ", "OH", "MD"],
        requires_geolocation_check=True,
        geolocation_provider="geocomply",
        supported_currencies=["USD"],
        min_bet=Decimal("1"),
        min_bet_currency="USD",
        anti_detection_level=AntiDetectionLevel.MODERATE,
        commission_model="built_into_odds",
        withdrawal_fee=Decimal("0"),
        notes="Parx Casino US sportsbook. PA-based.",
    ),
}
