// Demo fixtures for audit dashboard
export const auditStats = {
  totalEvents: 48291,
  todayEvents: 1247,
  trades: 892,
  orders: 3451,
  logins: 145,
  configChanges: 23,
  alerts: 67,
};

export const recentEvents = [
  {
    id: "evt-001",
    type: "trade",
    action: "TRADE_EXECUTED",
    user: "btc-basis-v3",
    details: "BUY 0.5 BTC @ $43,245",
    timestamp: "2s ago",
    status: "success",
    venue: "Binance",
  },
  {
    id: "evt-002",
    type: "order",
    action: "ORDER_PLACED",
    user: "eth-staked",
    details: "LIMIT SELL 10 ETH @ $2,450",
    timestamp: "5s ago",
    status: "pending",
    venue: "Deribit",
  },
  {
    id: "evt-003",
    type: "alert",
    action: "ALERT_TRIGGERED",
    user: "risk-monitor",
    details: "Margin utilization exceeded 80%",
    timestamp: "12s ago",
    status: "warning",
    venue: "System",
  },
  {
    id: "evt-004",
    type: "login",
    action: "USER_LOGIN",
    user: "john.doe@trading.co",
    details: "Login from 192.168.1.1",
    timestamp: "1m ago",
    status: "success",
    venue: "Auth",
  },
  {
    id: "evt-005",
    type: "config",
    action: "CONFIG_CHANGED",
    user: "admin@trading.co",
    details: "Updated risk limits for BTC strategies",
    timestamp: "2m ago",
    status: "success",
    venue: "Config",
  },
  {
    id: "evt-006",
    type: "trade",
    action: "TRADE_EXECUTED",
    user: "aave-lending",
    details: "SUPPLY 50,000 USDC to Aave",
    timestamp: "3m ago",
    status: "success",
    venue: "Aave",
  },
  {
    id: "evt-007",
    type: "order",
    action: "ORDER_CANCELLED",
    user: "ml-directional",
    details: "Cancelled stale order #ORD-4521",
    timestamp: "4m ago",
    status: "info",
    venue: "Binance",
  },
  {
    id: "evt-008",
    type: "alert",
    action: "ALERT_RESOLVED",
    user: "system",
    details: "Feature freshness restored",
    timestamp: "5m ago",
    status: "success",
    venue: "System",
  },
  {
    id: "evt-009",
    type: "trade",
    action: "TRADE_EXECUTED",
    user: "btc-basis-v3",
    details: "SELL 0.3 BTC @ $43,312",
    timestamp: "6m ago",
    status: "success",
    venue: "Binance",
  },
  {
    id: "evt-010",
    type: "login",
    action: "USER_LOGOUT",
    user: "jane.smith@trading.co",
    details: "Session ended",
    timestamp: "8m ago",
    status: "info",
    venue: "Auth",
  },
];

export const tradeHistory = [
  {
    id: "TRD-8921",
    strategy: "BTC Basis v3",
    side: "BUY",
    instrument: "BTC-PERP",
    qty: "0.5",
    price: "$43,245",
    venue: "Binance",
    pnl: "+$127",
    timestamp: "2s ago",
  },
  {
    id: "TRD-8920",
    strategy: "ETH Staked",
    side: "SELL",
    instrument: "ETH-SPOT",
    qty: "5.2",
    price: "$2,445",
    venue: "Coinbase",
    pnl: "+$89",
    timestamp: "45s ago",
  },
  {
    id: "TRD-8919",
    strategy: "AAVE Lending",
    side: "SUPPLY",
    instrument: "USDC",
    qty: "50,000",
    price: "$1.00",
    venue: "Aave",
    pnl: "-",
    timestamp: "3m ago",
  },
  {
    id: "TRD-8917",
    strategy: "ML Directional",
    side: "BUY",
    instrument: "SOL-PERP",
    qty: "100",
    price: "$98.45",
    venue: "Binance",
    pnl: "+$215",
    timestamp: "8m ago",
  },
  {
    id: "TRD-8916",
    strategy: "Sports Arb",
    side: "BET",
    instrument: "NBA-LAL",
    qty: "$500",
    price: "1.85",
    venue: "Polymarket",
    pnl: "+$425",
    timestamp: "12m ago",
  },
];

export const orderHistory = [
  {
    id: "ORD-4525",
    strategy: "BTC Basis v3",
    type: "LIMIT",
    side: "BUY",
    instrument: "BTC-PERP",
    qty: "1.0",
    price: "$43,100",
    status: "open",
    filled: "0%",
    timestamp: "1m ago",
  },
  {
    id: "ORD-4524",
    strategy: "ETH Staked",
    type: "MARKET",
    side: "SELL",
    instrument: "ETH-SPOT",
    qty: "10",
    price: "MKT",
    status: "filled",
    filled: "100%",
    timestamp: "2m ago",
  },
  {
    id: "ORD-4523",
    strategy: "ML Directional",
    type: "LIMIT",
    side: "SELL",
    instrument: "SOL-PERP",
    qty: "50",
    price: "$99.50",
    status: "cancelled",
    filled: "0%",
    timestamp: "4m ago",
  },
  {
    id: "ORD-4522",
    strategy: "BTC Basis v3",
    type: "LIMIT",
    side: "SELL",
    instrument: "BTC-SPOT",
    qty: "0.5",
    price: "$43,500",
    status: "partial",
    filled: "60%",
    timestamp: "8m ago",
  },
];

export const loginHistory = [
  {
    id: "LOG-892",
    user: "john.doe@trading.co",
    action: "LOGIN",
    ip: "192.168.1.1",
    device: "Chrome / macOS",
    location: "New York, US",
    timestamp: "1m ago",
    status: "success",
  },
  {
    id: "LOG-891",
    user: "jane.smith@trading.co",
    action: "LOGOUT",
    ip: "192.168.1.45",
    device: "Safari / macOS",
    location: "London, UK",
    timestamp: "8m ago",
    status: "success",
  },
  {
    id: "LOG-890",
    user: "admin@trading.co",
    action: "LOGIN",
    ip: "10.0.0.1",
    device: "Firefox / Linux",
    location: "Singapore",
    timestamp: "15m ago",
    status: "success",
  },
  {
    id: "LOG-889",
    user: "unknown@test.com",
    action: "LOGIN_FAILED",
    ip: "45.67.89.123",
    device: "Unknown",
    location: "Unknown",
    timestamp: "22m ago",
    status: "failed",
  },
  {
    id: "LOG-888",
    user: "mike.ops@trading.co",
    action: "LOGIN",
    ip: "192.168.1.78",
    device: "Chrome / Windows",
    location: "Tokyo, JP",
    timestamp: "45m ago",
    status: "success",
  },
];

export const configChanges = [
  {
    id: "CFG-145",
    user: "admin@trading.co",
    category: "Risk Limits",
    change: "BTC max position: $50M → $60M",
    timestamp: "2m ago",
    approved: true,
  },
  {
    id: "CFG-144",
    user: "john.doe@trading.co",
    category: "Strategy Config",
    change: "btc-basis-v3: enabled hedging",
    timestamp: "1h ago",
    approved: true,
  },
  {
    id: "CFG-143",
    user: "admin@trading.co",
    category: "System",
    change: "Kill switch threshold: 5% → 4%",
    timestamp: "2h ago",
    approved: true,
  },
  {
    id: "CFG-142",
    user: "mike.ops@trading.co",
    category: "Deployment",
    change: "Deployed execution-svc v2.14.3",
    timestamp: "4h ago",
    approved: true,
  },
];
