"""Venue execution registry — API-based exchanges and prediction markets."""

from __future__ import annotations

from decimal import Decimal

from .venue_execution import (
    AntiDetectionLevel,
    CredentialType,
    ExecutionMethod,
    VenueCategory,
    VenueExecutionProfile,
)

EXCHANGE_REGISTRY: dict[str, VenueExecutionProfile] = {
    # ── Traditional Betting Exchanges (REST API) ─────────────────────────
    "betfair_ex_uk": VenueExecutionProfile(
        venue_key="betfair_ex_uk",
        odds_api_key="betfair_ex_uk",
        display_name="Betfair Exchange UK",
        primary_execution_method=ExecutionMethod.REST_API,
        api_base_url="https://api.betfair.com",
        api_docs_url="https://docs.developer.betfair.com/",
        credential_type=CredentialType.API_KEY,
        venue_category=VenueCategory.EXCHANGE,
        config_secret_field="betfair_secret_name",
        min_bet="2.00",
        commission_model="net_winnings_pct",
        available_countries=["GB", "IE"],
        withdrawal_delay_hours_min=24,
        withdrawal_delay_hours_max=72,
        commission_rate="5.0",
        min_bet_currency="GBP",
        withdrawal_fee="0",
    ),
    "betfair_ex_eu": VenueExecutionProfile(
        venue_key="betfair_ex_eu",
        odds_api_key="betfair_ex_eu",
        display_name="Betfair Exchange EU",
        primary_execution_method=ExecutionMethod.REST_API,
        api_base_url="https://api.betfair.com",
        api_docs_url="https://docs.developer.betfair.com/",
        credential_type=CredentialType.API_KEY,
        venue_category=VenueCategory.EXCHANGE,
        config_secret_field="betfair_secret_name",
        min_bet="2.00",
        commission_model="net_winnings_pct",
        available_countries=["ES", "IT", "PT", "RO"],
        withdrawal_delay_hours_min=24,
        withdrawal_delay_hours_max=72,
        commission_rate="5.0",
        min_bet_currency="GBP",
        withdrawal_fee="0",
    ),
    "betfair_ex_au": VenueExecutionProfile(
        venue_key="betfair_ex_au",
        odds_api_key="betfair_ex_au",
        display_name="Betfair Exchange AU",
        primary_execution_method=ExecutionMethod.REST_API,
        api_base_url="https://api.betfair.com",
        api_docs_url="https://docs.developer.betfair.com/",
        credential_type=CredentialType.API_KEY,
        venue_category=VenueCategory.EXCHANGE,
        config_secret_field="betfair_secret_name",
        min_bet="2.00",
        commission_model="net_winnings_pct",
        available_countries=["AU"],
        withdrawal_delay_hours_min=24,
        withdrawal_delay_hours_max=72,
        commission_rate="5.0",
        min_bet_currency="GBP",
        withdrawal_fee="0",
    ),
    "pinnacle": VenueExecutionProfile(
        venue_key="pinnacle",
        odds_api_key="pinnacle",
        display_name="Pinnacle",
        primary_execution_method=ExecutionMethod.REST_API,
        api_base_url="https://api.pinnacle.com",
        api_docs_url="https://pinnacleapi.github.io/",
        credential_type=CredentialType.API_KEY,
        venue_category=VenueCategory.BOOKMAKER_API,
        config_secret_field="pinnacle_secret_name",
        min_bet="1.00",
        commission_model="built_into_odds",
        available_countries=["US", "UK", "AU", "CA"],
        withdrawal_delay_hours_min=24,
        withdrawal_delay_hours_max=48,
        min_bet_currency="USD",
        withdrawal_fee="0",
    ),
    "smarkets": VenueExecutionProfile(
        venue_key="smarkets",
        odds_api_key="smarkets",
        display_name="Smarkets",
        primary_execution_method=ExecutionMethod.REST_API,
        api_base_url="https://api.smarkets.com/v3",
        api_docs_url="https://docs.smarkets.com/",
        credential_type=CredentialType.API_KEY,
        venue_category=VenueCategory.EXCHANGE,
        config_secret_field="smarkets_secret_name",
        min_bet="1.00",
        commission_model="net_winnings_pct",
        available_countries=["GB", "IE"],
        withdrawal_delay_hours_min=24,
        withdrawal_delay_hours_max=72,
        commission_rate="2.0",
        min_bet_currency="GBP",
        withdrawal_fee="0",
    ),
    "matchbook": VenueExecutionProfile(
        venue_key="matchbook",
        odds_api_key="matchbook",
        display_name="Matchbook",
        primary_execution_method=ExecutionMethod.REST_API,
        api_base_url="https://api.matchbook.com/edge/rest",
        api_docs_url="https://www.matchbook.com/edge/rest",
        credential_type=CredentialType.USERNAME_PASSWORD,
        venue_category=VenueCategory.EXCHANGE,
        config_secret_field="matchbook_secret_name",
        min_bet="5",
        commission_model="net_winnings_pct",
        available_countries=["GB", "IE"],
        withdrawal_delay_hours_min=24,
        withdrawal_delay_hours_max=72,
        commission_rate="1.5",
        min_bet_currency="GBP",
        withdrawal_fee="0",
    ),
    "betdaq": VenueExecutionProfile(
        venue_key="betdaq",
        odds_api_key=None,
        display_name="Betdaq",
        primary_execution_method=ExecutionMethod.REST_API,
        api_base_url="https://api.betdaq.com",
        api_docs_url="https://www.betdaq.com/",
        credential_type=CredentialType.USERNAME_PASSWORD,
        venue_category=VenueCategory.EXCHANGE,
        config_secret_field="betdaq_secret_name",
        min_bet="0.50",
        commission_model="net_winnings_pct",
        available_countries=["GB", "IE"],
        withdrawal_delay_hours_min=24,
        withdrawal_delay_hours_max=72,
        commission_rate="2.0",
        min_bet_currency="GBP",
        withdrawal_fee="0",
    ),
    # ── Prediction Markets / Crypto Exchanges (REST API) ─────────────────
    "polymarket": VenueExecutionProfile(
        venue_key="polymarket",
        odds_api_key="polymarket",
        display_name="Polymarket",
        parent_company="Polymarket Inc",
        venue_category=VenueCategory.EXCHANGE,
        primary_execution_method=ExecutionMethod.REST_API,
        credential_type=CredentialType.API_KEY_SECRET,
        api_base_url="https://clob.polymarket.com",
        api_docs_url="https://docs.polymarket.com",
        has_rest_api=True,
        api_rate_limit_requests_per_second=10,
        config_secret_field="polymarket_credentials",
        api_key_secret_key="api_key",
        headquarters_country="US",
        available_countries=["US", "GB", "EU"],
        blocked_us_states=["NY"],
        supported_currencies=["USDC"],
        min_deposit=Decimal("1"),
        min_bet=Decimal("1"),
        min_bet_currency="USDC",
        supports_crypto_deposit=True,
        supports_crypto_withdrawal=True,
        crypto_currencies_accepted=["USDC"],
        withdrawal_delay_hours_min=0,
        withdrawal_delay_hours_max=1,
        commission_model="maker_taker",
        commission_rate=Decimal("0"),
        commission_notes="0% maker, 0% taker on prediction markets",
        withdrawal_fee=Decimal("0"),
        limits_winning_accounts=False,
        notes="Prediction market exchange on Polygon. CLOB API with HMAC auth.",
    ),
    "kalshi": VenueExecutionProfile(
        venue_key="kalshi",
        odds_api_key="kalshi",
        display_name="Kalshi",
        parent_company="Kalshi Inc",
        venue_category=VenueCategory.EXCHANGE,
        primary_execution_method=ExecutionMethod.REST_API,
        credential_type=CredentialType.API_KEY_SECRET,
        api_base_url="https://trading-api.kalshi.com/trade-api/v2",
        api_docs_url="https://trading-api.kalshi.com/docs",
        has_rest_api=True,
        has_websocket_api=True,
        api_rate_limit_requests_per_second=10,
        config_secret_field="kalshi_credentials",
        api_key_secret_key="api_key",
        headquarters_country="US",
        license_jurisdictions=["US-CFTC"],
        available_countries=["US"],
        blocked_us_states=[],
        requires_residency=True,
        residency_countries=["US"],
        supported_currencies=["USD"],
        min_deposit=Decimal("1"),
        min_bet=Decimal("1"),
        min_bet_currency="USD",
        withdrawal_delay_hours_min=1,
        withdrawal_delay_hours_max=48,
        commission_model="maker_taker",
        commission_rate=Decimal("0"),
        commission_notes="No trading fees; exchange spread is the cost",
        withdrawal_fee=Decimal("0"),
        limits_winning_accounts=False,
        notes="CFTC-regulated event contracts exchange. REST + WebSocket API.",
    ),
    "novig": VenueExecutionProfile(
        venue_key="novig",
        odds_api_key="novig",
        display_name="Novig",
        parent_company="Novig Inc",
        venue_category=VenueCategory.EXCHANGE,
        primary_execution_method=ExecutionMethod.BROWSER_AUTOMATION,
        credential_type=CredentialType.USERNAME_PASSWORD,
        login_url="https://www.novig.com/",
        config_secret_field="novig_credentials",
        username_secret_key="username",
        password_secret_key="password",
        headquarters_country="US",
        available_us_states=["NJ", "CO", "IN", "IA", "KS", "KY", "LA", "MD", "OH", "PA", "VA"],
        requires_geolocation_check=True,
        geolocation_provider="geocomply",
        supported_currencies=["USD"],
        min_bet=Decimal("1"),
        min_bet_currency="USD",
        anti_detection_level=AntiDetectionLevel.MODERATE,
        commission_model="low_vig_exchange",
        commission_rate=Decimal("1.0"),
        commission_notes="Peer-to-peer exchange with ~1% vig; no traditional commission",
        withdrawal_fee=Decimal("0"),
        limits_winning_accounts=False,
        notes="US peer-to-peer sports exchange. Low vig model.",
    ),
    "betopenly": VenueExecutionProfile(
        venue_key="betopenly",
        odds_api_key="betopenly",
        display_name="BetOpenly",
        parent_company="BetOpenly Inc",
        venue_category=VenueCategory.EXCHANGE,
        primary_execution_method=ExecutionMethod.BROWSER_AUTOMATION,
        credential_type=CredentialType.USERNAME_PASSWORD,
        login_url="https://www.betopenly.com/",
        config_secret_field="betopenly_credentials",
        username_secret_key="username",
        password_secret_key="password",
        headquarters_country="US",
        requires_geolocation_check=True,
        supported_currencies=["USD"],
        min_bet=Decimal("1"),
        min_bet_currency="USD",
        anti_detection_level=AntiDetectionLevel.BASIC,
        commission_model="exchange_commission",
        commission_rate=Decimal("2.0"),
        withdrawal_fee=Decimal("0"),
        limits_winning_accounts=False,
        notes="US sports exchange.",
    ),
    "prophetx": VenueExecutionProfile(
        venue_key="prophetx",
        odds_api_key="prophetx",
        display_name="ProphetX",
        parent_company="Prophet Exchange",
        venue_category=VenueCategory.EXCHANGE,
        primary_execution_method=ExecutionMethod.BROWSER_AUTOMATION,
        credential_type=CredentialType.USERNAME_PASSWORD,
        login_url="https://www.prophetexchange.com/",
        config_secret_field="prophetx_credentials",
        username_secret_key="username",
        password_secret_key="password",
        headquarters_country="US",
        available_us_states=["NJ"],
        requires_geolocation_check=True,
        geolocation_provider="geocomply",
        supported_currencies=["USD"],
        min_bet=Decimal("1"),
        min_bet_currency="USD",
        anti_detection_level=AntiDetectionLevel.MODERATE,
        commission_model="exchange_commission",
        commission_rate=Decimal("2.0"),
        withdrawal_fee=Decimal("0"),
        limits_winning_accounts=False,
        notes="NJ-only peer-to-peer sports exchange.",
    ),
}
