"""League classification raw data - part A.

Contains the first half of LEAGUE_CLASSIFICATION_DATA entries (league IDs for
Tier 1 top leagues through Tier 4 divisions and Features second divisions
up to Brazil Serie B).

Split to stay under 900-line file limit.
Import via league_classification_data.py -- do not import directly.

Source: Ported from instruments-service/instruments_service/sports/
into UAC so all downstream consumers share a single SSOT.
"""

from __future__ import annotations

LEAGUE_CLASSIFICATION_DATA_A: dict[int, dict[str, str | int | bool | dict[str, bool] | None]] = {
    # =========================================================================
    # TIER 1: Top European leagues (Big 5)
    # =========================================================================
    39: {
        "country_region": "England",
        "api_football_id": 39,
        "api_football_league_name": "Premier League",
        "odds_api_league_name": "soccer_epl",
        "classification": "Prediction",
        "tier": 1,
        "data_sources": {
            "api_football": True,
            "soccerfootball_info": True,
            "footystats": True,
            "transfermarkt": True,
            "understat": True,
            "odds_api": True,
            "open_meteo": True,
        },
    },
    140: {
        "country_region": "Spain",
        "api_football_id": 140,
        "api_football_league_name": "La Liga",
        "odds_api_league_name": "soccer_spain_la_liga",
        "classification": "Prediction",
        "tier": 1,
        "data_sources": {
            "api_football": True,
            "soccerfootball_info": True,
            "footystats": True,
            "transfermarkt": True,
            "understat": True,
            "odds_api": True,
            "open_meteo": True,
        },
    },
    78: {
        "country_region": "Germany",
        "api_football_id": 78,
        "api_football_league_name": "Bundesliga",
        "odds_api_league_name": "soccer_germany_bundesliga",
        "classification": "Prediction",
        "tier": 1,
        "data_sources": {
            "api_football": True,
            "soccerfootball_info": True,
            "footystats": True,
            "transfermarkt": True,
            "understat": True,
            "odds_api": True,
            "open_meteo": True,
        },
    },
    135: {
        "country_region": "Italy",
        "api_football_id": 135,
        "api_football_league_name": "Serie A",
        "odds_api_league_name": "soccer_italy_serie_a",
        "classification": "Prediction",
        "tier": 1,
        "data_sources": {
            "api_football": True,
            "soccerfootball_info": True,
            "footystats": True,
            "transfermarkt": True,
            "understat": True,
            "odds_api": True,
            "open_meteo": True,
        },
    },
    61: {
        "country_region": "France",
        "api_football_id": 61,
        "api_football_league_name": "Ligue 1",
        "odds_api_league_name": "soccer_france_ligue_one",
        "classification": "Prediction",
        "tier": 1,
        "data_sources": {
            "api_football": True,
            "soccerfootball_info": True,
            "footystats": True,
            "transfermarkt": True,
            "understat": True,
            "odds_api": True,
            "open_meteo": True,
        },
    },
    # =========================================================================
    # TIER 1: Other European leagues
    # =========================================================================
    88: {
        "country_region": "Netherlands",
        "api_football_id": 88,
        "api_football_league_name": "Eredivisie",
        "odds_api_league_name": "soccer_netherlands_eredivisie",
        "classification": "Prediction",
        "tier": 1,
        "data_sources": {
            "api_football": True,
            "soccerfootball_info": True,
            "footystats": True,
            "transfermarkt": True,
            "understat": False,
            "odds_api": True,
            "open_meteo": True,
        },
    },
    94: {
        "country_region": "Portugal",
        "api_football_id": 94,
        "api_football_league_name": "Primeira Liga",
        "odds_api_league_name": "soccer_portugal_primeira_liga",
        "classification": "Prediction",
        "tier": 1,
        "data_sources": {
            "api_football": True,
            "soccerfootball_info": True,
            "footystats": True,
            "transfermarkt": True,
            "understat": False,
            "odds_api": True,
            "open_meteo": True,
        },
    },
    144: {
        "country_region": "Belgium",
        "api_football_id": 144,
        "api_football_league_name": "First Division A",
        "odds_api_league_name": "soccer_belgium_first_div",
        "classification": "Prediction",
        "tier": 1,
        "data_sources": {
            "api_football": True,
            "soccerfootball_info": True,
            "footystats": True,
            "transfermarkt": True,
            "understat": False,
            "odds_api": True,
            "open_meteo": True,
        },
    },
    203: {
        "country_region": "Turkey",
        "api_football_id": 203,
        "api_football_league_name": "Super Lig",
        "odds_api_league_name": "soccer_turkey_super_league",
        "classification": "Prediction",
        "tier": 1,
        "data_sources": {
            "api_football": True,
            "soccerfootball_info": True,
            "footystats": True,
            "transfermarkt": True,
            "understat": False,
            "odds_api": True,
            "open_meteo": True,
        },
    },
    179: {
        "country_region": "Scotland",
        "api_football_id": 179,
        "api_football_league_name": "Premiership",
        "odds_api_league_name": "soccer_spl",
        "classification": "Prediction",
        "tier": 1,
        "data_sources": {
            "api_football": True,
            "soccerfootball_info": True,
            "footystats": True,
            "transfermarkt": True,
            "understat": False,
            "odds_api": True,
            "open_meteo": True,
        },
    },
    197: {
        "country_region": "Greece",
        "api_football_id": 197,
        "api_football_league_name": "Super League",
        "odds_api_league_name": "soccer_greece_super_league",
        "classification": "Prediction",
        "tier": 1,
        "data_sources": {
            "api_football": True,
            "soccerfootball_info": True,
            "footystats": True,
            "transfermarkt": True,
            "understat": False,
            "odds_api": True,
            "open_meteo": True,
        },
    },
    218: {
        "country_region": "Austria",
        "api_football_id": 218,
        "api_football_league_name": "Bundesliga",
        "odds_api_league_name": "soccer_austria_bundesliga",
        "classification": "Prediction",
        "tier": 1,
        "data_sources": {
            "api_football": True,
            "soccerfootball_info": True,
            "footystats": True,
            "transfermarkt": True,
            "understat": False,
            "odds_api": True,
            "open_meteo": True,
        },
    },
    207: {
        "country_region": "Switzerland",
        "api_football_id": 207,
        "api_football_league_name": "Super League",
        "odds_api_league_name": "soccer_switzerland_superleague",
        "classification": "Prediction",
        "tier": 1,
        "data_sources": {
            "api_football": True,
            "soccerfootball_info": True,
            "footystats": True,
            "transfermarkt": True,
            "understat": False,
            "odds_api": True,
            "open_meteo": True,
        },
    },
    119: {
        "country_region": "Denmark",
        "api_football_id": 119,
        "api_football_league_name": "Superliga",
        "odds_api_league_name": "soccer_denmark_superliga",
        "classification": "Prediction",
        "tier": 1,
        "data_sources": {
            "api_football": True,
            "soccerfootball_info": True,
            "footystats": True,
            "transfermarkt": True,
            "understat": False,
            "odds_api": True,
            "open_meteo": True,
        },
    },
    103: {
        "country_region": "Norway",
        "api_football_id": 103,
        "api_football_league_name": "Eliteserien",
        "odds_api_league_name": "soccer_norway_eliteserien",
        "classification": "Prediction",
        "tier": 1,
        "data_sources": {
            "api_football": True,
            "soccerfootball_info": True,
            "footystats": True,
            "transfermarkt": True,
            "understat": False,
            "odds_api": True,
            "open_meteo": True,
        },
    },
    106: {
        "country_region": "Poland",
        "api_football_id": 106,
        "api_football_league_name": "Ekstraklasa",
        "odds_api_league_name": "soccer_poland_ekstraklasa",
        "classification": "Prediction",
        "tier": 1,
        "data_sources": {
            "api_football": True,
            "soccerfootball_info": True,
            "footystats": True,
            "transfermarkt": True,
            "understat": False,
            "odds_api": True,
            "open_meteo": True,
        },
    },
    113: {
        "country_region": "Sweden",
        "api_football_id": 113,
        "api_football_league_name": "Allsvenskan",
        "odds_api_league_name": "soccer_sweden_allsvenskan",
        "classification": "Prediction",
        "tier": 1,
        "data_sources": {
            "api_football": True,
            "soccerfootball_info": True,
            "footystats": True,
            "transfermarkt": True,
            "understat": False,
            "odds_api": True,
            "open_meteo": True,
        },
    },
    # =========================================================================
    # TIER 1: Americas / Asia / Oceania
    # =========================================================================
    71: {
        "country_region": "Brazil",
        "api_football_id": 71,
        "api_football_league_name": "Serie A",
        "odds_api_league_name": "soccer_brazil_campeonato",
        "classification": "Prediction",
        "tier": 1,
        "data_sources": {
            "api_football": True,
            "soccerfootball_info": True,
            "footystats": True,
            "transfermarkt": True,
            "understat": False,
            "odds_api": True,
            "open_meteo": True,
        },
    },
    128: {
        "country_region": "Argentina",
        "api_football_id": 128,
        "api_football_league_name": "Primera Division",
        "odds_api_league_name": "soccer_argentina_primera_division",
        "classification": "Prediction",
        "tier": 1,
        "data_sources": {
            "api_football": True,
            "soccerfootball_info": True,
            "footystats": False,
            "transfermarkt": True,
            "understat": False,
            "odds_api": True,
            "open_meteo": True,
        },
    },
    253: {
        "country_region": "USA",
        "api_football_id": 253,
        "api_football_league_name": "MLS",
        "odds_api_league_name": "soccer_usa_mls",
        "classification": "Prediction",
        "tier": 1,
        "data_sources": {
            "api_football": True,
            "soccerfootball_info": True,
            "footystats": True,
            "transfermarkt": True,
            "understat": False,
            "odds_api": True,
            "open_meteo": True,
        },
    },
    98: {
        "country_region": "Japan",
        "api_football_id": 98,
        "api_football_league_name": "J1 League",
        "odds_api_league_name": "soccer_japan_j_league",
        "classification": "Prediction",
        "tier": 1,
        "data_sources": {
            "api_football": True,
            "soccerfootball_info": True,
            "footystats": True,
            "transfermarkt": True,
            "understat": False,
            "odds_api": True,
            "open_meteo": True,
        },
    },
    265: {
        "country_region": "Chile",
        "api_football_id": 265,
        "api_football_league_name": "Primera Division",
        "odds_api_league_name": "soccer_chile_campeonato",
        "classification": "Prediction",
        "tier": 1,
        "data_sources": {
            "api_football": True,
            "soccerfootball_info": True,
            "footystats": False,
            "transfermarkt": True,
            "understat": False,
            "odds_api": True,
            "open_meteo": True,
        },
    },
    262: {
        "country_region": "Mexico",
        "api_football_id": 262,
        "api_football_league_name": "Liga MX",
        "odds_api_league_name": "soccer_mexico_ligamx",
        "classification": "Prediction",
        "tier": 1,
        "data_sources": {
            "api_football": True,
            "soccerfootball_info": True,
            "footystats": False,
            "transfermarkt": True,
            "understat": False,
            "odds_api": True,
            "open_meteo": True,
        },
    },
    292: {
        "country_region": "South Korea",
        "api_football_id": 292,
        "api_football_league_name": "K League 1",
        "odds_api_league_name": "soccer_korea_kleague1",
        "classification": "Prediction",
        "tier": 1,
        "data_sources": {
            "api_football": True,
            "soccerfootball_info": True,
            "footystats": False,
            "transfermarkt": True,
            "understat": False,
            "odds_api": True,
            "open_meteo": True,
        },
    },
    188: {
        "country_region": "Australia",
        "api_football_id": 188,
        "api_football_league_name": "A-League",
        "odds_api_league_name": "soccer_australia_aleague",
        "classification": "Prediction",
        "tier": 1,
        "data_sources": {
            "api_football": True,
            "soccerfootball_info": True,
            "footystats": False,
            "transfermarkt": True,
            "understat": False,
            "odds_api": True,
            "open_meteo": True,
        },
    },
    # =========================================================================
    # TIER 2: Second divisions (Big 5)
    # =========================================================================
    40: {
        "country_region": "England",
        "api_football_id": 40,
        "api_football_league_name": "Championship",
        "odds_api_league_name": "soccer_efl_champ",
        "classification": "Prediction",
        "tier": 2,
        "data_sources": {
            "api_football": True,
            "soccerfootball_info": True,
            "footystats": True,
            "transfermarkt": True,
            "understat": False,
            "odds_api": True,
            "open_meteo": True,
        },
    },
    141: {
        "country_region": "Spain",
        "api_football_id": 141,
        "api_football_league_name": "Segunda Division",
        "odds_api_league_name": "soccer_spain_segunda_division",
        "classification": "Prediction",
        "tier": 2,
        "data_sources": {
            "api_football": True,
            "soccerfootball_info": True,
            "footystats": True,
            "transfermarkt": True,
            "understat": False,
            "odds_api": True,
            "open_meteo": True,
        },
    },
    79: {
        "country_region": "Germany",
        "api_football_id": 79,
        "api_football_league_name": "2. Bundesliga",
        "odds_api_league_name": "soccer_germany_bundesliga2",
        "classification": "Prediction",
        "tier": 2,
        "data_sources": {
            "api_football": True,
            "soccerfootball_info": True,
            "footystats": True,
            "transfermarkt": True,
            "understat": False,
            "odds_api": True,
            "open_meteo": True,
        },
    },
    136: {
        "country_region": "Italy",
        "api_football_id": 136,
        "api_football_league_name": "Serie B",
        "odds_api_league_name": "soccer_italy_serie_b",
        "classification": "Prediction",
        "tier": 2,
        "data_sources": {
            "api_football": True,
            "soccerfootball_info": True,
            "footystats": True,
            "transfermarkt": True,
            "understat": False,
            "odds_api": True,
            "open_meteo": True,
        },
    },
    62: {
        "country_region": "France",
        "api_football_id": 62,
        "api_football_league_name": "Ligue 2",
        "odds_api_league_name": "soccer_france_ligue_two",
        "classification": "Prediction",
        "tier": 2,
        "data_sources": {
            "api_football": True,
            "soccerfootball_info": True,
            "footystats": True,
            "transfermarkt": True,
            "understat": False,
            "odds_api": True,
            "open_meteo": True,
        },
    },
    # =========================================================================
    # TIER 3: Third divisions
    # =========================================================================
    80: {
        "country_region": "Germany",
        "api_football_id": 80,
        "api_football_league_name": "3. Liga",
        "odds_api_league_name": "soccer_germany_liga3",
        "classification": "Prediction",
        "tier": 3,
        "data_sources": {
            "api_football": True,
            "soccerfootball_info": True,
            "footystats": True,
            "transfermarkt": True,
            "understat": False,
            "odds_api": True,
            "open_meteo": True,
        },
    },
    41: {
        "country_region": "England",
        "api_football_id": 41,
        "api_football_league_name": "League One",
        "odds_api_league_name": "soccer_england_league1",
        "classification": "Prediction",
        "tier": 3,
        "data_sources": {
            "api_football": True,
            "soccerfootball_info": True,
            "footystats": True,
            "transfermarkt": True,
            "understat": False,
            "odds_api": True,
            "open_meteo": True,
        },
    },
    # =========================================================================
    # TIER 4: Fourth divisions
    # =========================================================================
    42: {
        "country_region": "England",
        "api_football_id": 42,
        "api_football_league_name": "League Two",
        "odds_api_league_name": "soccer_england_league2",
        "classification": "Prediction",
        "tier": 4,
        "data_sources": {
            "api_football": True,
            "soccerfootball_info": True,
            "footystats": True,
            "transfermarkt": True,
            "understat": False,
            "odds_api": True,
            "open_meteo": True,
        },
    },
    # =========================================================================
    # FEATURES: Second divisions with limited data coverage
    # =========================================================================
    89: {
        "country_region": "Netherlands",
        "api_football_id": 89,
        "api_football_league_name": "Eerste Divisie",
        "odds_api_league_name": None,
        "classification": "Features",
        "tier": 2,
        "data_sources": {
            "api_football": True,
            "soccerfootball_info": False,
            "footystats": True,
            "transfermarkt": True,
            "understat": False,
            "odds_api": False,
            "open_meteo": False,
        },
    },
    95: {
        "country_region": "Portugal",
        "api_football_id": 95,
        "api_football_league_name": "Liga Portugal 2",
        "odds_api_league_name": None,
        "classification": "Features",
        "tier": 2,
        "data_sources": {
            "api_football": True,
            "soccerfootball_info": False,
            "footystats": True,
            "transfermarkt": True,
            "understat": False,
            "odds_api": False,
            "open_meteo": False,
        },
    },
    145: {
        "country_region": "Belgium",
        "api_football_id": 145,
        "api_football_league_name": "First Division B",
        "odds_api_league_name": None,
        "classification": "Features",
        "tier": 2,
        "data_sources": {
            "api_football": True,
            "soccerfootball_info": False,
            "footystats": True,
            "transfermarkt": True,
            "understat": False,
            "odds_api": False,
            "open_meteo": False,
        },
    },
    204: {
        "country_region": "Turkey",
        "api_football_id": 204,
        "api_football_league_name": "TFF First League",
        "odds_api_league_name": None,
        "classification": "Features",
        "tier": 2,
        "data_sources": {
            "api_football": True,
            "soccerfootball_info": False,
            "footystats": True,
            "transfermarkt": True,
            "understat": False,
            "odds_api": False,
            "open_meteo": False,
        },
    },
    198: {
        "country_region": "Greece",
        "api_football_id": 198,
        "api_football_league_name": "Super League 2",
        "odds_api_league_name": None,
        "classification": "Features",
        "tier": 2,
        "data_sources": {
            "api_football": True,
            "soccerfootball_info": False,
            "footystats": True,
            "transfermarkt": True,
            "understat": False,
            "odds_api": False,
            "open_meteo": False,
        },
    },
    180: {
        "country_region": "Scotland",
        "api_football_id": 180,
        "api_football_league_name": "Championship",
        "odds_api_league_name": None,
        "classification": "Features",
        "tier": 2,
        "data_sources": {
            "api_football": True,
            "soccerfootball_info": False,
            "footystats": True,
            "transfermarkt": True,
            "understat": False,
            "odds_api": False,
            "open_meteo": False,
        },
    },
    219: {
        "country_region": "Austria",
        "api_football_id": 219,
        "api_football_league_name": "2. Liga",
        "odds_api_league_name": None,
        "classification": "Features",
        "tier": 2,
        "data_sources": {
            "api_football": True,
            "soccerfootball_info": False,
            "footystats": True,
            "transfermarkt": True,
            "understat": False,
            "odds_api": False,
            "open_meteo": False,
        },
    },
    208: {
        "country_region": "Switzerland",
        "api_football_id": 208,
        "api_football_league_name": "Challenge League",
        "odds_api_league_name": None,
        "classification": "Features",
        "tier": 2,
        "data_sources": {
            "api_football": True,
            "soccerfootball_info": False,
            "footystats": True,
            "transfermarkt": True,
            "understat": False,
            "odds_api": False,
            "open_meteo": False,
        },
    },
    120: {
        "country_region": "Denmark",
        "api_football_id": 120,
        "api_football_league_name": "1st Division",
        "odds_api_league_name": None,
        "classification": "Features",
        "tier": 2,
        "data_sources": {
            "api_football": True,
            "soccerfootball_info": False,
            "footystats": True,
            "transfermarkt": True,
            "understat": False,
            "odds_api": False,
            "open_meteo": False,
        },
    },
    104: {
        "country_region": "Norway",
        "api_football_id": 104,
        "api_football_league_name": "1. divisjon",
        "odds_api_league_name": None,
        "classification": "Features",
        "tier": 2,
        "data_sources": {
            "api_football": True,
            "soccerfootball_info": False,
            "footystats": True,
            "transfermarkt": True,
            "understat": False,
            "odds_api": False,
            "open_meteo": False,
        },
    },
    107: {
        "country_region": "Poland",
        "api_football_id": 107,
        "api_football_league_name": "I Liga",
        "odds_api_league_name": None,
        "classification": "Features",
        "tier": 2,
        "data_sources": {
            "api_football": True,
            "soccerfootball_info": False,
            "footystats": True,
            "transfermarkt": True,
            "understat": False,
            "odds_api": False,
            "open_meteo": False,
        },
    },
    114: {
        "country_region": "Sweden",
        "api_football_id": 114,
        "api_football_league_name": "Superettan",
        "odds_api_league_name": None,
        "classification": "Features",
        "tier": 2,
        "data_sources": {
            "api_football": True,
            "soccerfootball_info": False,
            "footystats": True,
            "transfermarkt": True,
            "understat": False,
            "odds_api": False,
            "open_meteo": False,
        },
    },
    255: {
        "country_region": "USA",
        "api_football_id": 255,
        "api_football_league_name": "USL Championship",
        "odds_api_league_name": None,
        "classification": "Features",
        "tier": 2,
        "data_sources": {
            "api_football": True,
            "soccerfootball_info": False,
            "footystats": True,
            "transfermarkt": True,
            "understat": False,
            "odds_api": False,
            "open_meteo": False,
        },
    },
    # =========================================================================
    # FEATURES: Second divisions (Americas / Asia) -- limited data
    # =========================================================================
    129: {
        "country_region": "Argentina",
        "api_football_id": 129,
        "api_football_league_name": "Primera Nacional",
        "odds_api_league_name": None,
        "classification": "Features",
        "tier": 2,
        "data_sources": {
            "api_football": True,
            "soccerfootball_info": False,
            "footystats": False,
            "transfermarkt": True,
            "understat": False,
            "odds_api": False,
            "open_meteo": False,
        },
    },
    72: {
        "country_region": "Brazil",
        "api_football_id": 72,
        "api_football_league_name": "Serie B",
        "odds_api_league_name": None,
        "classification": "Features",
        "tier": 2,
        "data_sources": {
            "api_football": True,
            "soccerfootball_info": False,
            "footystats": True,
            "transfermarkt": True,
            "understat": False,
            "odds_api": False,
            "open_meteo": False,
        },
    },
}

__all__ = ["LEAGUE_CLASSIFICATION_DATA_A"]
