"""Bookmaker registry data — auto-extracted from sports.py for file-size compliance."""

from __future__ import annotations

from decimal import Decimal

from unified_api_contracts.canonical.domain.sports import BookmakerCategory, BookmakerInfo

BOOKMAKER_REGISTRY: dict[str, BookmakerInfo] = {
    "betfair": BookmakerInfo(
        key="betfair",
        display_name="Betfair Exchange",
        category=BookmakerCategory.EXCHANGE,
        currency="GBP",
        supports_live_betting=True,
        supports_cash_out=True,
        min_bet_gbp=Decimal("2.00"),
        api_docs_url="https://docs.developer.betfair.com/",
    ),
    "smarkets": BookmakerInfo(
        key="smarkets",
        display_name="Smarkets Exchange",
        category=BookmakerCategory.EXCHANGE,
        currency="GBP",
        supports_live_betting=True,
        supports_cash_out=False,
        min_bet_gbp=Decimal("1.00"),
        api_docs_url="https://docs.smarkets.com/",
    ),
    "matchbook": BookmakerInfo(
        key="matchbook",
        display_name="Matchbook Exchange",
        category=BookmakerCategory.EXCHANGE,
        currency="GBP",
        supports_live_betting=True,
        supports_cash_out=False,
        min_bet_gbp=Decimal("0.10"),
        api_docs_url="https://www.matchbook.com/edge/rest",
    ),
    "betdaq": BookmakerInfo(
        key="betdaq",
        display_name="Betdaq Exchange",
        category=BookmakerCategory.EXCHANGE,
        currency="GBP",
        supports_live_betting=True,
        supports_cash_out=False,
        min_bet_gbp=Decimal("0.50"),
        api_docs_url="https://www.betdaq.com/",
    ),
    "pinnacle": BookmakerInfo(
        key="pinnacle",
        display_name="Pinnacle",
        category=BookmakerCategory.BOOKMAKER_API,
        currency="USD",
        supports_live_betting=True,
        supports_cash_out=False,
        min_bet_gbp=Decimal("1.00"),
        max_bet_gbp=Decimal("50000.00"),
        api_docs_url="https://pinnacleapi.github.io/",
    ),
    "onexbet": BookmakerInfo(
        key="onexbet",
        display_name="1xBet",
        category=BookmakerCategory.BOOKMAKER_API,
        currency="EUR",
        supports_live_betting=True,
        supports_cash_out=True,
        min_bet_gbp=Decimal("0.20"),
        max_bet_gbp=Decimal("10000.00"),
    ),
    "odds_api": BookmakerInfo(
        key="odds_api",
        display_name="The Odds API",
        category=BookmakerCategory.AGGREGATOR,
        currency="USD",
        supports_live_betting=False,
        supports_cash_out=False,
        min_bet_gbp=Decimal("0.00"),
        api_docs_url="https://the-odds-api.com/liveapi/guides/v4/",
    ),
    "opticodds": BookmakerInfo(
        key="opticodds",
        display_name="OpticOdds",
        category=BookmakerCategory.STREAMING_API,
        currency="USD",
        supports_live_betting=False,
        supports_cash_out=False,
        min_bet_gbp=Decimal("0.00"),
        api_docs_url="https://docs.opticodds.com/",
    ),
    "oddsjam": BookmakerInfo(
        key="oddsjam",
        display_name="OddsJam",
        category=BookmakerCategory.STREAMING_API,
        currency="USD",
        supports_live_betting=False,
        supports_cash_out=False,
        min_bet_gbp=Decimal("0.00"),
        api_docs_url="https://developer.oddsjam.com/",
    ),
    "skybet": BookmakerInfo(
        key="skybet",
        display_name="Sky Bet",
        category=BookmakerCategory.SCRAPER,
        currency="GBP",
        supports_live_betting=True,
        supports_cash_out=True,
        min_bet_gbp=Decimal("0.10"),
        max_bet_gbp=Decimal("10000.00"),
        scrape_url="https://www.skybet.com/",
    ),
    "coral": BookmakerInfo(
        key="coral",
        display_name="Coral",
        category=BookmakerCategory.SCRAPER,
        currency="GBP",
        supports_live_betting=True,
        supports_cash_out=True,
        min_bet_gbp=Decimal("0.10"),
        max_bet_gbp=Decimal("50000.00"),
        scrape_url="https://www.coral.co.uk/",
    ),
    "paddypower": BookmakerInfo(
        key="paddypower",
        display_name="Paddy Power",
        category=BookmakerCategory.SCRAPER,
        currency="GBP",
        supports_live_betting=True,
        supports_cash_out=True,
        min_bet_gbp=Decimal("0.10"),
        max_bet_gbp=Decimal("50000.00"),
        scrape_url="https://www.paddypower.com/",
    ),
    "betfred": BookmakerInfo(
        key="betfred",
        display_name="Betfred",
        category=BookmakerCategory.SCRAPER,
        currency="GBP",
        supports_live_betting=True,
        supports_cash_out=True,
        min_bet_gbp=Decimal("0.10"),
        max_bet_gbp=Decimal("25000.00"),
        scrape_url="https://www.betfred.com/",
    ),
    "betvictor": BookmakerInfo(
        key="betvictor",
        display_name="BetVictor",
        category=BookmakerCategory.SCRAPER,
        currency="GBP",
        supports_live_betting=True,
        supports_cash_out=True,
        min_bet_gbp=Decimal("0.10"),
        max_bet_gbp=Decimal("25000.00"),
        scrape_url="https://www.betvictor.com/",
    ),
    "boylesports": BookmakerInfo(
        key="boylesports",
        display_name="BoyleSports",
        category=BookmakerCategory.SCRAPER,
        currency="GBP",
        supports_live_betting=True,
        supports_cash_out=True,
        min_bet_gbp=Decimal("0.10"),
        max_bet_gbp=Decimal("10000.00"),
        scrape_url="https://www.boylesports.com/",
    ),
    "bwin": BookmakerInfo(
        key="bwin",
        display_name="bwin",
        category=BookmakerCategory.SCRAPER,
        currency="EUR",
        supports_live_betting=True,
        supports_cash_out=True,
        min_bet_gbp=Decimal("0.10"),
        max_bet_gbp=Decimal("25000.00"),
        scrape_url="https://www.bwin.com/",
    ),
    "ladbrokes": BookmakerInfo(
        key="ladbrokes",
        display_name="Ladbrokes",
        category=BookmakerCategory.SCRAPER,
        currency="GBP",
        supports_live_betting=True,
        supports_cash_out=True,
        min_bet_gbp=Decimal("0.10"),
        max_bet_gbp=Decimal("50000.00"),
        scrape_url="https://www.ladbrokes.com/",
    ),
    "williamhill": BookmakerInfo(
        key="williamhill",
        display_name="William Hill",
        category=BookmakerCategory.SCRAPER,
        currency="GBP",
        supports_live_betting=True,
        supports_cash_out=True,
        min_bet_gbp=Decimal("0.10"),
        max_bet_gbp=Decimal("50000.00"),
        scrape_url="https://www.williamhill.com/",
    ),
    "betway": BookmakerInfo(
        key="betway",
        display_name="Betway",
        category=BookmakerCategory.SCRAPER,
        currency="GBP",
        supports_live_betting=True,
        supports_cash_out=True,
        min_bet_gbp=Decimal("0.10"),
        max_bet_gbp=Decimal("25000.00"),
        scrape_url="https://www.betway.com/",
    ),
    "unibet": BookmakerInfo(
        key="unibet",
        display_name="Unibet",
        category=BookmakerCategory.SCRAPER,
        currency="GBP",
        supports_live_betting=True,
        supports_cash_out=True,
        min_bet_gbp=Decimal("0.10"),
        max_bet_gbp=Decimal("25000.00"),
        scrape_url="https://www.unibet.co.uk/",
    ),
    "bet888sport": BookmakerInfo(
        key="bet888sport",
        display_name="888sport",
        category=BookmakerCategory.SCRAPER,
        currency="GBP",
        supports_live_betting=True,
        supports_cash_out=True,
        min_bet_gbp=Decimal("0.10"),
        max_bet_gbp=Decimal("25000.00"),
        scrape_url="https://www.888sport.com/",
    ),
    "bet365": BookmakerInfo(
        key="bet365",
        display_name="Bet365",
        category=BookmakerCategory.SCRAPER,
        currency="GBP",
        supports_live_betting=True,
        supports_cash_out=True,
        min_bet_gbp=Decimal("0.10"),
        max_bet_gbp=Decimal("50000.00"),
        scrape_url="https://www.bet365.com/",
    ),
    "sbo": BookmakerInfo(
        key="sbo",
        display_name="SBOBet",
        category=BookmakerCategory.SCRAPER,
        currency="USD",
        supports_live_betting=True,
        supports_cash_out=True,
        min_bet_gbp=Decimal("0.10"),
        max_bet_gbp=Decimal("100000.00"),
        scrape_url="https://www.sbobet.com/",
    ),
    # Prediction Markets
    "polymarket": BookmakerInfo(
        key="polymarket",
        display_name="Polymarket",
        category=BookmakerCategory.EXCHANGE,
        currency="USD",
        supports_live_betting=True,
        supports_cash_out=False,
        min_bet_gbp=Decimal("1.00"),
        api_docs_url="https://docs.polymarket.com/",
    ),
    "kalshi": BookmakerInfo(
        key="kalshi",
        display_name="Kalshi",
        category=BookmakerCategory.EXCHANGE,
        currency="USD",
        supports_live_betting=True,
        supports_cash_out=False,
        min_bet_gbp=Decimal("1.00"),
        api_docs_url="https://trading-api.readme.io/",
    ),
    "novig": BookmakerInfo(
        key="novig",
        display_name="Novig",
        category=BookmakerCategory.EXCHANGE,
        currency="USD",
        supports_live_betting=True,
        supports_cash_out=False,
        min_bet_gbp=Decimal("1.00"),
        scrape_url="https://www.novig.us/",
    ),
    "betopenly": BookmakerInfo(
        key="betopenly",
        display_name="BetOpenly",
        category=BookmakerCategory.EXCHANGE,
        currency="USD",
        supports_live_betting=True,
        supports_cash_out=False,
        min_bet_gbp=Decimal("1.00"),
        scrape_url="https://app.betopenly.com/",
    ),
    "prophetx": BookmakerInfo(
        key="prophetx",
        display_name="ProphetX",
        category=BookmakerCategory.EXCHANGE,
        currency="USD",
        supports_live_betting=True,
        supports_cash_out=False,
        min_bet_gbp=Decimal("1.00"),
        scrape_url="https://www.prophetx.co/",
    ),
    # US Sportsbooks
    "draftkings": BookmakerInfo(
        key="draftkings",
        display_name="DraftKings",
        category=BookmakerCategory.SCRAPER,
        currency="USD",
        supports_live_betting=True,
        supports_cash_out=True,
        min_bet_gbp=Decimal("0.50"),
        max_bet_gbp=Decimal("50000.00"),
        scrape_url="https://www.draftkings.com/",
    ),
    "fanduel": BookmakerInfo(
        key="fanduel",
        display_name="FanDuel",
        category=BookmakerCategory.SCRAPER,
        currency="USD",
        supports_live_betting=True,
        supports_cash_out=True,
        min_bet_gbp=Decimal("0.50"),
        max_bet_gbp=Decimal("50000.00"),
        scrape_url="https://sportsbook.fanduel.com/",
    ),
    "betmgm": BookmakerInfo(
        key="betmgm",
        display_name="BetMGM",
        category=BookmakerCategory.SCRAPER,
        currency="USD",
        supports_live_betting=True,
        supports_cash_out=True,
        min_bet_gbp=Decimal("0.50"),
        max_bet_gbp=Decimal("25000.00"),
        scrape_url="https://sports.betmgm.com/",
    ),
    "bovada": BookmakerInfo(
        key="bovada",
        display_name="Bovada",
        category=BookmakerCategory.SCRAPER,
        currency="USD",
        supports_live_betting=True,
        supports_cash_out=True,
        min_bet_gbp=Decimal("0.50"),
        max_bet_gbp=Decimal("25000.00"),
        scrape_url="https://www.bovada.lv/",
    ),
    "caesars": BookmakerInfo(
        key="caesars",
        display_name="Caesars Sportsbook",
        category=BookmakerCategory.SCRAPER,
        currency="USD",
        supports_live_betting=True,
        supports_cash_out=True,
        min_bet_gbp=Decimal("0.50"),
        max_bet_gbp=Decimal("25000.00"),
        scrape_url="https://www.caesars.com/sportsbook-and-casino",
    ),
    "betrivers": BookmakerInfo(
        key="betrivers",
        display_name="BetRivers",
        category=BookmakerCategory.SCRAPER,
        currency="USD",
        supports_live_betting=True,
        supports_cash_out=True,
        min_bet_gbp=Decimal("0.50"),
        max_bet_gbp=Decimal("10000.00"),
        scrape_url="https://www.betrivers.com/",
    ),
    "betonlineag": BookmakerInfo(
        key="betonlineag",
        display_name="BetOnline.ag",
        category=BookmakerCategory.SCRAPER,
        currency="USD",
        supports_live_betting=True,
        supports_cash_out=False,
        min_bet_gbp=Decimal("1.00"),
        max_bet_gbp=Decimal("25000.00"),
        scrape_url="https://www.betonline.ag/",
    ),
    "betus": BookmakerInfo(
        key="betus",
        display_name="BetUS",
        category=BookmakerCategory.SCRAPER,
        currency="USD",
        supports_live_betting=True,
        supports_cash_out=False,
        min_bet_gbp=Decimal("1.00"),
        max_bet_gbp=Decimal("10000.00"),
        scrape_url="https://www.betus.com.pa/",
    ),
    "lowvig": BookmakerInfo(
        key="lowvig",
        display_name="LowVig.ag",
        category=BookmakerCategory.SCRAPER,
        currency="USD",
        supports_live_betting=True,
        supports_cash_out=False,
        min_bet_gbp=Decimal("1.00"),
        max_bet_gbp=Decimal("10000.00"),
        scrape_url="https://www.lowvig.ag/",
    ),
    "mybookieag": BookmakerInfo(
        key="mybookieag",
        display_name="MyBookie.ag",
        category=BookmakerCategory.SCRAPER,
        currency="USD",
        supports_live_betting=True,
        supports_cash_out=False,
        min_bet_gbp=Decimal("1.00"),
        max_bet_gbp=Decimal("10000.00"),
        scrape_url="https://mybookie.ag/",
    ),
    "fanatics": BookmakerInfo(
        key="fanatics",
        display_name="Fanatics Sportsbook",
        category=BookmakerCategory.SCRAPER,
        currency="USD",
        supports_live_betting=True,
        supports_cash_out=True,
        min_bet_gbp=Decimal("0.50"),
        max_bet_gbp=Decimal("25000.00"),
        scrape_url="https://sportsbook.fanatics.com/",
    ),
    "ballybet": BookmakerInfo(
        key="ballybet",
        display_name="Bally Bet",
        category=BookmakerCategory.SCRAPER,
        currency="USD",
        supports_live_betting=True,
        supports_cash_out=False,
        min_bet_gbp=Decimal("0.50"),
        max_bet_gbp=Decimal("10000.00"),
        scrape_url="https://play.ballybet.com/",
    ),
    "betanysports": BookmakerInfo(
        key="betanysports",
        display_name="BetAnySports",
        category=BookmakerCategory.SCRAPER,
        currency="USD",
        supports_live_betting=True,
        supports_cash_out=False,
        min_bet_gbp=Decimal("1.00"),
        max_bet_gbp=Decimal("10000.00"),
        scrape_url="https://betanything.eu/",
    ),
    "betparx": BookmakerInfo(
        key="betparx",
        display_name="betPARX",
        category=BookmakerCategory.SCRAPER,
        currency="USD",
        supports_live_betting=True,
        supports_cash_out=False,
        min_bet_gbp=Decimal("0.50"),
        max_bet_gbp=Decimal("10000.00"),
        scrape_url="https://betparx.com/",
    ),
    "espnbet": BookmakerInfo(
        key="espnbet",
        display_name="ESPN Bet",
        category=BookmakerCategory.SCRAPER,
        currency="USD",
        supports_live_betting=True,
        supports_cash_out=True,
        min_bet_gbp=Decimal("0.50"),
        max_bet_gbp=Decimal("25000.00"),
        scrape_url="https://sportsbook.thescore.bet/",
    ),
    "fliff": BookmakerInfo(
        key="fliff",
        display_name="Fliff",
        category=BookmakerCategory.SCRAPER,
        currency="USD",
        supports_live_betting=True,
        supports_cash_out=False,
        min_bet_gbp=Decimal("0.50"),
        max_bet_gbp=Decimal("5000.00"),
        scrape_url="https://www.getfliff.com/",
    ),
    "hardrockbet": BookmakerInfo(
        key="hardrockbet",
        display_name="Hard Rock Bet",
        category=BookmakerCategory.SCRAPER,
        currency="USD",
        supports_live_betting=True,
        supports_cash_out=True,
        min_bet_gbp=Decimal("0.50"),
        max_bet_gbp=Decimal("10000.00"),
        scrape_url="https://app.hardrock.bet/",
    ),
    "rebet": BookmakerInfo(
        key="rebet",
        display_name="ReBet",
        category=BookmakerCategory.SCRAPER,
        currency="USD",
        supports_live_betting=True,
        supports_cash_out=False,
        min_bet_gbp=Decimal("0.50"),
        max_bet_gbp=Decimal("5000.00"),
        scrape_url="https://rebet.app/",
    ),
    # US DFS
    "prizepicks": BookmakerInfo(
        key="prizepicks",
        display_name="PrizePicks",
        category=BookmakerCategory.SCRAPER,
        currency="USD",
        supports_live_betting=False,
        supports_cash_out=False,
        min_bet_gbp=Decimal("0.50"),
        max_bet_gbp=Decimal("1000.00"),
        scrape_url="https://prizepicks.com/",
    ),
    "underdog": BookmakerInfo(
        key="underdog",
        display_name="Underdog Fantasy",
        category=BookmakerCategory.SCRAPER,
        currency="USD",
        supports_live_betting=False,
        supports_cash_out=False,
        min_bet_gbp=Decimal("0.50"),
        max_bet_gbp=Decimal("1000.00"),
        scrape_url="https://underdogfantasy.com/",
    ),
    "pick6": BookmakerInfo(
        key="pick6",
        display_name="DraftKings Pick6",
        category=BookmakerCategory.SCRAPER,
        currency="USD",
        supports_live_betting=False,
        supports_cash_out=False,
        min_bet_gbp=Decimal("0.50"),
        max_bet_gbp=Decimal("1000.00"),
        scrape_url="https://pick6.draftkings.com/",
    ),
    "betr_dfs": BookmakerInfo(
        key="betr_dfs",
        display_name="Betr Picks",
        category=BookmakerCategory.SCRAPER,
        currency="USD",
        supports_live_betting=False,
        supports_cash_out=False,
        min_bet_gbp=Decimal("0.50"),
        max_bet_gbp=Decimal("1000.00"),
        scrape_url="https://www.betr.app/picks",
    ),
    # UK additions
    "casumo": BookmakerInfo(
        key="casumo",
        display_name="Casumo",
        category=BookmakerCategory.SCRAPER,
        currency="GBP",
        supports_live_betting=True,
        supports_cash_out=True,
        min_bet_gbp=Decimal("0.10"),
        max_bet_gbp=Decimal("10000.00"),
        scrape_url="https://casumo.com/",
    ),
    "grosvenor": BookmakerInfo(
        key="grosvenor",
        display_name="Grosvenor",
        category=BookmakerCategory.SCRAPER,
        currency="GBP",
        supports_live_betting=True,
        supports_cash_out=True,
        min_bet_gbp=Decimal("0.10"),
        max_bet_gbp=Decimal("10000.00"),
        scrape_url="https://www.grosvenorcasinos.com/sport",
    ),
    "leovegas": BookmakerInfo(
        key="leovegas",
        display_name="LeoVegas",
        category=BookmakerCategory.SCRAPER,
        currency="GBP",
        supports_live_betting=True,
        supports_cash_out=True,
        min_bet_gbp=Decimal("0.10"),
        max_bet_gbp=Decimal("10000.00"),
        scrape_url="https://www.leovegas.com/",
    ),
    "livescorebet": BookmakerInfo(
        key="livescorebet",
        display_name="LiveScore Bet",
        category=BookmakerCategory.SCRAPER,
        currency="GBP",
        supports_live_betting=True,
        supports_cash_out=True,
        min_bet_gbp=Decimal("0.10"),
        max_bet_gbp=Decimal("10000.00"),
        scrape_url="https://www.livescorebet.com/",
    ),
    "virginbet": BookmakerInfo(
        key="virginbet",
        display_name="Virgin Bet",
        category=BookmakerCategory.SCRAPER,
        currency="GBP",
        supports_live_betting=True,
        supports_cash_out=True,
        min_bet_gbp=Decimal("0.10"),
        max_bet_gbp=Decimal("10000.00"),
        scrape_url="https://www.virginbet.com/",
    ),
    # EU
    "betclic": BookmakerInfo(
        key="betclic",
        display_name="Betclic",
        category=BookmakerCategory.SCRAPER,
        currency="EUR",
        supports_live_betting=True,
        supports_cash_out=True,
        min_bet_gbp=Decimal("0.10"),
        max_bet_gbp=Decimal("10000.00"),
        scrape_url="https://www.betclic.com/",
    ),
    "betsson": BookmakerInfo(
        key="betsson",
        display_name="Betsson",
        category=BookmakerCategory.SCRAPER,
        currency="EUR",
        supports_live_betting=True,
        supports_cash_out=True,
        min_bet_gbp=Decimal("0.10"),
        max_bet_gbp=Decimal("25000.00"),
        scrape_url="https://betsson.com/",
    ),
    "coolbet": BookmakerInfo(
        key="coolbet",
        display_name="Coolbet",
        category=BookmakerCategory.SCRAPER,
        currency="EUR",
        supports_live_betting=True,
        supports_cash_out=True,
        min_bet_gbp=Decimal("0.10"),
        max_bet_gbp=Decimal("10000.00"),
        scrape_url="https://www.coolbet.com/",
    ),
    "everygame": BookmakerInfo(
        key="everygame",
        display_name="Everygame",
        category=BookmakerCategory.SCRAPER,
        currency="USD",
        supports_live_betting=True,
        supports_cash_out=False,
        min_bet_gbp=Decimal("1.00"),
        max_bet_gbp=Decimal("10000.00"),
        scrape_url="https://everygame.eu/",
    ),
    "gtbets": BookmakerInfo(
        key="gtbets",
        display_name="GTbets",
        category=BookmakerCategory.SCRAPER,
        currency="USD",
        supports_live_betting=True,
        supports_cash_out=False,
        min_bet_gbp=Decimal("1.00"),
        max_bet_gbp=Decimal("10000.00"),
        scrape_url="https://www.gtbets.ag/",
    ),
    "marathonbet": BookmakerInfo(
        key="marathonbet",
        display_name="Marathon Bet",
        category=BookmakerCategory.SCRAPER,
        currency="EUR",
        supports_live_betting=True,
        supports_cash_out=True,
        min_bet_gbp=Decimal("0.10"),
        max_bet_gbp=Decimal("25000.00"),
        scrape_url="https://www.marathonbet.co.uk/",
    ),
    "nordicbet": BookmakerInfo(
        key="nordicbet",
        display_name="NordicBet",
        category=BookmakerCategory.SCRAPER,
        currency="EUR",
        supports_live_betting=True,
        supports_cash_out=True,
        min_bet_gbp=Decimal("0.10"),
        max_bet_gbp=Decimal("10000.00"),
        scrape_url="https://www.nordicbet.com/",
    ),
    "parionssport": BookmakerInfo(
        key="parionssport",
        display_name="Parions Sport",
        category=BookmakerCategory.SCRAPER,
        currency="EUR",
        supports_live_betting=True,
        supports_cash_out=True,
        min_bet_gbp=Decimal("0.10"),
        max_bet_gbp=Decimal("10000.00"),
        scrape_url="https://www.enligne.parionssport.fdj.fr/",
    ),
    "pmu": BookmakerInfo(
        key="pmu",
        display_name="PMU",
        category=BookmakerCategory.SCRAPER,
        currency="EUR",
        supports_live_betting=True,
        supports_cash_out=False,
        min_bet_gbp=Decimal("0.10"),
        max_bet_gbp=Decimal("10000.00"),
        scrape_url="https://parisportif.pmu.fr/",
    ),
    "suprabets": BookmakerInfo(
        key="suprabets",
        display_name="Suprabets",
        category=BookmakerCategory.SCRAPER,
        currency="EUR",
        supports_live_betting=True,
        supports_cash_out=False,
        min_bet_gbp=Decimal("0.10"),
        max_bet_gbp=Decimal("10000.00"),
        scrape_url="https://www.suprabets.com/",
    ),
    "tipico": BookmakerInfo(
        key="tipico",
        display_name="Tipico",
        category=BookmakerCategory.SCRAPER,
        currency="EUR",
        supports_live_betting=True,
        supports_cash_out=True,
        min_bet_gbp=Decimal("0.10"),
        max_bet_gbp=Decimal("25000.00"),
        scrape_url="https://sports.tipico.de/",
    ),
    "winamax": BookmakerInfo(
        key="winamax",
        display_name="Winamax",
        category=BookmakerCategory.SCRAPER,
        currency="EUR",
        supports_live_betting=True,
        supports_cash_out=True,
        min_bet_gbp=Decimal("0.10"),
        max_bet_gbp=Decimal("25000.00"),
        scrape_url="https://winamax.fr/",
    ),
    "codere": BookmakerInfo(
        key="codere",
        display_name="Codere",
        category=BookmakerCategory.SCRAPER,
        currency="EUR",
        supports_live_betting=True,
        supports_cash_out=True,
        min_bet_gbp=Decimal("0.10"),
        max_bet_gbp=Decimal("10000.00"),
        scrape_url="https://www.codere.it/",
    ),
    "netbet": BookmakerInfo(
        key="netbet",
        display_name="NetBet",
        category=BookmakerCategory.SCRAPER,
        currency="EUR",
        supports_live_betting=True,
        supports_cash_out=True,
        min_bet_gbp=Decimal("0.10"),
        max_bet_gbp=Decimal("10000.00"),
        scrape_url="https://www.netbet.fr/",
    ),
    # SE
    "atg": BookmakerInfo(
        key="atg",
        display_name="ATG",
        category=BookmakerCategory.SCRAPER,
        currency="SEK",
        supports_live_betting=True,
        supports_cash_out=False,
        min_bet_gbp=Decimal("0.10"),
        max_bet_gbp=Decimal("10000.00"),
        scrape_url="https://www.atg.se/",
    ),
    "mrgreen": BookmakerInfo(
        key="mrgreen",
        display_name="Mr Green",
        category=BookmakerCategory.SCRAPER,
        currency="SEK",
        supports_live_betting=True,
        supports_cash_out=True,
        min_bet_gbp=Decimal("0.10"),
        max_bet_gbp=Decimal("10000.00"),
        scrape_url="https://www.mrgreen.se/",
    ),
    "svenskaspel": BookmakerInfo(
        key="svenskaspel",
        display_name="Svenska Spel",
        category=BookmakerCategory.SCRAPER,
        currency="SEK",
        supports_live_betting=True,
        supports_cash_out=False,
        min_bet_gbp=Decimal("0.10"),
        max_bet_gbp=Decimal("10000.00"),
        scrape_url="https://www.svenskaspel.se/",
    ),
    # AU
    "betr_au": BookmakerInfo(
        key="betr_au",
        display_name="Betr AU",
        category=BookmakerCategory.SCRAPER,
        currency="AUD",
        supports_live_betting=True,
        supports_cash_out=True,
        min_bet_gbp=Decimal("0.10"),
        max_bet_gbp=Decimal("10000.00"),
        scrape_url="https://betr.com.au/",
    ),
    "betright": BookmakerInfo(
        key="betright",
        display_name="Bet Right",
        category=BookmakerCategory.SCRAPER,
        currency="AUD",
        supports_live_betting=True,
        supports_cash_out=True,
        min_bet_gbp=Decimal("0.10"),
        max_bet_gbp=Decimal("10000.00"),
        scrape_url="https://www.betright.com.au/",
    ),
    "dabble": BookmakerInfo(
        key="dabble",
        display_name="Dabble",
        category=BookmakerCategory.SCRAPER,
        currency="AUD",
        supports_live_betting=True,
        supports_cash_out=True,
        min_bet_gbp=Decimal("0.10"),
        max_bet_gbp=Decimal("10000.00"),
        scrape_url="https://www.dabble.com.au/",
    ),
    "neds": BookmakerInfo(
        key="neds",
        display_name="Neds",
        category=BookmakerCategory.SCRAPER,
        currency="AUD",
        supports_live_betting=True,
        supports_cash_out=True,
        min_bet_gbp=Decimal("0.10"),
        max_bet_gbp=Decimal("10000.00"),
        scrape_url="https://www.neds.com.au/",
    ),
    "playup": BookmakerInfo(
        key="playup",
        display_name="PlayUp",
        category=BookmakerCategory.SCRAPER,
        currency="AUD",
        supports_live_betting=True,
        supports_cash_out=True,
        min_bet_gbp=Decimal("0.10"),
        max_bet_gbp=Decimal("10000.00"),
        scrape_url="https://www.playup.com.au/",
    ),
    "pointsbet": BookmakerInfo(
        key="pointsbet",
        display_name="PointsBet",
        category=BookmakerCategory.SCRAPER,
        currency="AUD",
        supports_live_betting=True,
        supports_cash_out=True,
        min_bet_gbp=Decimal("0.10"),
        max_bet_gbp=Decimal("10000.00"),
        scrape_url="https://pointsbet.com.au/",
    ),
    "sportsbet": BookmakerInfo(
        key="sportsbet",
        display_name="SportsBet",
        category=BookmakerCategory.SCRAPER,
        currency="AUD",
        supports_live_betting=True,
        supports_cash_out=True,
        min_bet_gbp=Decimal("0.10"),
        max_bet_gbp=Decimal("10000.00"),
        scrape_url="https://www.sportsbet.com.au/",
    ),
    "tab": BookmakerInfo(
        key="tab",
        display_name="TAB",
        category=BookmakerCategory.SCRAPER,
        currency="AUD",
        supports_live_betting=True,
        supports_cash_out=True,
        min_bet_gbp=Decimal("0.10"),
        max_bet_gbp=Decimal("10000.00"),
        scrape_url="https://tab.com.au/",
    ),
    "tabtouch": BookmakerInfo(
        key="tabtouch",
        display_name="TABtouch",
        category=BookmakerCategory.SCRAPER,
        currency="AUD",
        supports_live_betting=True,
        supports_cash_out=False,
        min_bet_gbp=Decimal("0.10"),
        max_bet_gbp=Decimal("10000.00"),
        scrape_url="https://www.tabtouch.mobi/",
    ),
}

BookmakerRegistry = BOOKMAKER_REGISTRY
