import type { ReconciliationRecord } from "./reconciliation-types";

export const FALLBACK_HISTORY: ReconciliationRecord[] = [
  {
    id: "REC-001",
    date: "2026-03-22",
    venue: "Binance",
    breakType: "position",
    liveValue: 1.2045,
    batchValue: 1.2,
    delta: 0.0045,
    status: "pending",
  },
  {
    id: "REC-002",
    date: "2026-03-22",
    venue: "Deribit",
    breakType: "pnl",
    liveValue: 34521.8,
    batchValue: 34200.0,
    delta: 321.8,
    status: "investigating",
  },
  {
    id: "REC-003",
    date: "2026-03-21",
    venue: "OKX",
    breakType: "fee",
    liveValue: 12.45,
    batchValue: 11.9,
    delta: 0.55,
    status: "resolved",
  },
  {
    id: "REC-004",
    date: "2026-03-21",
    venue: "Binance",
    breakType: "pnl",
    liveValue: -1520.3,
    batchValue: -1480.0,
    delta: -40.3,
    status: "resolved",
  },
  {
    id: "REC-005",
    date: "2026-03-21",
    venue: "Bybit",
    breakType: "position",
    liveValue: 0.5,
    batchValue: 0.512,
    delta: -0.012,
    status: "pending",
  },
  {
    id: "REC-006",
    date: "2026-03-20",
    venue: "Hyperliquid",
    breakType: "fee",
    liveValue: 8.32,
    batchValue: 7.8,
    delta: 0.52,
    status: "resolved",
  },
  {
    id: "REC-007",
    date: "2026-03-20",
    venue: "Deribit",
    breakType: "position",
    liveValue: 2.0,
    batchValue: 2.05,
    delta: -0.05,
    status: "investigating",
  },
  {
    id: "REC-008",
    date: "2026-03-19",
    venue: "OKX",
    breakType: "pnl",
    liveValue: 8730.12,
    batchValue: 8730.12,
    delta: 0.0,
    status: "resolved",
  },
  {
    id: "REC-009",
    date: "2026-03-19",
    venue: "Binance",
    breakType: "fee",
    liveValue: 45.6,
    batchValue: 43.2,
    delta: 2.4,
    status: "resolved",
  },
  {
    id: "REC-010",
    date: "2026-03-18",
    venue: "Bybit",
    breakType: "pnl",
    liveValue: -620.5,
    batchValue: -590.0,
    delta: -30.5,
    status: "resolved",
  },
  {
    id: "REC-011",
    date: "2026-03-18",
    venue: "Hyperliquid",
    breakType: "position",
    liveValue: 0.32,
    batchValue: 0.32,
    delta: 0.0,
    status: "resolved",
  },
  {
    id: "REC-012",
    date: "2026-03-17",
    venue: "Deribit",
    breakType: "fee",
    liveValue: 19.88,
    batchValue: 18.5,
    delta: 1.38,
    status: "resolved",
  },
];

export const DRIFT_METRICS = [
  {
    label: "Net Position (BTC)",
    liveValue: 4.2045,
    batchValue: 4.162,
    unit: "BTC",
    threshold: 2,
  },
  {
    label: "Unrealized PnL",
    liveValue: 41731.92,
    batchValue: 40930.12,
    threshold: 3,
  },
  { label: "Total Fees", liveValue: 86.25, batchValue: 81.4, threshold: 5 },
  { label: "Order Count", liveValue: 1247, batchValue: 1243, threshold: 1 },
  { label: "Fill Count", liveValue: 1189, batchValue: 1182, threshold: 1 },
];

export const UNRECONCILED_ITEMS = [
  {
    id: "UNR-001",
    type: "position" as const,
    description: "BTC-PERP position mismatch on Binance",
    timestamp: "2026-03-22T14:32:00Z",
    amount: 0.0045,
    venue: "Binance",
  },
  {
    id: "UNR-002",
    type: "fill" as const,
    description: "Missing fill for ETH-USDT limit order",
    timestamp: "2026-03-22T13:18:00Z",
    amount: 321.8,
    venue: "Deribit",
  },
  {
    id: "UNR-003",
    type: "transfer" as const,
    description: "Funding rate credit not reflected in batch",
    timestamp: "2026-03-22T12:00:00Z",
    amount: 12.45,
    venue: "OKX",
  },
  {
    id: "UNR-004",
    type: "fill" as const,
    description: "Partial fill quantity discrepancy SOL-PERP",
    timestamp: "2026-03-22T11:45:00Z",
    amount: 40.3,
    venue: "Bybit",
  },
  {
    id: "UNR-005",
    type: "position" as const,
    description: "AVAX-USDT position stale in batch snapshot",
    timestamp: "2026-03-22T10:22:00Z",
    amount: 0.012,
    venue: "Bybit",
  },
  {
    id: "UNR-006",
    type: "transfer" as const,
    description: "Withdrawal fee double-counted",
    timestamp: "2026-03-21T23:55:00Z",
    amount: 0.52,
    venue: "Hyperliquid",
  },
  {
    id: "UNR-007",
    type: "fill" as const,
    description: "Maker rebate missing for BTC-PERP batch",
    timestamp: "2026-03-21T22:10:00Z",
    amount: 2.4,
    venue: "Binance",
  },
];

export const VENUES = ["All", "Binance", "Deribit", "OKX", "Bybit", "Hyperliquid"];
export const BREAK_TYPES: Array<{ value: string; label: string }> = [
  { value: "all", label: "All Types" },
  { value: "position", label: "Position" },
  { value: "pnl", label: "PnL" },
  { value: "fee", label: "Fee" },
];
export const STATUS_OPTIONS: Array<{ value: string; label: string }> = [
  { value: "all", label: "All Statuses" },
  { value: "pending", label: "Pending" },
  { value: "investigating", label: "Investigating" },
  { value: "resolved", label: "Resolved" },
  { value: "rejected", label: "Rejected" },
];
