// AUTO-GENERATED by scripts/sync-capability-claims-to-ui.sh — do not edit.
// Source: unified-api-contracts/unified_api_contracts/internal/architecture_v2/capability_claims.py
//
// Stage 3E G2 § 4 — Odum-controlled Firebase custom claims. The
// `setCapabilityClaim` Cloud Function writes this shape; Firestore
// security rules and service middleware read it.
//
// SSOT: codex/14-playbooks/infra-spec/stage-3e-g2-env-split.md § 4.

export type ClientAudience =
  | "admin"
  | "im_desk"
  | "im_client"
  | "trading_platform_subscriber"
  | "reg_umbrella_client";

export interface CapabilityClaims {
  role: string;
  audience: ClientAudience;
  org_id: string | null;

  // capability flags (default false — locked-down)
  pricing_read_internal: boolean;
  strategy_catalogue_admin: boolean;
  im_desk: boolean;
  admin: boolean;
}

export const EMPTY_CAPABILITY_CLAIMS: CapabilityClaims = {
  role: "viewer",
  audience: "trading_platform_subscriber",
  org_id: null,
  pricing_read_internal: false,
  strategy_catalogue_admin: false,
  im_desk: false,
  admin: false,
};

/**
 * Safely coerce a raw `auth.token`-shaped object into a typed
 * CapabilityClaims. Unknown keys are dropped; missing flags default
 * to `false`; bad audience falls back to `trading_platform_subscriber`
 * (never `admin`). This is defence-in-depth on top of Firestore rules.
 */
export function capabilityClaimsFromToken(token: Record<string, unknown>): CapabilityClaims {
  const AUDS = new Set([
    "admin",
    "im_desk",
    "im_client",
    "trading_platform_subscriber",
    "reg_umbrella_client",
  ] as const);
  const raw = token.audience;
  const audience: ClientAudience =
    typeof raw === "string" && AUDS.has(raw as ClientAudience)
      ? (raw as ClientAudience)
      : "trading_platform_subscriber";

  return {
    role: typeof token.role === "string" ? token.role : "viewer",
    audience,
    org_id: typeof token.org_id === "string" ? token.org_id : null,
    pricing_read_internal: token.pricing_read_internal === true,
    strategy_catalogue_admin: token.strategy_catalogue_admin === true,
    im_desk: token.im_desk === true,
    admin: token.admin === true,
  };
}
