// Mock data — DevOps dashboard
export const systemHealth = { healthy: 42, degraded: 3, unhealthy: 2, total: 47 };

export const services = [
  {
    name: "execution-service",
    status: "healthy",
    cpu: 34,
    memory: 62,
    replicas: "3/3",
    latency: "12ms",
    version: "v2.14.3",
  },
  {
    name: "market-data-api",
    status: "healthy",
    cpu: 45,
    memory: 71,
    replicas: "5/5",
    latency: "8ms",
    version: "v1.8.0",
  },
  {
    name: "ml-inference",
    status: "degraded",
    cpu: 89,
    memory: 85,
    replicas: "2/3",
    latency: "145ms",
    version: "v3.2.1",
  },
  {
    name: "risk-service",
    status: "healthy",
    cpu: 28,
    memory: 45,
    replicas: "2/2",
    latency: "23ms",
    version: "v2.1.0",
  },
  {
    name: "strategy-service",
    status: "healthy",
    cpu: 56,
    memory: 68,
    replicas: "4/4",
    latency: "18ms",
    version: "v4.5.2",
  },
  {
    name: "position-monitor",
    status: "unhealthy",
    cpu: 12,
    memory: 34,
    replicas: "0/2",
    latency: "-",
    version: "v1.2.0",
  },
  {
    name: "alerting-service",
    status: "healthy",
    cpu: 22,
    memory: 38,
    replicas: "2/2",
    latency: "5ms",
    version: "v2.0.1",
  },
  {
    name: "pnl-attribution",
    status: "healthy",
    cpu: 41,
    memory: 55,
    replicas: "2/2",
    latency: "89ms",
    version: "v1.5.4",
  },
];

export const recentDeployments = [
  {
    id: "DEP-1842",
    service: "execution-service",
    version: "v2.14.3",
    env: "prod",
    status: "success",
    time: "12m ago",
    commit: "a3f7c21",
    cloud: "AWS",
  },
  {
    id: "DEP-1841",
    service: "market-data-api",
    version: "v1.8.0",
    env: "prod",
    status: "success",
    time: "45m ago",
    commit: "b2e9f45",
    cloud: "GCP",
  },
  {
    id: "DEP-1840",
    service: "ml-inference",
    version: "v3.2.1",
    env: "staging",
    status: "running",
    time: "1h ago",
    commit: "c4d8a12",
    cloud: "AWS",
  },
  {
    id: "DEP-1839",
    service: "risk-service",
    version: "v2.1.0",
    env: "prod",
    status: "failed",
    time: "2h ago",
    commit: "e7f9b34",
    cloud: "AWS",
  },
  {
    id: "DEP-1838",
    service: "strategy-service",
    version: "v4.5.2",
    env: "prod",
    status: "success",
    time: "3h ago",
    commit: "f1a2c56",
    cloud: "GCP",
  },
];

export const jobs = [
  {
    id: "JOB-892",
    name: "daily-reconciliation",
    status: "running",
    progress: 67,
    startTime: "2h ago",
    duration: "45m",
    schedule: "Daily 00:00 UTC",
  },
  {
    id: "JOB-891",
    name: "feature-pipeline",
    status: "completed",
    progress: 100,
    startTime: "3h ago",
    duration: "28m",
    schedule: "Hourly",
  },
  {
    id: "JOB-890",
    name: "model-training",
    status: "queued",
    progress: 0,
    startTime: "-",
    duration: "-",
    schedule: "Weekly",
  },
  {
    id: "JOB-889",
    name: "data-backup",
    status: "completed",
    progress: 100,
    startTime: "6h ago",
    duration: "15m",
    schedule: "Daily 06:00 UTC",
  },
  {
    id: "JOB-888",
    name: "report-generation",
    status: "failed",
    progress: 34,
    startTime: "8h ago",
    duration: "12m",
    schedule: "Daily 08:00 UTC",
  },
];

export const versionBranches = [
  {
    service: "execution-service",
    branches: ["main", "v2.14.x", "v2.13.x", "feat/new-algo"],
    current: "main",
  },
  {
    service: "market-data-api",
    branches: ["main", "v1.8.x", "v1.7.x", "fix/latency"],
    current: "main",
  },
  {
    service: "ml-inference",
    branches: ["main", "v3.2.x", "v3.1.x", "experiment/gpt5"],
    current: "main",
  },
  {
    service: "risk-service",
    branches: ["main", "v2.1.x", "v2.0.x"],
    current: "main",
  },
];

export const alerts = [
  {
    id: 1,
    severity: "critical",
    message: "position-monitor service down (0/2 replicas)",
    time: "5m ago",
    service: "position-monitor",
  },
  {
    id: 2,
    severity: "warning",
    message: "ml-inference CPU usage at 89%",
    time: "12m ago",
    service: "ml-inference",
  },
  {
    id: 3,
    severity: "warning",
    message: "market-data-api latency spike detected",
    time: "18m ago",
    service: "market-data-api",
  },
  {
    id: 4,
    severity: "info",
    message: "Scheduled maintenance window in 2 hours",
    time: "30m ago",
    service: "system",
  },
];

export const resourceUsage = {
  cpu: { current: 45, limit: 100 },
  memory: { current: 62, limit: 100 },
  storage: { current: 1.2, limit: 2.0 },
  network: { in: "1.2 GB/s", out: "890 MB/s" },
};
